import {motion,AnimatePresence,useReducedMotion} from 'motion/react';
import React,{useEffect,useRef,useState} from 'react';
import {UploadSimple,ArrowsOutCardinal,CaretDown,Trash} from '@phosphor-icons/react';
import Avatar from './Avatar';
import {tx} from './language';
import {prepareAppearanceImage,uploadImage} from './appearance-image';
import './AppearanceEditor.css';
const dirty=()=>tx('尚未保存，点击“保存装扮”后生效','Unsaved changes. Click Save appearance to apply.');
export default function AppearanceEditor({profile,onSaved}){
 const reduced=useReducedMotion();
 const [data,setData]=useState(null),[settings,setSettings]=useState(null),[frames,setFrames]=useState([]),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[deleting,setDeleting]=useState(null),[target,setTarget]=useState('frame');
 const pending=useRef(new Map()),removed=useRef(new Set()),cover=useRef(null),drag=useRef(null),previewBox=useRef(null),mask=useRef(null),alive=useRef(true);
 const request=async(path,method='GET',body)=>{const r=await fetch('/api/campus-social'+path,{method,headers:{'X-Workspace-Token':profile.token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.message||d.detail||tx('保存失败，请重试','Could not save, please retry'));return d};
 useEffect(()=>{alive.current=true;request('/me/appearance').then(d=>{if(alive.current){setData(d);setSettings(d.settings);setFrames(d.frames||d.settings.frames||[])}}).catch(e=>setStatus(e.message));return()=>{alive.current=false;pending.current.forEach(p=>URL.revokeObjectURL(p.url));if(cover.current)URL.revokeObjectURL(cover.current.url)}},[profile.account.id]);
 const selected=settings?.frame==='auto'?(data?.gifted?'teacher-day-2026':'none'):settings?.frame;
 const selectedFrame=frames.find(f=>f.url===settings?.customFrame);
 const frameUrl=selected==='teacher-day-2026'?'/images/teacher-day-2026-640.webp':selected==='custom'?(selectedFrame?.preview||selectedFrame?.url||settings.customFrame):'';
 useEffect(()=>{mask.current=null;if(!frameUrl)return;let active=true;const image=new Image();image.onload=()=>{try{const canvas=document.createElement('canvas');canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(image,0,0);if(active)mask.current={ctx,width:canvas.width,height:canvas.height}}catch{}};image.src=frameUrl;return()=>{active=false}},[frameUrl]);
 const edit=changes=>{setSettings(s=>({...s,...changes}));setStatus(dirty())};
 async function selectFiles(kind,files){if(busy||!files.length)return;setBusy(true);setStatus(tx('正在处理图片…','Preparing images…'));try{for(const file of files){const prepared=await prepareAppearanceImage(file,kind);if(!alive.current)return;const url=URL.createObjectURL(prepared);if(kind==='banner'){if(cover.current)URL.revokeObjectURL(cover.current.url);cover.current={file:prepared,url};edit({banner:url})}else{const id='pending-'+crypto.randomUUID();pending.current.set(id,{file:new File([prepared],file.name,{type:prepared.type}),url});const item={id,name:file.name,url,thumbnail:url};setFrames(v=>[...v,item]);edit({frame:'custom',customFrame:url,scale:1,x:0,y:0})}}setStatus(tx('图片已压缩并生成预览，保存后生效','Images compressed and previewed. Save to apply.'))}catch(e){setStatus(e.message)}finally{setBusy(false)}}
 function removeOne(f){const p=pending.current.get(f.id);if(p){URL.revokeObjectURL(p.url);pending.current.delete(f.id)}else removed.current.add(f.id);setFrames(v=>v.filter(x=>x.id!==f.id));if(settings.customFrame===f.url)edit({frame:settings.frame==='custom'?'none':settings.frame,customFrame:'',scale:1,x:0,y:0});setDeleting(null);setStatus(dirty())}
 async function save(){if(busy)return;setBusy(true);setStatus(tx('正在保存装扮…','Saving appearance…'));try{let custom=settings.customFrame;for(const id of [...removed.current]){await request('/me/appearance/frames/'+encodeURIComponent(id),'DELETE');removed.current.delete(id)}if(cover.current){const p=cover.current;const saved=await uploadImage('/api/campus-social/me/appearance/banner',p.file,profile.token,n=>setStatus(tx('保存封面：','Saving cover: ')+n+'%'));cover.current=null;URL.revokeObjectURL(p.url);setSettings(s=>({...s,banner:saved.banner}))}for(const [id,p] of [...pending.current]){const saved=await uploadImage('/api/campus-social/me/appearance/frame',p.file,profile.token,n=>setStatus(tx('保存头像框：','Saving frame: ')+n+'%'));const item=saved.frames.find(f=>f.url===saved.customFrame);if(custom===p.url)custom=item.url;pending.current.delete(id);URL.revokeObjectURL(p.url);setFrames(v=>v.map(f=>f.id===id?item:f));setSettings(s=>({...s,customFrame:s.customFrame===p.url?item.url:s.customFrame}))}await request('/me/appearance','PUT',{...settings,customFrame:custom});const d=await request('/me/appearance');setData(d);setSettings(d.settings);setFrames(d.frames);setStatus(tx('装扮已保存','Appearance saved'));await onSaved?.()}catch(e){setStatus(e.message)}finally{setBusy(false)}}
 function beginDrag(e){if(busy)return;const avatar=previewBox.current?.querySelector('.campus-avatar');if(!avatar)return;const box=avatar.getBoundingClientRect();if(target==='frame'){const img=avatar.querySelector('.teacher-avatar-frame'),m=mask.current;if(!img||!m)return;const b=img.getBoundingClientRect(),ratio=Math.min(b.width/m.width,b.height/m.height),left=b.left+(b.width-m.width*ratio)/2,top=b.top+(b.height-m.height*ratio)/2,x=Math.floor((e.clientX-left)/ratio),y=Math.floor((e.clientY-top)/ratio);if(x<0||y<0||x>=m.width||y>=m.height||m.ctx.getImageData(x,y,1,1).data[3]<24)return;}else{const dx=(e.clientX-(box.left+box.width/2))/(box.width/2),dy=(e.clientY-(box.top+box.height/2))/(box.height/2);if(dx*dx+dy*dy>1||!profile.account.avatarUrl)return;}e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);const keys=target==='frame'?['x','y']:['avatarX','avatarY'];drag.current={x:e.clientX,y:e.clientY,oldX:settings[keys[0]]||0,oldY:settings[keys[1]]||0,keys,width:box.width*(target==='frame'?1.28:1),height:box.height*(target==='frame'?1.28:1)}}
 if(!settings)return <p role="status">{status||tx('加载装扮…','Loading appearance…')}</p>;
 const preview={...profile.account,avatarFrame:selected==='none'?'':selected,appearance:{frameUrl,scale:settings.scale,x:settings.x,y:settings.y,avatarScale:settings.avatarScale,avatarX:settings.avatarX,avatarY:settings.avatarY}};
 const scaleKey=target==='frame'?'scale':'avatarScale',keys=target==='frame'?['x','y']:['avatarX','avatarY'];
 return <section className="appearance-editor" aria-busy={busy}><h2>{tx('主页与装扮','Profile appearance')}</h2>
  <div className="appearance-banner">{settings.banner&&<img src={settings.banner} alt={tx('主页封面','Profile cover')}/>}</div>
  <div className="appearance-banner-actions"><label className="appearance-upload"><UploadSimple size={18}/>{tx('上传主页封面','Upload cover')}<input type="file" accept="image/png,image/jpeg" disabled={busy} onChange={e=>{const files=[...e.target.files];e.target.value='';selectFiles('banner',files)}}/></label></div>
  <p className="appearance-upload-status" role="status" aria-live="polite">{status||tx('所有改动均在点击“保存装扮”后生效','All changes apply only after you click Save appearance.')}</p>
  {busy&&<div className="motion-busy" aria-hidden="true"><span/></div>}<div className="appearance-columns"><div><div ref={previewBox} className={'appearance-preview editing-'+target} onPointerDown={beginDrag} onPointerMove={e=>{const d=drag.current;if(!d||busy)return;edit({[d.keys[0]]:Math.max(-.5,Math.min(.5,d.oldX+(e.clientX-d.x)/d.width)),[d.keys[1]]:Math.max(-.5,Math.min(.5,d.oldY+(e.clientY-d.y)/d.height))})}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}><Avatar person={preview}/></div><p className="appearance-hint"><ArrowsOutCardinal size={16}/>{target==='frame'?tx('拖动头像框有图案的位置，透明处不会移动','Drag a visible part of the frame. Transparent areas do not move it.'):tx('拖动圆形头像调整位置','Drag the circular avatar to reposition it.')}</p></div>
  <div className="appearance-controls"><label>{tx('装配头像框','Equipped frame')}<span className="appearance-select"><select disabled={busy} value={settings.frame==='custom'?'custom:'+selectedFrame?.id:settings.frame} onChange={e=>{const value=e.target.value;if(value.startsWith('custom:')){const f=frames.find(f=>f.id===value.slice(7));edit({frame:'custom',customFrame:f.url,scale:f.scale||1,x:f.x||0,y:f.y||0})}else edit({frame:value})}}><option value="none">{tx('不装配','None')}</option><option value="auto">{tx('默认装扮','Default')}</option>{data.gifted&&<option value="teacher-day-2026">{tx('2026 教师节限定','Teachers’ Day 2026')}</option>}{frames.map(f=><option key={f.id} value={'custom:'+f.id}>{f.name}</option>)}</select><CaretDown size={18} aria-hidden="true"/></span></label>
   <label className="appearance-upload"><UploadSimple size={18}/>{tx('添加 PNG 头像框（可多选）','Add PNG frames (multiple allowed)')}<input type="file" accept="image/png" multiple disabled={busy} onChange={e=>{const files=[...e.target.files];e.target.value='';selectFiles('frame',files)}}/></label>
   <div className="appearance-target" role="group" aria-label={tx('调整对象','Adjust layer')}><button type="button" disabled={busy||!profile.account.avatarUrl} aria-pressed={target==='avatar'} onClick={()=>setTarget('avatar')}>{tx('调整头像','Adjust avatar')}</button><button type="button" disabled={busy} aria-pressed={target==='frame'} onClick={()=>setTarget('frame')}>{tx('调整头像框','Adjust frame')}</button></div>
   <label>{target==='frame'?tx('头像框缩放','Frame scale'):tx('头像缩放','Avatar scale')} · {Math.round((settings[scaleKey]||1)*100)}%<input type="range" disabled={busy} min={target==='frame'?.5:1} max={target==='frame'?1.8:2.5} step="0.01" value={settings[scaleKey]||1} onChange={e=>edit({[scaleKey]:+e.target.value})}/></label>
   {keys.map((key,i)=><label key={key}>{i?tx('垂直位置','Vertical position'):tx('水平位置','Horizontal position')}<input type="range" disabled={busy} min="-0.5" max="0.5" step="0.01" value={settings[key]||0} onChange={e=>edit({[key]:+e.target.value})}/></label>)}
  </div></div>
  <div className="frame-library"><h3>{tx('我的头像框','My frames')} · {frames.length}</h3><div className="frame-library-grid"><AnimatePresence initial={false}>{frames.map(f=><motion.article layout={!reduced} initial={{opacity:0,scale:reduced?1:.95}} animate={{opacity:1,scale:1}} exit={{opacity:0,scale:reduced?1:.95}} transition={{duration:reduced?0:.2}} className={settings.frame==='custom'&&settings.customFrame===f.url?'selected':''} key={f.id}><button type="button" className="frame-choice" disabled={busy} aria-pressed={settings.frame==='custom'&&settings.customFrame===f.url} onClick={()=>edit({frame:'custom',customFrame:f.url,scale:f.scale||1,x:f.x||0,y:f.y||0})}><img src={f.thumbnail||f.url} alt="" loading="lazy" decoding="async"/><span>{f.name}</span></button><button type="button" className="frame-remove" disabled={busy} aria-label={tx('删除头像框：','Delete frame: ')+f.name} onClick={()=>setDeleting(f)}><Trash size={17}/>{tx('删除此框','Delete this frame')}</button></motion.article>)}</AnimatePresence></div>{!frames.length&&<p>{tx('可以添加多个头像框，按需选择装配。','Add multiple frames and choose which one to wear.')}</p>}</div>
  {deleting&&<div className="appearance-delete" role="alert"><p>{tx('只删除这个头像框：','Delete only this frame: ')}<strong>{deleting.name}</strong>{tx('？保存后生效，其他头像框会保留。','? Applies when you save. Other frames are kept.')}</p><div className="appearance-delete-actions"><button type="button" className="appearance-danger" disabled={busy} onClick={()=>removeOne(deleting)}>{tx('确认删除此框','Delete this frame')}</button><button type="button" disabled={busy} onClick={()=>setDeleting(null)}>{tx('取消','Cancel')}</button></div></div>}
  <fieldset><legend>{tx('显示的标签','Visible tags')}</legend>{data.gifted&&<label className="appearance-check"><input type="checkbox" disabled={busy} checked={settings.holidayBadge} onChange={e=>edit({holidayBadge:e.target.checked})}/>{tx('教师节限定标签','Teachers’ Day badge')}</label>}{data.tags.map(tag=><label className="appearance-check" key={tag}><input type="checkbox" disabled={busy} checked={settings.tags===null||settings.tags.includes(tag)} onChange={e=>{const selected=settings.tags??data.tags;edit({tags:e.target.checked?[...selected,tag]:selected.filter(t=>t!==tag)})}}/>{tag}</label>)}</fieldset>
  <button type="button" className="appearance-save" disabled={busy} onClick={save}>{busy?tx('保存中…','Saving…'):tx('保存装扮','Save appearance')}</button>
 </section>
}
