import React,{useEffect,useRef} from 'react';
import {createPortal} from 'react-dom';
// Original grid-based ASCII trail, based on the user's visual reference.
export default function AsciiCursor(){const canvas=useRef();useEffect(()=>{
 if(matchMedia('(prefers-reduced-motion: reduce), (pointer: coarse)').matches)return;
 const el=canvas.current,ctx=el.getContext('2d'),cells=new Map(),symbols='01{}[]<>/$*+#@';const cell=24;let frame=0,last=0,lastPoint=null,w=innerWidth,h=innerHeight;
 const size=()=>{w=innerWidth;h=innerHeight;const dpr=Math.min(devicePixelRatio||1,1.5);el.width=w*dpr;el.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)};size();
 const stamp=(x,y)=>{const cx=Math.floor(x/cell),cy=Math.floor(y/cell),now=performance.now();for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){if(Math.abs(dx)+Math.abs(dy)>1&&Math.random()<.4)continue;const key=(cx+dx)+','+(cy+dy);cells.set(key,{x:(cx+dx)*cell,y:(cy+dy)*cell,born:now,life:380+Math.random()*450,seed:Math.floor(Math.random()*symbols.length)});}while(cells.size>260)cells.delete(cells.keys().next().value)};
 const draw=now=>{frame=0;if(now-last<28){frame=requestAnimationFrame(draw);return}last=now;ctx.clearRect(0,0,w,h);ctx.font='bold 17px ui-monospace, monospace';ctx.textAlign='center';ctx.textBaseline='middle';for(const[key,p]of cells){const age=now-p.born;if(age>p.life){cells.delete(key);continue}ctx.fillStyle='#fff';ctx.fillRect(p.x,p.y,cell,cell);ctx.strokeStyle='#e3e8e4';ctx.strokeRect(p.x+.5,p.y+.5,cell-1,cell-1);if(age<p.life*.84){ctx.fillStyle='#24e438';ctx.fillText(symbols[(p.seed+Math.floor(age/90))%symbols.length],p.x+cell/2,p.y+cell/2)}}if(cells.size)frame=requestAnimationFrame(draw)};
 const move=e=>{if(document.hidden||e.target.closest('input,textarea,video'))return;const x=e.clientX,y=e.clientY;if(lastPoint){const dist=Math.hypot(x-lastPoint.x,y-lastPoint.y);if(dist<cell*.4)return;const steps=Math.min(12,Math.ceil(dist/cell));for(let i=1;i<=steps;i++)stamp(lastPoint.x+(x-lastPoint.x)*i/steps,lastPoint.y+(y-lastPoint.y)*i/steps)}else stamp(x,y);lastPoint={x,y};if(!frame)frame=requestAnimationFrame(draw)};
 const pause=()=>{cells.clear();lastPoint=null;cancelAnimationFrame(frame);frame=0;ctx.clearRect(0,0,w,h)};addEventListener('pointermove',move,{passive:true});addEventListener('resize',size,{passive:true});addEventListener('scroll',pause,{passive:true});document.addEventListener('visibilitychange',pause);return()=>{pause();removeEventListener('pointermove',move);removeEventListener('resize',size);removeEventListener('scroll',pause);document.removeEventListener('visibilitychange',pause)};
 },[]);return createPortal(<canvas className="ascii-cursor-canvas" ref={canvas} aria-hidden="true" style={{position:'fixed',inset:0,width:'100%',height:'100%',pointerEvents:'none',zIndex:0}}/>,document.body)}
