import { build } from "esbuild";
import { existsSync } from "node:fs";
import { updateModulePreloads } from "./build/preloads.mjs";
const shared = {
  bundle: true,
  minify: true,
  jsx: "automatic",
  define: { "process.env.NODE_ENV": '"production"' },
  entryNames: "[name]",
  legalComments: "eof",
  banner: {
    js: "/* Generated by frontend/build.mjs. Edit frontend/ source, then run npm run build. */",
    css: "/* Generated by frontend/build.mjs. Edit frontend/ source, then run npm run build. */",
  },
};
await build({
  ...shared,
  entryPoints: ["frontend/home.jsx"],
  outdir: "src/main/resources/static/javascript/darkveil",
});
const uiBuild = await build({
  ...shared,
  metafile: true,
  format: "esm",
  splitting: true,
  chunkNames: "chunks/[name]-[hash]",
  entryPoints: [
    "frontend/navigation.jsx",
    "frontend/auth.jsx",
    "frontend/workspace.jsx",
    "frontend/social.jsx",
    "frontend/account.jsx",
    "frontend/suggestion.jsx",
    "frontend/catalog.jsx",
    "frontend/calendar.jsx",
    "frontend/booking.jsx",
  ],
  outdir: "src/main/resources/static/javascript/ui",
});

await build({
  ...shared,
  entryPoints: ["frontend/booking-nav.jsx"],
  outfile:
    process.env.BOOKING_ASSET_FILE ||
    (existsSync("booking/school")
      ? "booking/school/aero-shards.bundle.js"
      : existsSync("../outputs/qpsw-mrbs/school")
        ? "../outputs/qpsw-mrbs/school/aero-shards.bundle.js"
        : "src/main/resources/static/javascript/booking/aero-shards.bundle.js"),
  format: "iife",
});

// Templates preload shared chunks without changing the lazy-loading boundaries.
await updateModulePreloads("src/main/resources/templates", uiBuild.metafile.outputs);
