import React,{useEffect,useRef,useState} from 'react';
import {tx} from './language';
import './DateJump.css';
export default function DateJump({value,onChange,children}){
 const [open,setOpen]=useState(false),[draft,setDraft]=useState(value),[position,setPosition]=useState({}),root=useRef(),trigger=useRef();
 useEffect(()=>{if(!open)return;const click=e=>{if(!root.current?.contains(e.target))setOpen(false)};const close=()=>setOpen(false);window.addEventListener('resize',close);window.addEventListener('scroll',close);const key=e=>{if(e.key==='Escape'){setOpen(false);trigger.current?.focus()}};document.addEventListener('pointerdown',click);document.addEventListener('keydown',key);return()=>{document.removeEventListener('pointerdown',click);document.removeEventListener('keydown',key);window.removeEventListener('resize',close);window.removeEventListener('scroll',close)}},[open]);
 const [year,month,day]=draft.split('-').map(Number),maxDay=new Date(year,month,0).getDate();
 const update=(y,m,d)=>setDraft(`${y}-${String(m).padStart(2,'0')}-${String(Math.min(d,new Date(y,m,0).getDate())).padStart(2,'0')}`);
 return <span className="date-jump" ref={root}><button ref={trigger} type="button" className="date-jump-trigger" aria-label={tx('选择年月日','Choose date')} aria-expanded={open} onClick={()=>{const r=trigger.current.getBoundingClientRect();setPosition({left:Math.max(16,Math.min(r.left,window.innerWidth-Math.min(320,window.innerWidth-48)-16)),top:Math.max(16,Math.min(r.bottom+10,window.innerHeight-180))});setDraft(value);setOpen(v=>!v)}}>{children}<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><path d="m6 9 6 6 6-6"/></svg></button>{open&&<span className="date-jump-popup" style={position} role="group" aria-label={tx('选择年月日','Choose date')}><span className="date-jump-fields"><label>{tx('年','Year')}<select autoFocus value={year} onChange={e=>update(+e.target.value,month,day)}>{Array.from({length:51},(_,i)=>new Date().getFullYear()-10+i).map(y=><option key={y}>{y}</option>)}</select></label><label>{tx('月','Month')}<select value={month} onChange={e=>update(year,+e.target.value,day)}>{Array.from({length:12},(_,i)=>i+1).map(m=><option key={m}>{m}</option>)}</select></label><label>{tx('日','Day')}<select value={day} onChange={e=>update(year,month,+e.target.value)}>{Array.from({length:maxDay},(_,i)=>i+1).map(d=><option key={d}>{d}</option>)}</select></label></span><button className="date-jump-go" type="button" onClick={()=>{onChange(draft);setOpen(false);trigger.current?.focus()}}>{tx('跳转到此日期','Go to date')}</button></span>}</span>
}
