import {useEffect,useRef,useState} from 'react';
import {tx,tr} from './language';
export default function EmailEditor({profile,write,onSaved}){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[code,setCode]=useState(''),[sent,setSent]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[until,setUntil]=useState(0),[now,setNow]=useState(Date.now());
 const form=useRef(),lock=useRef(false),codeField=useRef();
 useEffect(()=>{if(until<=Date.now())return;const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[until]);
 const remaining=Math.max(0,Math.ceil((until-now)/1000));
 async function act(fn){if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(tr(e.message));}finally{lock.current=false;setBusy(false);}}
 return <form ref={form} className="account-card" onSubmit={e=>{e.preventDefault();act(async()=>{await write('/me/email','PUT',{email:sent,code});setNotice(tx('邮箱已更新，下次请使用新邮箱登录。','Email updated. Use your new email to sign in.'));setSent('');setPassword('');setEmail('');setCode('');await onSaved();});}}><div className="account-card-title"><h2>{tx('登录邮箱','Sign-in email')}</h2></div><p className="account-email-current">{profile.email}</p><p className="account-hint">{tx('验证新邮箱后即可更换，私信和社团记录会保留。','Verify your new email to change it. Messages and club records will stay with your account.')}</p><fieldset disabled={busy} className="email-fields"><div className="account-field-grid"><label>{tx('新邮箱','New email')}<input type="email" autoComplete="email" maxLength={254} required value={email} onChange={e=>{setEmail(e.target.value);setSent('');setCode('');}}/></label><label>{tx('当前密码','Current password')}<input type="password" autoComplete="current-password" maxLength={128} required value={password} onChange={e=>setPassword(e.target.value)}/></label></div><div className="account-email-actions"><button type="button" className="account-secondary" disabled={busy||remaining>0} onClick={()=>{if(![...form.current.querySelectorAll('input[type="email"],input[type="password"]')].every(input=>input.reportValidity()))return;act(async()=>{const target=email.trim().toLowerCase();await write('/me/email/code','POST',{email:target,currentPassword:password});setSent(target);setUntil(Date.now()+60000);setNow(Date.now());setNotice(tx('验证码已发送，请检查新邮箱（含垃圾邮件）。','Code sent. Check your new inbox and spam folder.'));setTimeout(()=>codeField.current?.focus(),0);});}}>{remaining>0?`${remaining}s`:tx('发送验证码','Send code')}</button>{sent&&<label>{tx('6 位验证码','6-digit code')}<input ref={codeField} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required/></label>}{sent&&<button disabled={busy||code.length!==6} type="submit">{tx('确认修改邮箱','Confirm email change')}</button>}</div></fieldset>{error&&<p role="alert" className="account-error">{error}</p>}{notice&&<p role="status" className="account-notice">{notice}</p>}</form>;
}
