import React,{useEffect,useRef,useState} from 'react';
import {tx,en} from './language';
export default function JoinRequestsPanel({club,token,onChanged}){
 const [items,setItems]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(''),[retry,setRetry]=useState(0);const lock=useRef(false);
 const path=`/api/club-workspace/${club}/join-requests`;
 async function api(url,options){const r=await fetch(url,options),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||tx('请求未成功','Request failed'));return d;}
 useEffect(()=>{const c=new AbortController();api(path,{signal:c.signal}).then(setItems).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>c.abort()},[club,retry]);
 async function decide(id,status){if(lock.current)return;lock.current=true;setBusy(id);setError('');try{const d=await api(path+'/'+id,{method:'POST',headers:{'Content-Type':'application/json','X-Workspace-Token':token},body:JSON.stringify({status})});setItems(xs=>xs.map(x=>x.id===id?d:x));await onChanged()}catch(e){setError(e.message)}finally{lock.current=false;setBusy('')}}
 return <section className="ws-panel join-review"><div className="ws-section-head"><div><h3>{tx('入社申请','Membership applications')}</h3><p>{tx('通过申请后，申请人会自动加入本社团。','Approving an application adds the applicant to this club.')}</p></div></div>{error&&<p role="alert" className="ws-error">{error} <button onClick={()=>setRetry(n=>n+1)}>{tx('重试','Retry')}</button></p>}{items===null?<p>{tx('正在载入…','Loading…')}</p>:!items.length?<p className="ws-help">{tx('暂无入社申请。','No applications yet.')}</p>:items.map(i=><article key={i.id}><div><strong>{en&&i.nameEn?i.nameEn:i.name}</strong><time dateTime={i.createdAt}>{new Date(i.createdAt).toLocaleDateString(en?'en-GB':'zh-CN')}</time><p>{i.note||tx('未填写附言','No introduction provided')}</p></div>{i.status==='pending'?<div className="join-review-actions"><button disabled={!!busy} onClick={()=>decide(i.id,'declined')}>{tx('拒绝','Decline')}</button><button className="ws-primary" disabled={!!busy} onClick={()=>decide(i.id,'approved')}>{busy===i.id?tx('处理中…','Saving…'):tx('同意入社','Approve')}</button></div>:<span className="ws-badge">{i.status==='approved'?tx('已通过','Approved'):tx('已拒绝','Declined')}</span>}</article>)}</section>;
}
