// Messages use ECDH + HKDF + AES-GCM. Recovery copies are encrypted with a separate server secret.
const encode=new TextEncoder(),decode=new TextDecoder();
export const b64=a=>btoa(String.fromCharCode(...new Uint8Array(a)));
export const unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
const hex=b=>Array.from(new Uint8Array(b),v=>v.toString(16).padStart(2,'0')).join('');
export async function makeIdentity(){const keys=await crypto.subtle.generateKey({name:'ECDH',namedCurve:'P-256'},true,['deriveBits']);const publicKey=b64(await crypto.subtle.exportKey('spki',keys.publicKey));return {privateKey:keys.privateKey,publicKey,fingerprint:hex(await crypto.subtle.digest('SHA-256',unb64(publicKey)))};}
function db(){return new Promise((resolve,reject)=>{const r=indexedDB.open('qpwfl-campus-keys',1);r.onupgradeneeded=()=>r.result.createObjectStore('identities');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(Error('无法使用本机密钥存储，请检查浏览器隐私设置'));});}
async function local(id,value){const d=await db();try{return await new Promise((resolve,reject)=>{const t=d.transaction('identities',value?'readwrite':'readonly'),s=t.objectStore('identities'),r=value?s.put(value,id):s.get(id);let result;r.onsuccess=()=>result=r.result;t.oncomplete=()=>resolve(result);t.onerror=()=>reject(Error('本机密钥保存失败'));});}finally{d.close();}}
const starting=new Map();
async function recoverIdentity(id,api){const saved=await api('/keys/recovery');if(!saved.ready)return null;const privateKey=await crypto.subtle.importKey('pkcs8',unb64(saved.privateKey),{name:'ECDH',namedCurve:'P-256'},true,['deriveBits']);const own={privateKey,publicKey:saved.publicKey,fingerprint:hex(await crypto.subtle.digest('SHA-256',unb64(saved.publicKey)))};await local(id,own);return own;}
async function escrow(own,write){await write('/keys/recovery','PUT',{publicKey:own.publicKey,privateKey:b64(await crypto.subtle.exportKey('pkcs8',own.privateKey))});}
export function ensureIdentity(id,api,write){if(!starting.has(id))starting.set(id,(async()=>{if(!crypto.subtle)throw Error('加密私信需要 HTTPS 或 localhost 安全连接');let own=await local(id);let remote=await api('/keys/'+id);if(!own)own=await recoverIdentity(id,api);if(!own&&!remote.ready){await write('/keys/provision','POST',{account:id});own=await recoverIdentity(id,api);remote=await api('/keys/'+id);}if(!own)throw Error('此账号尚未同步旧私信，请先在原设备登录一次，再在此设备重新登录');if(remote.ready&&remote.fingerprint!==own.fingerprint)throw Error('请重新登录以同步加密私信');await escrow(own,write);return own;})().catch(e=>{starting.delete(id);throw e;}));return starting.get(id);}

const context=(sender,recipient,senderKey,recipientKey)=>encode.encode(['qpwfl-message-v1',sender,recipient,senderKey,recipientKey].join('|'));
async function aes(own,peer,iv,info){const pub=await crypto.subtle.importKey('spki',unb64(peer.publicKey),{name:'ECDH',namedCurve:'P-256'},false,[]);const bits=await crypto.subtle.deriveBits({name:'ECDH',public:pub},own.privateKey,256);const secret=await crypto.subtle.importKey('raw',bits,'HKDF',false,['deriveKey']);return crypto.subtle.deriveKey({name:'HKDF',hash:'SHA-256',salt:iv,info},secret,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
export async function encryptMessage(own,peer,sender,recipient,text){if(!text.trim()||text.length>2000)throw Error('消息需为 1–2000 字');return encryptChatPayload(own,peer,sender,recipient,text);}
export async function encryptChatPayload(own,peer,sender,recipient,text){if(!text.trim()||encode.encode(text).length>11000)throw Error('Message payload is too large');const iv=crypto.getRandomValues(new Uint8Array(12)),info=context(sender,recipient,own.fingerprint,peer.fingerprint),key=await aes(own,peer,iv,info);const ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:info},key,encode.encode(text));return 'e2ee:v1:'+JSON.stringify({v:1,senderKey:own.fingerprint,recipientKey:peer.fingerprint,iv:b64(iv),ciphertext:b64(ciphertext)});}
export async function decryptMessage(own,peer,me,message){const e=JSON.parse(message.text.slice(8));const senderKey=message.sender===me?own.fingerprint:peer.fingerprint,recipientKey=message.recipient===me?own.fingerprint:peer.fingerprint;if(e.v!==1||e.senderKey!==senderKey||e.recipientKey!==recipientKey)throw Error('密钥不匹配');const iv=unb64(e.iv),info=context(message.sender,message.recipient,senderKey,recipientKey),key=await aes(own,peer,iv,info);return decode.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv,additionalData:info},key,unb64(e.ciphertext)));}
async function backupKey(password,salt){if(!password||password.length>128)throw Error('密码长度无效');const material=await crypto.subtle.importKey('raw',encode.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:600000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
export async function exportIdentity(id,password){const own=await local(id);if(!own)throw Error('本机没有可备份的密钥');const iv=crypto.getRandomValues(new Uint8Array(12)),salt=crypto.getRandomValues(new Uint8Array(16)),key=await backupKey(password,salt);const data={account:id,publicKey:own.publicKey,privateJwk:await crypto.subtle.exportKey('jwk',own.privateKey)};const ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:encode.encode(id)},key,encode.encode(JSON.stringify(data)));return JSON.stringify({version:1,account:id,iv:b64(iv),salt:b64(salt),ciphertext:b64(ciphertext)});}
export async function importIdentity(id,password,file,api,write){if(file.size>20000)throw Error('备份文件过大');try{const envelope=JSON.parse(await file.text());if(envelope.version!==1||envelope.account!==id)throw Error();const iv=unb64(envelope.iv),salt=unb64(envelope.salt);if(iv.length!==12||salt.length!==16)throw Error();const key=await backupKey(password,salt);const data=JSON.parse(decode.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv,additionalData:encode.encode(id)},key,unb64(envelope.ciphertext))));if(data.account!==id)throw Error();const privateKey=await crypto.subtle.importKey('jwk',data.privateJwk,{name:'ECDH',namedCurve:'P-256'},true,['deriveBits']);const publicKey=await crypto.subtle.importKey('spki',unb64(data.publicKey),{name:'ECDH',namedCurve:'P-256'},false,[]);const probe=await crypto.subtle.generateKey({name:'ECDH',namedCurve:'P-256'},false,['deriveBits']);const a=await crypto.subtle.deriveBits({name:'ECDH',public:probe.publicKey},privateKey,256),b=await crypto.subtle.deriveBits({name:'ECDH',public:publicKey},probe.privateKey,256);if(b64(a)!==b64(b))throw Error();const own={privateKey,publicKey:data.publicKey,fingerprint:hex(await crypto.subtle.digest('SHA-256',unb64(data.publicKey)))};const remote=await api('/keys/'+id);if(remote.ready&&remote.fingerprint!==own.fingerprint)throw Error();await write('/keys','PUT',{publicKey:own.publicKey});await local(id,own);starting.delete(id);return own;}catch{throw Error('无法导入：请检查账号、备份文件与口令');}}
export async function safetyCode(a,b){return hex(await crypto.subtle.digest('SHA-256',encode.encode([a.fingerprint,b.fingerprint].sort().join('|')))).match(/.{1,4}/g).join(' ');}

export async function verifyPeer(me,id,peer){const fingerprint=hex(await crypto.subtle.digest('SHA-256',unb64(peer.publicKey)));if(fingerprint!==peer.fingerprint)throw Error('对方公钥校验失败，已停止发送');const key='pin:'+me+':'+id;const pinned=await local(key);if(pinned&&pinned!==fingerprint)throw Error('对方密钥发生变化，已停止发送。请先与本人核对');if(!pinned)await local(key,fingerprint);return peer;}

export async function syncIdentityAfterLogin(password){
 const request=async(path,options={})=>{const r=await fetch('/api/campus-social'+path,options);if(!r.ok)throw Error('加密私信同步失败 / Unable to sync encrypted messages');return r.json()};
 const profile=await request('/me');const write=(path,method,body)=>request(path,{method,headers:{'Content-Type':'application/json','X-Workspace-Token':profile.token},body:JSON.stringify(body)});const id=profile.account.id;
 let own=await recoverIdentity(id,request);
 if(!own){const backup=await request('/keys/backup');if(backup.envelope){try{own=await importIdentity(id,password,new Blob([backup.envelope]),request,write)}catch(error){own=await local(id);if(!own)throw error;}}}
 starting.delete(id);own=await ensureIdentity(id,request,write);await escrow(own,write);
 const envelope=await exportIdentity(id,password);const backup=await request('/keys/backup');if(!backup.envelope)await write('/keys/backup','PUT',{envelope});
}

export async function forgetIdentity(id){starting.delete(id);const d=await db();try{await new Promise((resolve,reject)=>{const t=d.transaction('identities','readwrite'),s=t.objectStore('identities'),r=s.openCursor();r.onsuccess=()=>{const c=r.result;if(!c)return;if(c.key===id||String(c.key).startsWith('pin:'+id+':'))c.delete();c.continue()};t.oncomplete=resolve;t.onerror=reject})}finally{d.close()}}
