import {useRef,useState,useCallback,useEffect,useId} from 'react';
import './OptionWheel.css';
// Adapted from React Bits OptionWheel (REACT-BITS-LICENSE.md).
// Commit only after a snapped option settles, so dragging never floods the feed API.
export default function OptionWheel({items=[],defaultSelected=0,onChange,textColor='#938a9a',activeColor='#302438',side='left',fontSize=1.3,spacing=1.8,curve=1,tilt=9,blur=.5,fade=.28,minOpacity=.08,smoothing=100,inset=38,loop=false,draggable=true,className='',label='选择分类'}) {
 const clamp=v=>Math.max(0,Math.min(items.length-1,v));
 const initial=clamp(defaultSelected),root=useRef(),els=useRef([]),pos=useRef(initial),target=useRef(initial),raf=useRef(),last=useRef(0),config=useRef(),change=useRef(onChange),committed=useRef(initial),active=useRef(initial),timer=useRef(),drag=useRef(),moved=useRef(false),id=useId();
 const [selected,setSelected]=useState(initial),[dragging,setDragging]=useState(false),[reduced,setReduced]=useState(false);
 change.current=onChange;config.current={items,count:items.length,rowH:fontSize*spacing*16,curve,tilt,blur,fade,minOpacity,smoothing,side,loop,draggable,reduced};
 const frame=useCallback(now=>{const c=config.current;if(!c.count)return;const dt=Math.min((now-last.current)/1000,.05);last.current=now;let next=(c.reduced||drag.current)?target.current:pos.current+(target.current-pos.current)*(1-Math.exp(-dt/(Math.max(c.smoothing,1)/1000)));const settled=Math.abs(next-target.current)<.005;if(settled)next=target.current;pos.current=next;
  const angle=c.tilt*Math.PI/180,R=angle>.0005?c.rowH/angle:0,mirror=c.side==='right'?-1:1;
  els.current.forEach((el,i)=>{if(!el)return;let d=i-next;if(c.loop&&c.count>1){d=((d%c.count)+c.count)%c.count;if(d>c.count/2)d-=c.count;}const dist=Math.abs(d),a=Math.max(-Math.PI/2,Math.min(Math.PI/2,d*angle)),y=R?R*Math.sin(a):d*c.rowH,x=R?-mirror*R*(1-Math.cos(a))*c.curve:0,rot=R?mirror*a*180/Math.PI:0;el.style.transform=`translate(${x}px,calc(${y}px - 50%)) rotate(${rot}deg)`;el.style.opacity=String(Math.max(c.minOpacity,1-dist*c.fade));el.style.filter=c.reduced?'none':`blur(${dist*c.blur}px)`;el.style.setProperty('--ow-p',String(Math.max(0,1-Math.min(dist,1))));});
  const index=((Math.round(next)%c.count)+c.count)%c.count;if(active.current!==index){active.current=index;setSelected(index);}
  raf.current=settled?null:requestAnimationFrame(frame);
  if(settled&&Number.isInteger(target.current)&&!drag.current&&!timer.current&&committed.current!==index){committed.current=index;change.current?.(index,c.items[index]);}
 },[]);
 const start=useCallback(()=>{if(raf.current!=null)return;last.current=performance.now();raf.current=requestAnimationFrame(frame);},[frame]);
 const apply=useCallback((v,snap=true)=>{const c=config.current;if(!c.count)return;if(!c.loop)v=Math.max(0,Math.min(c.count-1,v));target.current=snap?Math.round(v):v;if(snap){const index=((Math.round(v)%c.count)+c.count)%c.count;if(committed.current!==index){committed.current=index;change.current?.(index,c.items[index]);}}start();},[start]);
 useEffect(()=>{const m=matchMedia('(prefers-reduced-motion: reduce)'),update=()=>setReduced(m.matches);update();m.addEventListener('change',update);return()=>m.removeEventListener('change',update);},[]);
 useEffect(()=>{start();},[items,fontSize,spacing,curve,tilt,blur,fade,minOpacity,side,loop,smoothing,reduced,start]);
 useEffect(()=>{const el=root.current;const wheel=e=>{e.preventDefault();const c=config.current,delta=e.deltaY*(e.deltaMode===1?24:e.deltaMode===2?el.clientHeight:1);clearTimeout(timer.current);timer.current=setTimeout(()=>{timer.current=null;apply(target.current);},140);apply(target.current+Math.max(-1,Math.min(1,delta/c.rowH)),false);};el.addEventListener('wheel',wheel,{passive:false});return()=>{el.removeEventListener('wheel',wheel);clearTimeout(timer.current);cancelAnimationFrame(raf.current);};},[apply]);
 const end=()=>{const d=drag.current;if(!d)return;drag.current=null;setDragging(false);if(root.current.hasPointerCapture?.(d.id))root.current.releasePointerCapture(d.id);if(moved.current)apply(target.current);};
 const select=i=>{if(moved.current)return;clearTimeout(timer.current);timer.current=null;let delta=i-((target.current%items.length)+items.length)%items.length;if(loop&&items.length>1){if(delta>items.length/2)delta-=items.length;else if(delta<-items.length/2)delta+=items.length;}apply(target.current+delta);};
 return <div ref={root} role="listbox" tabIndex={0} aria-label={label} aria-activedescendant={`${id}-${selected}`} className={`option-wheel ${dragging?'is-dragging':''} ${side==='right'?'option-wheel--right':''} ${className}`} style={{'--ow-text-color':textColor,'--ow-active-color':activeColor,'--ow-font-size':`${fontSize}rem`,'--ow-inset':`${inset}px`}} onPointerDown={e=>{if(!draggable||e.button!==0)return;clearTimeout(timer.current);timer.current=null;target.current=pos.current;drag.current={y:e.clientY,start:pos.current,id:e.pointerId};moved.current=false;setDragging(true);root.current.focus({preventScroll:true});}} onPointerMove={e=>{const d=drag.current;if(!d||d.id!==e.pointerId)return;const dy=e.clientY-d.y;if(!moved.current&&Math.abs(dy)>4){moved.current=true;root.current.setPointerCapture(d.id);}if(moved.current)apply(d.start-dy/config.current.rowH,false);}} onPointerUp={end} onPointerCancel={end} onLostPointerCapture={end} onKeyDown={e=>{const delta=['ArrowDown','ArrowRight'].includes(e.key)?1:['ArrowUp','ArrowLeft'].includes(e.key)?-1:0;if(!delta&&!['Home','End'].includes(e.key))return;e.preventDefault();moved.current=false;clearTimeout(timer.current);timer.current=null;apply(e.key==='Home'?0:e.key==='End'?items.length-1:Math.round(target.current)+delta);}}><div className="option-wheel__focus" aria-hidden="true"/>{items.map((text,i)=><div key={text} id={`${id}-${i}`} ref={el=>{els.current[i]=el;}} role="option" aria-selected={selected===i} className={'option-wheel__item '+(selected===i?'is-selected':'')} onClick={()=>select(i)}>{text}</div>)}</div>;
}
