import {MentionText} from './Mentions';
import React,{useState,useEffect,useRef} from 'react';
import {Heart,ChatCircle,Envelope,Eye,PushPin,Trash,DotsThree} from '@phosphor-icons/react';
import {motion,AnimatePresence,useIsPresent,useReducedMotion} from 'motion/react';
import {TeacherBadge} from './TeacherDay';
import Avatar from './Avatar';
import PostMedia from './PostMedia';
import {AnimatedNumber} from './MotionPrimitives';
import {tr,tx,en} from './language';
import {postName} from './person-names.mjs';
import './social.css';
import './ConversationRefinements.css';
import './InlineReply.css';
const personName=p=>postName(p,en),base='/api/campus-social',postUrl=id=>'/page/wall?post='+encodeURIComponent(id),stamp=s=>s?.slice(0,16).replace('T',' ')||'';
const roles={student:tr('学生'),teacher:tr('教师'),president:tr('社长'),admin:tx('管理员 · 学生','Administrator · Student')};
const kinds={recruit:tr('招募伙伴'),help:tr('互助求助'),team:tr('项目组队'),general:tr('校园分享'),other:tr('其他'),events:tr('活动公告')};
const personRole=p=>{if(p?.role==='president'){const club=en?p.clubNameEn||p.clubName:p.clubName;const role=p.position==='vice_president'?tx('副社长','Vice President'):tx('社长','President');return club?club+' · '+role:role;}return roles[p?.role]||''};
function Icon({name}){const Component={heart:Heart,chat:ChatCircle,mail:Envelope}[name]||ChatCircle;return <Component size={20} aria-hidden="true"/>}
function ErrorMessage({children}){return children?<p className="social-error" role="alert">{children}</p>:null}
async function api(path){const r=await fetch(base+path);const d=await r.json();if(!r.ok)throw Error(d.message||tr('操作未成功'));return d;}
function ReplyTransition({children,reduced}){
 const present=useIsPresent();
 return <motion.div className="reply-composer-transition" inert={!present} aria-hidden={present?undefined:true} initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}} transition={{duration:reduced?0:.22,ease:[.22,1,.36,1]}} style={{overflow:'hidden'}}>{children}</motion.div>;
}
export default function Post({post,profile,write,onRemove,onLike,onReply,onPin,profileFeed=false,detail=false}){
 const [replyTarget,setReplyTarget]=useState(null),[replyOpen,setReplyOpen]=useState(detail),[deleteReply,setDeleteReply]=useState(null);const replyInput=useRef(null),replyMounted=useRef(false),replyForm=useRef(null),autoScrollUntil=useRef(0);
 const reduced=useReducedMotion(),menuRef=useRef(null);const [menu,setMenu]=useState(false);
 useEffect(()=>{if(!menu)return;const close=e=>{if(!menuRef.current?.contains(e.target))setMenu(false)},key=e=>{if(e.key==='Escape'){setMenu(false);menuRef.current?.querySelector('button')?.focus()}};document.addEventListener('pointerdown',close);document.addEventListener('keydown',key);return()=>{document.removeEventListener('pointerdown',close);document.removeEventListener('keydown',key)}},[menu]);
 const [replies,setReplies]=useState(null),[replyDrafts,setReplyDrafts]=useState({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirm,setConfirm]=useState(false);const lock=useRef(false);const postElement=useRef(null),viewWrite=useRef(write);viewWrite.current=write;const [views,setViews]=useState(post.views||0);
 const draftKey=replyTarget?.id||'post',text=replyDrafts[draftKey]||'';const setText=value=>setReplyDrafts(d=>({...d,[draftKey]:value}));
 useEffect(()=>setViews(v=>Math.max(v,post.views||0)),[post.views]);
 useEffect(()=>{let timer,active=true,sent=false;const observer=new IntersectionObserver(entries=>{clearTimeout(timer);if(entries[0].isIntersecting&&!sent&&!document.hidden)timer=setTimeout(()=>{if(document.hidden)return;sent=true;viewWrite.current('/posts/views','POST',{ids:[post.id]}).then(d=>{if(active)setViews(d.views[post.id]);}).catch(()=>{sent=false;});},1000);},{threshold:0.25});const target=postElement.current?.querySelector('.social-post-body>header');const observe=()=>{clearTimeout(timer);observer.disconnect();if(target&&!document.hidden)observer.observe(target)};observe();document.addEventListener('visibilitychange',observe);return()=>{active=false;clearTimeout(timer);observer.disconnect();document.removeEventListener('visibilitychange',observe);};},[post.id]);
 const load=()=>api('/posts/'+post.id+'/replies').then(setReplies).catch(e=>setError(tr(e.message)));
 useEffect(()=>{if(detail)load();},[post.id,detail]);
 useEffect(()=>{if(!replyMounted.current){replyMounted.current=true;return}if(!replyOpen)return;autoScrollUntil.current=performance.now()+700;const frame=requestAnimationFrame(()=>{replyInput.current?.focus({preventScroll:true});if(detail&&replyTarget)replyInput.current?.scrollIntoView({block:'nearest',behavior:reduced?'instant':'smooth'})});return()=>cancelAnimationFrame(frame)},[replyOpen,replyTarget?.id]);
 useEffect(()=>{const input=replyInput.current;if(!input)return;const resize=()=>{input.style.height='24px';input.style.height=Math.min(120,Math.max(24,input.scrollHeight))+'px';input.style.overflowY=input.scrollHeight>120?'auto':'hidden'};resize();const observer=new ResizeObserver(resize);observer.observe(input.parentElement);return()=>observer.disconnect()},[text,replyOpen,detail,replyTarget?.id]);
 // Dismiss only comment replies; each target's draft remains in replyDrafts.
 useEffect(()=>{
  if(!replyOpen||!replyTarget)return;
  const inside=e=>replyForm.current?.contains(e.target);
  const close=()=>{if(lock.current)return;replyInput.current?.blur();setReplyOpen(false);setReplyTarget(null)};
  const pointer=e=>{const control=e.target.closest('.reply-thread-button,.post-reply-toggle');if(!inside(e)&&!(control&&postElement.current?.contains(control)))close()};
  const wheel=e=>{
   if(e.ctrlKey)return;
   const input=replyInput.current;
   if(inside(e)&&input?.contains(e.target)&&input.scrollHeight>input.clientHeight&&
    ((e.deltaY>0&&input.scrollTop+input.clientHeight<input.scrollHeight-1)||(e.deltaY<0&&input.scrollTop>0)))return;
   if(e.deltaX||e.deltaY)close();
  };
  const touch=e=>{if(!inside(e))close()};
  const scroll=e=>{if(e.target===document&&performance.now()>autoScrollUntil.current)close()};
  const key=e=>{if(e.key==='Escape'||(!inside(e)&&['PageDown','PageUp','Home','End','ArrowDown','ArrowUp',' '].includes(e.key)))close()};
  document.addEventListener('pointerdown',pointer);
  document.addEventListener('wheel',wheel,{passive:true});
  document.addEventListener('touchmove',touch,{passive:true});
  document.addEventListener('scroll',scroll,{passive:true});
  document.addEventListener('keydown',key);
  return()=>{document.removeEventListener('pointerdown',pointer);document.removeEventListener('wheel',wheel);document.removeEventListener('touchmove',touch);document.removeEventListener('scroll',scroll);document.removeEventListener('keydown',key)};
 },[replyOpen,replyTarget?.id]);
 const act=async fn=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await fn();}catch(e){setError(tr(e.message));}finally{lock.current=false;setBusy(false);}};
 const replyComposer=<form ref={node=>{if(node)replyForm.current=node}} className="post-reply-composer inline-reply" id={"reply-composer-"+post.id+"-"+draftKey} onSubmit={e=>{e.preventDefault();act(async()=>{await write('/posts/'+post.id+'/replies','POST',{text,parentReply:replyTarget?.id||''});setText('');setReplyOpen(false);setReplyTarget(null);if(detail)await load();await onReply(post.id);});}}>{replyTarget&&<div className="reply-target">{tx('回复 ','Replying to ')+personName(replyTarget.author)}<button type="button" onClick={()=>{setReplyOpen(false);setReplyTarget(null)}}>{tx('取消','Cancel')}</button></div>}<div className="inline-reply-row"><span className="inline-reply-avatar"><Avatar person={profile.account}/></span><div className="inline-reply-field"><textarea rows={1} ref={node=>{if(node)replyInput.current=node}} aria-label={tx('发表评论','Write a comment')} value={text} maxLength={500} onChange={e=>setText(e.target.value)} placeholder={tx('写下你的回复…','Write your reply…')}/><button className="inline-reply-send" type="submit" disabled={busy||!text.trim()}>{busy?tx('发送中…','Sending…'):tr('回复')}</button></div></div><ErrorMessage>{error}</ErrorMessage></form>;
 return <motion.article layout={reduced?false:'position'} initial={false} transition={{layout:{duration:.26,ease:[.22,1,.36,1]}}} ref={postElement} id={'post-'+post.id} className={'social-post'+(post.anonymous?' is-anonymous':'')+(!detail?' post-clickable':'')} onClick={!detail?e=>{if(!e.target.closest('a,button,input,textarea,video,select,.reply-composer-transition,.social-replies,.social-confirm,.post-reply-composer')&&!window.getSelection()?.toString())location.assign(postUrl(post.id));}:undefined}>
 {!post.anonymous&&<a className="post-avatar-link" href={'/page/user/home?account='+post.author.id} aria-label={personName(post.author)}><Avatar person={post.author}/></a>}
 <div className="social-post-body">{(profileFeed?post.profilePinned:post.wallPinned)&&<div className="post-pinned"><PushPin size={15} weight="fill"/>{tx('已置顶','Pinned')}</div>}<header><a href={!post.anonymous&&post.author.id?'/page/user/home?account='+post.author.id:undefined}><strong>{post.anonymous?tr('匿名同学'):personName(post.author)}</strong></a><span className="social-handle">{post.anonymous?tr('匿名发布'):personRole(post.author)}</span><TeacherBadge person={post.author}/><time>{stamp(post.createdAt)}</time>{(post.own||profile.admin)&&<div className="post-menu" ref={menuRef}><button className="social-icon-button" aria-label={tx('帖子操作：','Post actions: ')+post.text.slice(0,15)} aria-expanded={menu} onClick={()=>setMenu(v=>!v)}><DotsThree size={24}/></button>{menu&&<div className="post-menu-panel">{post.own&&!post.anonymous&&<button disabled={busy} onClick={()=>act(async()=>{await write('/posts/'+post.id+'/pin','PUT',{scope:'profile',pinned:!post.profilePinned});setMenu(false);await(onPin||onLike)?.(post.id)})}><PushPin size={18}/>{post.profilePinned?tx('取消主页置顶','Unpin from profile'):tx('置顶到个人主页','Pin to profile')}</button>}{profile.admin&&<button disabled={busy} onClick={()=>act(async()=>{await write('/posts/'+post.id+'/pin','PUT',{scope:'wall',pinned:!post.wallPinned});setMenu(false);await(onPin||onLike)?.(post.id)})}><PushPin size={18}/>{post.wallPinned?tx('取消校园墙置顶','Unpin from campus wall'):tx('置顶到校园墙','Pin to campus wall')}</button>}<button className="post-menu-delete" disabled={busy} onClick={()=>{setMenu(false);setConfirm(true)}}><Trash size={18}/>{tx('删除帖子','Delete post')}</button></div>}</div>}</header>
 {post.club>0&&<a className="wall-club-badge" href={'/page/wall?club='+post.club}>{post.clubName} ↗</a>}<span className="community-post-kind">{kinds[post.category]||tr('校园分享')}</span>
 <p className="social-post-text"><MentionText text={post.text} mentions={post.mentions}/></p>
 <PostMedia post={post}/>
 <div className="social-post-actions"><span className="post-view-count" title={tx('同一账号 24 小时内重复浏览不重复计数','Repeat views by the same account within 24 hours count once')}><Eye size={20} aria-hidden="true"/><span>{views.toLocaleString()} {tx('浏览','views')}</span></span><button aria-label={post.liked?tr('取消点赞'):tr('点赞')} aria-pressed={post.liked} disabled={busy} className={post.liked?'liked':''} onClick={()=>act(async()=>{await write('/posts/'+post.id+'/like','PUT',{liked:!post.liked});onLike(post.id);})}><Icon name="heart"/><span>{post.likes?<AnimatedNumber value={post.likes}/>:tr('点赞')}</span></button><button className="post-reply-toggle" aria-label={tx("回复帖子","Reply to post")} disabled={busy} aria-expanded={replyOpen&&!replyTarget} onClick={()=>{setReplyOpen(replyTarget?true:!replyOpen);setReplyTarget(null)}}><Icon name="chat"/><span>{post.replies||tr("回复")}</span></button>{!post.own&&!post.anonymous&&<a href={'/page/messages?with='+post.author.id} aria-label={tr('发送私信')}><Icon name="mail"/></a>}</div>
 {confirm&&<div className="social-confirm"><span>{tr('删除这条帖子及其回复？')}</span><button disabled={busy} onClick={()=>act(async()=>{await write('/posts/'+post.id,'DELETE');onRemove(post.id);})}>{tr('确认删除')}</button><button onClick={()=>setConfirm(false)}>{tr('取消')}</button></div>}{!replyOpen&&<ErrorMessage>{error}</ErrorMessage>}
 <AnimatePresence initial={false}>{replyOpen&&profile.canPost&&(!detail||!replyTarget)&&<ReplyTransition key={draftKey} reduced={reduced}>{replyComposer}</ReplyTransition>}</AnimatePresence>
 {!detail&&post.previewReply&&<div className="post-featured-comment"><a className="post-reply-preview" href={postUrl(post.id)}><Avatar person={post.previewReply.author}/><strong>{personName(post.previewReply.author)}</strong><span>{post.previewReply.text}</span>{post.previewReply.likes>0&&<small>♡ {post.previewReply.likes}</small>}</a><button className="reply-thread-button" aria-label={tx('回复这条评论','Reply to this comment')} disabled={busy} aria-expanded={replyOpen&&replyTarget?.id===post.previewReply.id} onClick={()=>{setReplyTarget(post.previewReply);setReplyOpen(true)}}><Icon name="chat"/>{post.previewReply.replyCount||''}</button></div>}
 {detail&&<section className="social-replies"><h2>{tx('评论','Comments')} ({post.replies})</h2>{!replies?<p>{tr('正在载入回复…')}</p>:replies.map(r=><div className="social-reply" data-reply-id={r.id} key={r.id}><a className="reply-avatar" href={r.author.id?"/page/user/home?account="+r.author.id:undefined} aria-label={r.author.role==='anonymous'?tr('匿名楼主'):personName(r.author)}><Avatar person={r.author}/></a><div className="reply-body"><header className="reply-heading"><strong>{r.author.role==='anonymous'?tr('匿名楼主'):personName(r.author)}</strong><small>{stamp(r.createdAt)}</small></header>{r.replyingTo&&<span className="reply-context">{tx('回复 ','Replying to ')+personName(r.replyingTo)}</span>}<p>{r.text}</p><div className="reply-actions"><button className={'reply-like'+(r.liked?' liked':'')} aria-label={tx('点赞评论','Like comment')} aria-pressed={r.liked} disabled={busy} onClick={()=>act(async()=>{await write('/posts/'+post.id+'/replies/'+r.id+'/like','PUT',{liked:!r.liked});await load();onReply(post.id);})}><Icon name="heart"/>{r.likes||0}</button><button className="reply-thread-button" aria-label={tx('回复这条评论','Reply to this comment')} disabled={busy} aria-expanded={replyOpen&&replyTarget?.id===r.id} aria-controls={replyOpen&&replyTarget?.id===r.id?'reply-composer-'+post.id+'-'+r.id:undefined} onClick={()=>{setReplyTarget(r);setReplyOpen(true)}}><Icon name="chat"/>{r.replyCount||''}</button>{(r.own||profile.admin)&&<button className="reply-delete" aria-label={tx('删除评论','Delete comment')} disabled={busy} onClick={()=>setDeleteReply(r.id)}><Trash size={17}/>{tx('删除','Delete')}</button>}</div>{deleteReply===r.id&&<div className="social-confirm"><span>{tx('删除这条评论？','Delete this comment?')}</span><button disabled={busy} onClick={()=>act(async()=>{await write('/posts/'+post.id+'/replies/'+r.id,'DELETE');setDeleteReply(null);await load();await onReply(post.id);})}>{tx('确认删除','Confirm delete')}</button><button onClick={()=>setDeleteReply(null)}>{tx('取消','Cancel')}</button></div>}<AnimatePresence initial={false}>{replyOpen&&profile.canPost&&replyTarget?.id===r.id&&<ReplyTransition key={r.id} reduced={reduced}>{replyComposer}</ReplyTransition>}</AnimatePresence></div></div>)}{replies?.length===0&&<p>{tr('还没有回复，来聊聊吧。')}</p>}</section>}

 </div></motion.article>;
}
