package com.qpwflshclub.formal_club.social;
import com.qpwflshclub.formal_club.pojo.User.User;import com.qpwflshclub.formal_club.repository.User.*;import com.qpwflshclub.formal_club.repository.Club.ClubRepository;import com.qpwflshclub.formal_club.service.User.IUserService;import com.qpwflshclub.formal_club.workspace.WorkspaceAccess;
import org.junit.jupiter.api.*;import org.junit.jupiter.api.io.TempDir;import org.springframework.mock.web.*;import java.nio.file.Path;import java.io.*;import javax.imageio.ImageIO;import java.awt.image.BufferedImage;
import static org.assertj.core.api.Assertions.*;import static org.mockito.Mockito.*;
class AvatarTest {
 @TempDir Path dir;AvatarStore store;AvatarController controller;SchoolAccounts accounts;WorkspaceAccess access;MockHttpServletRequest request;String key;User user;
 @BeforeEach void setup(){store=new AvatarStore(dir.toString());var service=mock(IUserService.class);user=new User();user.setEmail("avatar@example.com");user.setUsername("Student");key=SchoolAccounts.key(user.getEmail());when(service.findByEmail(user.getEmail())).thenReturn(user);accounts=new SchoolAccounts(service,mock(UserRepository.class),mock(ClubPresidentRepository.class),mock(TeacherRepository.class),mock(AdminRepository.class));org.springframework.test.util.ReflectionTestUtils.setField(accounts,"avatars",store);access=new WorkspaceAccess(service,mock(ClubRepository.class));controller=new AvatarController(store,accounts,access);request=new MockHttpServletRequest();request.getSession().setAttribute("authenticatedEmail",user.getEmail());request.addHeader("X-Workspace-Token",access.token(request));}
 MockMultipartFile png()throws Exception{var image=new BufferedImage(40,20,BufferedImage.TYPE_INT_RGB);var out=new ByteArrayOutputStream();ImageIO.write(image,"png",out);return new MockMultipartFile("file","../../avatar.png","image/png",out.toByteArray());}
 @Test void imagesAreReencodedAndPersistAsCompressedSquareWithoutUsingOriginalPaths()throws Exception{controller.upload(png(),request);BufferedImage result=ImageIO.read(new ByteArrayInputStream(new AvatarStore(dir.toString()).read(key)));assertThat(result.getWidth()).isEqualTo(20);assertThat(result.getHeight()).isEqualTo(20);assertThat(accounts.view(user).avatarUrl()).startsWith("/api/campus-social/avatars/"+key);assertThat(controller.get(key,request).getHeaders().getFirst("Cache-Control")).contains("private");controller.remove(request);assertThat(accounts.view(user).avatarUrl()).isEmpty();assertThatThrownBy(()->store.read(key)).hasMessageContaining("404");}
 @Test void fakeImagesOversizedFilesAndPathTraversalAreRejected()throws Exception{assertThatThrownBy(()->store.save(key,new MockMultipartFile("file","x.png","image/png","<svg><script/></svg>".getBytes()))).hasMessageContaining("400");assertThatThrownBy(()->store.save(key,new MockMultipartFile("file","x.png","image/png",new byte[5*1024*1024+1]))).hasMessageContaining("5 MB");assertThatThrownBy(()->store.read("../../secret")).hasMessageContaining("404");var out=new ByteArrayOutputStream();ImageIO.write(new BufferedImage(2,2,BufferedImage.TYPE_INT_RGB),"gif",out);assertThatThrownBy(()->store.save(key,new MockMultipartFile("file","fake.png","image/png",out.toByteArray()))).hasMessageContaining("仅支持");}
 @Test void uploadRequiresOwnSessionAndMutationTokenWhileAnonymousViewsHaveNoAvatar()throws Exception{assertThatThrownBy(()->controller.upload(png(),new MockHttpServletRequest())).hasMessageContaining("401");assertThatThrownBy(()->controller.get(key,new MockHttpServletRequest())).hasMessageContaining("401");request.removeHeader("X-Workspace-Token");assertThatThrownBy(()->controller.upload(png(),request)).hasMessageContaining("403");assertThat(new SchoolAccounts.Account("","匿名同学","","anonymous").avatarUrl()).isEmpty();}
}
