package com.qpwflshclub.formal_club.social;
import com.qpwflshclub.formal_club.pojo.User.*;
import com.qpwflshclub.formal_club.pojo.Club.Club;
import com.qpwflshclub.formal_club.repository.User.*;
import com.qpwflshclub.formal_club.repository.Club.ClubRepository;
import com.qpwflshclub.formal_club.workspace.*;
import com.qpwflshclub.formal_club.service.User.IUserService;
import org.junit.jupiter.api.Test;
import org.springframework.mock.web.MockHttpServletRequest;
import java.util.*;
import static org.mockito.Mockito.*;
import static org.assertj.core.api.Assertions.*;
class CommunityMembershipTest {
 final SchoolAccounts accounts=mock(SchoolAccounts.class);final ClubRepository clubs=mock(ClubRepository.class);final UserRepository students=mock(UserRepository.class);final TeacherRepository teachers=mock(TeacherRepository.class);final ClubPresidentRepository presidents=mock(ClubPresidentRepository.class);final AdminRepository admins=mock(AdminRepository.class);final WorkspaceAccess access=new WorkspaceAccess(mock(IUserService.class),clubs);
 final CommunityController controller=new CommunityController(accounts,access,mock(MessageKeys.class),mock(WorkspaceStore.class),clubs,students,teachers,presidents,admins);
 Club club(int id){var c=new Club();c.setId(id);return c;}
 MockHttpServletRequest request(UserBase u){u.setEmail("member@example.com");when(accounts.current(any())).thenReturn(u);var r=new MockHttpServletRequest();r.addHeader("X-Workspace-Token",access.token(r));return r;}
 @Test void leaderLeavingAlsoRemovesStudentMembershipAndManagementRights() throws Exception{var c=club(200);c.setPresident("Leader");var other=club(201);var p=new ClubPresident();p.setMainClub(c);p.setClubs(List.of(other));var u=new User();u.setClubs(List.of(c,other));var r=request(p);when(presidents.findByEmail(p.getEmail())).thenReturn(p);when(students.findByEmail(p.getEmail())).thenReturn(u);when(clubs.findById(200)).thenReturn(Optional.of(c));controller.leave(200,r);assertThat(p.getMainClub()).isNull();assertThat(u.getClubs()).containsExactly(other);assertThat(p.getClubs()).containsExactly(other);assertThat(c.getPresident()).isEmpty();assertThat(access.clubs(p)).isEmpty();assertThatThrownBy(()->access.require(p,200)).hasMessageContaining("403");}
 @Test void teacherLeavingPreservesOtherAdvisers() throws Exception{var c=club(200);var t=new Teacher();t.setClubs(List.of(c));var remaining=new Teacher();remaining.setUsername("李老师");remaining.setUsernameEn("Ms Li");remaining.setClubs(List.of(c));var r=request(t);when(teachers.findByEmail(t.getEmail())).thenReturn(t);when(teachers.findAll()).thenReturn(List.of(t,remaining));when(clubs.findById(200)).thenReturn(Optional.of(c));controller.leave(200,r);assertThat(t.getClubs()).isEmpty();assertThat(c.getTeacher()).isEqualTo("李老师");assertThat(c.getTeacherEn()).isEqualTo("Ms Li");}
 @Test void cannotLeaveAnUnrelatedClubOrWithoutCsrf() throws Exception{var u=new User();u.setClubs(List.of(club(1)));var r=request(u);when(students.findByEmail(u.getEmail())).thenReturn(u);when(clubs.findById(2)).thenReturn(Optional.of(club(2)));assertThatThrownBy(()->controller.leave(2,r)).hasMessageContaining("409");verify(students,never()).save(any());r.removeHeader("X-Workspace-Token");assertThatThrownBy(()->controller.leave(1,r)).hasMessageContaining("403");}
 @Test void contactSelectsPresidentsClubInsteadOfNameOrVice() throws Exception{var r=request(new User());var c=club(200);var vice=new ClubPresident();vice.setMainClub(c);vice.setVicePresident(true);var p=new ClubPresident();p.setUsername("真实姓名");p.setMainClub(c);var unrelated=new ClubPresident();unrelated.setMainClub(club(201));when(presidents.findAll()).thenReturn(List.of(vice,unrelated,p));when(clubs.existsById(200)).thenReturn(true);var a=new SchoolAccounts.Account("id","社长","President","president");when(accounts.view(p)).thenReturn(a);assertThat(controller.contact(200,r)).isEqualTo(a);assertThatThrownBy(()->controller.contact(999,r)).hasMessageContaining("404");}
 @Test void ordinaryStudentCanLeaveOneClubAndKeepOtherMemberships() throws Exception{var one=club(1);var two=club(2);var u=new User();u.setClubs(new ArrayList<>(List.of(one,two)));var r=request(u);when(students.findByEmail(u.getEmail())).thenReturn(u);when(clubs.findById(1)).thenReturn(Optional.of(one));controller.leave(1,r);assertThat(u.getClubs()).containsExactly(two);verify(students).save(u);verify(presidents,never()).delete(any());}
 @Test void resignRequiresExplicitConfirmationAndPreservesMembership() throws Exception{var c=club(1);var p=new ClubPresident();p.setMainClub(c);p.setClubs(new ArrayList<>());p.setUsername("Leader");p.setUsernameEn("Leader");p.setPassword("encoded");var r=request(p);when(presidents.findAll()).thenReturn(List.of(p));assertThatThrownBy(()->controller.resign(new CommunityController.ResignInput("no"),r)).hasMessageContaining("400");controller.resign(new CommunityController.ResignInput("RESIGN"),r);var captured=org.mockito.ArgumentCaptor.forClass(User.class);verify(students).save(captured.capture());assertThat(captured.getValue().getClubs()).containsExactly(c);assertThat(captured.getValue().getPassword()).isEqualTo("encoded");verify(presidents).delete(p);}
 @Test void resigningSecondaryOfficeKeepsPrimaryAndOtherOffices(@org.junit.jupiter.api.io.TempDir java.nio.file.Path dir)throws Exception{
  var main=club(28);var code=club(1);var third=club(3);var p=new ClubPresident();p.setMainClub(main);p.setUsername("李毅睿");p.setUsernameEn("Jason");var r=request(p);var assignments=new OfficerAssignments(new com.fasterxml.jackson.databind.ObjectMapper(),dir.toString());var id=SchoolAccounts.key(p.getEmail());assignments.assign(id,1,"vice_president");assignments.assign(id,3,"president");org.springframework.test.util.ReflectionTestUtils.setField(controller,"officers",assignments);
  when(clubs.findById(1)).thenReturn(Optional.of(code));when(clubs.findById(3)).thenReturn(Optional.of(third));when(clubs.existsById(1)).thenReturn(true);when(presidents.findAll()).thenReturn(List.of(p));
  assertThatThrownBy(()->controller.resign(new CommunityController.ResignInput("RESIGN",99),r)).hasMessageContaining("403");
  controller.resign(new CommunityController.ResignInput("RESIGN",1),r);assertThat(p.getMainClub()).isSameAs(main);assertThat(p.isVicePresident()).isFalse();assertThat(p.getClubs()).contains(code);assertThat(assignments.forAccount(id)).extracting(OfficerAssignments.Office::club).containsExactly(3);verify(presidents,never()).delete(any());
 }
 @Test void presidentCanRemoveOnlyOwnViceAndPreservesOtherOffices(@org.junit.jupiter.api.io.TempDir java.nio.file.Path dir)throws Exception{
 var code=club(1);var robot=club(28);var actor=new ClubPresident();actor.setMainClub(code);var r=request(actor);var target=new ClubPresident();target.setEmail("vice@example.com");target.setMainClub(robot);target.setClubs(new ArrayList<>());var id=SchoolAccounts.key(target.getEmail());var assignments=new OfficerAssignments(new com.fasterxml.jackson.databind.ObjectMapper(),dir.toString());assignments.assign(id,1,"vice_president");org.springframework.test.util.ReflectionTestUtils.setField(controller,"officers",assignments);when(accounts.find(id)).thenReturn(target);when(clubs.findById(1)).thenReturn(Optional.of(code));when(clubs.findById(28)).thenReturn(Optional.of(robot));when(clubs.existsById(1)).thenReturn(true);when(presidents.findAll()).thenReturn(List.of());
 actor.setVicePresident(true);assertThatThrownBy(()->controller.removeVice(1,id,r)).hasMessageContaining("403");actor.setVicePresident(false);assertThatThrownBy(()->controller.removeVice(28,id,r)).hasMessageContaining("403");controller.removeVice(1,id,r);assertThat(target.getMainClub()).isSameAs(robot);assertThat(target.getClubs()).contains(code);assertThat(assignments.forAccount(id)).isEmpty();verify(presidents,never()).delete(any());
 }
}
