package com.qpwflshclub.formal_club.social;
import com.fasterxml.jackson.databind.ObjectMapper;import com.qpwflshclub.formal_club.config.*;import com.qpwflshclub.formal_club.repository.User.*;import com.qpwflshclub.formal_club.pojo.User.*;import com.qpwflshclub.formal_club.service.User.IUserService;import com.qpwflshclub.formal_club.service.Suggestion.MailService;import org.junit.jupiter.api.*;import org.junit.jupiter.api.io.TempDir;import org.springframework.mock.web.*;import org.springframework.test.util.ReflectionTestUtils;import java.nio.file.Path;import java.util.*;import java.util.concurrent.*;import static org.assertj.core.api.Assertions.*;import static org.mockito.Mockito.*;
class PasswordRecoveryTest {
 @TempDir Path dir;PasswordRecoveryController c;IUserService users;UserRepository students;AdminRepository admins;User user;Admin admin;MailService mail;LoginEmails emails;SessionRevocations sessions;MessageKeyVault vault;BlockingQueue<String> codes;
 @BeforeEach void setup()throws Exception{users=mock(IUserService.class);students=mock(UserRepository.class);admins=mock(AdminRepository.class);mail=mock(MailService.class);vault=mock(MessageKeyVault.class);user=new User();user.setEmail("old@example.com");user.setPassword(PasswordCodec.encode("OriginalPassword123!"));admin=new Admin();admin.setEmail(user.getEmail());admin.setPassword(user.getPassword());when(users.findByEmail(user.getEmail())).thenReturn(user);when(students.findByEmail(user.getEmail())).thenReturn(user);when(admins.findByAdminEmail(user.getEmail())).thenReturn(admin);emails=new LoginEmails(dir.resolve("emails.json").toString(),users);emails.change(user.getEmail(),"new@example.com");sessions=new SessionRevocations(new ObjectMapper(),dir.resolve("sessions.json").toString());c=new PasswordRecoveryController(emails,users,students,mock(TeacherRepository.class),mock(ClubPresidentRepository.class),admins,mail,sessions,vault);ReflectionTestUtils.setField(c,"host","localhost");ReflectionTestUtils.setField(c,"username","test");ReflectionTestUtils.setField(c,"password","");codes=new LinkedBlockingQueue<>();doAnswer(inv->{codes.add(inv.getArgument(5));return null;}).when(mail).sendRecoveryCode(anyString(),anyInt(),anyString(),anyString(),anyString(),anyString(),anyBoolean());}
 MockHttpServletRequest request(){var r=new MockHttpServletRequest();r.setRemoteAddr("127.0.0.1");return r;}
 String send(MockHttpServletRequest r)throws Exception{c.code(new PasswordRecoveryController.EmailInput("new@example.com"),r);String code=codes.poll(5,TimeUnit.SECONDS);assertThat(code).matches("[0-9]{6}");return code;}
 @Test void resetRequiresVerificationUpdatesAllRolesAndRevokesSessions()throws Exception{var r=request();long before=System.currentTimeMillis()-1000;String code=send(r);assertThatThrownBy(()->c.complete(new PasswordRecoveryController.PasswordInput("ReplacementPassword123!",null),r)).hasMessageContaining("403");assertThatThrownBy(()->c.verify(new PasswordRecoveryController.CodeInput("new@example.com",code),request())).hasMessageContaining("400");c.verify(new PasswordRecoveryController.CodeInput("new@example.com",code),r);c.complete(new PasswordRecoveryController.PasswordInput("ReplacementPassword123!",null),r);assertThat(PasswordCodec.matches(user.getPassword(),"ReplacementPassword123!")).isTrue();assertThat(PasswordCodec.matches(user.getPassword(),"OriginalPassword123!")).isFalse();assertThat(admin.getPassword()).isEqualTo(user.getPassword());verify(students).save(user);verify(admins).save(admin);assertThat(sessions.revoked(user.getEmail(),before)).isTrue();assertThat(new SessionRevocations(new ObjectMapper(),dir.resolve("sessions.json").toString()).revoked(user.getEmail(),before)).isTrue();assertThatThrownBy(()->c.complete(new PasswordRecoveryController.PasswordInput("ReplacementPassword123!",null),r)).hasMessageContaining("400");verify(vault,never()).replace(any(),any());}
 @Test void wrongCodesLockChallengeAndSendingIsThrottled()throws Exception{var r=request();String code=send(r);String wrong=code.equals("000000")?"111111":"000000";for(int i=0;i<5;i++)assertThatThrownBy(()->c.verify(new PasswordRecoveryController.CodeInput("new@example.com",wrong),r)).hasMessageContaining("400");assertThatThrownBy(()->c.verify(new PasswordRecoveryController.CodeInput("new@example.com",code),r)).hasMessageContaining("400");assertThatThrownBy(()->c.code(new PasswordRecoveryController.EmailInput("new@example.com"),request())).hasMessageContaining("429");}
 @Test void unknownAndOldAliasReturnSameGenericReplyWithoutMail()throws Exception{var r=request();assertThat(c.code(new PasswordRecoveryController.EmailInput("missing@example.com"),r)).isEqualTo(Map.of("code",200,"retryAfter",60,"message","OK"));c.code(new PasswordRecoveryController.EmailInput("old@example.com"),request());assertThat(codes.poll(100,TimeUnit.MILLISECONDS)).isNull();verify(mail,never()).sendRecoveryCode(any(),anyInt(),any(),any(),any(),any(),anyBoolean());assertThatThrownBy(()->c.verify(new PasswordRecoveryController.CodeInput("new@example.com","123456"),r)).hasMessageContaining("400");}
 @Test void expiryOriginAndChangedPasswordInvalidateProof()throws Exception{var r=request();String code=send(r);var old=(PasswordRecoveryController.Challenge)r.getSession().getAttribute("passwordRecovery");r.getSession().setAttribute("passwordRecovery",new PasswordRecoveryController.Challenge(old.login(),old.canonical(),old.version(),old.digest(),1,0,false));assertThatThrownBy(()->c.verify(new PasswordRecoveryController.CodeInput("new@example.com",code),r)).hasMessageContaining("400");r.getSession().setAttribute("passwordRecovery",old);user.setPassword("changed");assertThatThrownBy(()->c.verify(new PasswordRecoveryController.CodeInput("new@example.com",code),r)).hasMessageContaining("400");var cross=request();cross.addHeader("Origin","https://other.example");assertThatThrownBy(()->c.code(new PasswordRecoveryController.EmailInput("new@example.com"),cross)).hasMessageContaining("403");}
}
