package com.qpwflshclub.formal_club.social;
import com.fasterxml.jackson.databind.ObjectMapper;import com.qpwflshclub.formal_club.workspace.*;import com.qpwflshclub.formal_club.pojo.User.User;import org.junit.jupiter.api.*;import org.junit.jupiter.api.io.TempDir;import org.springframework.mock.web.MockHttpServletRequest;import java.nio.file.Path;import java.util.*;import static org.assertj.core.api.Assertions.*;import static org.mockito.Mockito.*;
class SocialNotificationsTest {
 @TempDir Path dir;ObjectMapper json=new ObjectMapper();
 @Test void recallOnlyOwnMessageErasesPayloadAndSurvivesReload()throws Exception{var s=new SocialStore(json,dir.toString());var m=s.message("a","b","ciphertext");assertThatThrownBy(()->s.recall(m.id(),"b","a")).hasMessageContaining("403");assertThatThrownBy(()->s.recall(m.id(),"a","c")).hasMessageContaining("403");s.recall(m.id(),"a","b");s.markRead("b","a");var stored=new SocialStore(json,dir.toString()).snapshot().messages().getFirst();assertThat(stored.text()).isEmpty();assertThat(stored.recalled()).isTrue();assertThat(stored.read()).isTrue();assertThatThrownBy(()->s.encryptHistory(m.id(),"a","b","e2ee:v1:new")).hasMessageContaining("409");}
 @Test void oldMessageJsonLoadsWithoutNewFields()throws Exception{var m=json.readValue("{\"id\":\"1\",\"sender\":\"a\",\"recipient\":\"b\",\"text\":\"hi\",\"createdAt\":\"now\",\"read\":false}",SocialStore.Message.class);assertThat(m.recalled()).isFalse();}
 @Test void mentionsUnreadIsolationAnonymityDeletionAndRecall()throws Exception{var a=mock(SchoolAccounts.class);var access=mock(WorkspaceAccess.class);var store=new SocialStore(json,dir.toString());var notifications=new SocialNotifications(json,dir.toString());var c=new NotificationController(a,access,store,notifications);var user=new User();user.setEmail("bob@example.com");String me=SchoolAccounts.key(user.getEmail());var r=new MockHttpServletRequest();when(a.current(r)).thenReturn(user);when(a.directory()).thenReturn(Map.of());when(access.token(r)).thenReturn("token");var p=store.post("alice","@Bob Hi","general",true);notifications.attach(p.id(),List.of(new SocialNotifications.Mention(0,4,me)));var m=store.message("alice",me,"secret");var result=json.valueToTree(c.get(r));assertThat(result.get("unread").asInt()).isEqualTo(2);assertThat(result.toString()).doesNotContain("secret");var mention=result.get("items").findValuesAsText("type");assertThat(mention).contains("mention","message");assertThat(result.get("items").findValues("actor")).allMatch(v->v.isNull());c.read(new NotificationController.ReadInput("mention:"+p.id(),false),r);assertThat(json.valueToTree(c.get(r)).get("unread").asInt()).isEqualTo(1);assertThat(new SocialNotifications(json,dir.toString()).read(me,"mention:"+p.id())).isTrue();assertThat(notifications.read("outsider","mention:"+p.id())).isFalse();store.recall(m.id(),"alice",me);assertThat(json.valueToTree(c.get(r)).get("unread").asInt()).isZero();store.delete(p.id(),"alice",false);assertThat(json.valueToTree(c.get(r)).get("items")).isEmpty();assertThatThrownBy(()->c.read(new NotificationController.ReadInput("message:other",false),r)).hasMessageContaining("404");}
 @Test void mentionOffsetsAreValidatedAndTrimmed()throws Exception{var a=mock(SchoolAccounts.class);var n=new SocialNotifications(json,dir.toString());assertThat(n.validate(null,List.of(),a)).isEmpty();assertThat(n.validate("　@Bob",List.of(new SocialNotifications.Mention(1,5,"b")),a).getFirst().start()).isEqualTo(1);var valid=n.validate("  @Bob test",List.of(new SocialNotifications.Mention(2,6,"b")),a);assertThat(valid.getFirst().start()).isZero();assertThat(valid.getFirst().end()).isEqualTo(4);assertThatThrownBy(()->n.validate("Hi",List.of(new SocialNotifications.Mention(0,100,"b")),a)).hasMessageContaining("400");assertThatThrownBy(()->n.validate("@Bob",List.of(new SocialNotifications.Mention(0,4,"b"),new SocialNotifications.Mention(0,4,"c")),a)).hasMessageContaining("400");}
}
