package com.qpwflshclub.formal_club.social;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;import org.junit.jupiter.api.io.TempDir;
import org.springframework.mock.web.MockMultipartFile;
import java.nio.file.*;import java.util.*;import java.awt.image.BufferedImage;import java.io.ByteArrayOutputStream;import javax.imageio.ImageIO;
import static org.assertj.core.api.Assertions.*;
class SocialUpgradeTest {
 @TempDir Path dir;
 @Test void blockIsBilateralPinIsPrivateAndPersists()throws Exception{var p=new ChatPreferences(new ObjectMapper(),dir.toString());p.update("a","b",new ChatPreferences.Preference(true,true));assertThat(p.allowed("a","b")).isFalse();assertThat(p.allowed("b","a")).isFalse();assertThat(p.get("b","a").pinned()).isFalse();assertThatThrownBy(()->p.requireAllowed("b","a")).hasMessageContaining("403");var reopened=new ChatPreferences(new ObjectMapper(),dir.toString());assertThat(reopened.get("a","b").pinned()).isTrue();p.update("a","b",new ChatPreferences.Preference(true,false));assertThat(p.allowed("b","a")).isTrue();}
 @Test void appearanceCannotClaimGiftsOrInjectUrlsAndCanUnequip()throws Exception{var p=new ProfileAppearance(new ObjectMapper(),dir.toString());var claim=new ProfileAppearance.Settings("teacher-day-2026",true,1,0,0,List.of(),"https://evil","https://evil");assertThatThrownBy(()->p.update("student",claim,false,List.of())).hasMessageContaining("400");var saved=p.update("teacher",new ProfileAppearance.Settings("none",false,1.2,.1,-.2,List.of("known","fake"),"evil","evil"),true,List.of("known"));assertThat(saved.tags()).containsExactly("known");assertThat(saved.customFrame()).isEmpty();assertThat(saved.banner()).isEmpty();assertThat(new ProfileAppearance(new ObjectMapper(),dir.toString()).publicView("teacher",true)).containsEntry("frame","none");assertThatThrownBy(()->p.update("teacher",new ProfileAppearance.Settings("auto",true,Double.NaN,0,0,null,"",""),true,List.of())).hasMessageContaining("400");}
 @Test void uploadedTransparentFrameIsResizedAndOwnerScoped()throws Exception{var p=new ProfileAppearance(new ObjectMapper(),dir.toString());var out=new ByteArrayOutputStream();ImageIO.write(new BufferedImage(1000,1000,BufferedImage.TYPE_INT_ARGB),"png",out);var saved=p.upload("a","frame",new MockMultipartFile("file","frame.png","image/png",out.toByteArray()));assertThat(saved.frame()).isEqualTo("custom");assertThat(p.get("b").customFrame()).isEmpty();assertThat(ImageIO.read(p.file(Path.of(saved.customFrame()).getFileName().toString()).toFile()).getWidth()).isEqualTo(640);assertThatThrownBy(()->p.file("../settings.json")).hasMessageContaining("404");}
 @Test void legacyMediaUsesSignatureNotFilename()throws Exception{var files=new WallFiles(dir.toString());var id=UUID.randomUUID().toString();Files.createDirectories(files.file(id).getParent());Files.write(files.file(id),new byte[]{(byte)255,(byte)216,(byte)255,0});assertThat(files.resolved(new SocialStore.Attachment(id,"old.bin","application/octet-stream",4)).type()).isEqualTo("image/jpeg");Files.writeString(files.file(id),"<script>alert(1)</script>");assertThat(files.resolved(new SocialStore.Attachment(id,"fake.png","application/octet-stream",25)).type()).isEqualTo("application/octet-stream");}
 @Test void rgbAndIndexedPngFramesUploadWithoutLosingAlpha()throws Exception{var p=new ProfileAppearance(new ObjectMapper(),dir.toString());for(int type:new int[]{BufferedImage.TYPE_INT_RGB,BufferedImage.TYPE_BYTE_INDEXED,BufferedImage.TYPE_INT_ARGB}){var source=new BufferedImage(32,32,type);source.setRGB(0,0,0x00773322);var out=new ByteArrayOutputStream();ImageIO.write(source,"png",out);var saved=p.upload("a","frame",new MockMultipartFile("file","frame.png","image/png",out.toByteArray()));var image=ImageIO.read(p.file(Path.of(saved.customFrame()).getFileName().toString()).toFile());assertThat(image.getWidth()).isEqualTo(32);if(type==BufferedImage.TYPE_INT_ARGB)assertThat(image.getRGB(0,0)>>>24).isZero();}assertThatThrownBy(()->p.upload("a","frame",new MockMultipartFile("file","fake.png","image/png","<svg/>".getBytes()))).hasMessageContaining("400");}
 @Test void removingOwnFrameUnequipsItAndPreservesOtherUsersAndGifts()throws Exception{
 var p=new ProfileAppearance(new ObjectMapper(),dir.toString());var out=new ByteArrayOutputStream();ImageIO.write(new BufferedImage(32,32,BufferedImage.TYPE_INT_ARGB),"png",out);var file=new MockMultipartFile("file","frame.png","image/png",out.toByteArray());var a=p.upload("a","frame",file);var b=p.upload("b","frame",file);String aName=Path.of(a.customFrame()).getFileName().toString();var deleted=p.removeFrame("a");assertThat(deleted.frame()).isEqualTo("none");assertThat(deleted.customFrame()).isEmpty();assertThatThrownBy(()->p.file(aName)).hasMessageContaining("404");assertThatThrownBy(()->p.file(aName.replace(".png","-small.png"))).hasMessageContaining("404");assertThat(p.file(Path.of(b.customFrame()).getFileName().toString())).exists();assertThat(p.get("b").customFrame()).isEqualTo(b.customFrame());assertThat(p.removeFrame("a")).isEqualTo(deleted);
 p.update("b",new ProfileAppearance.Settings("teacher-day-2026",true,1,0,0,List.of("teacher"),"",""),true,List.of("teacher"));p.removeFrame("b");assertThat(p.get("b").frame()).isEqualTo("teacher-day-2026");assertThat(p.get("b").holidayBadge()).isTrue();assertThat(p.get("b").tags()).containsExactly("teacher");assertThat(new ProfileAppearance(new ObjectMapper(),dir.toString()).get("a").customFrame()).isEmpty();
 }

 @Test void frameLibraryKeepsMultipleUploadsAndDeletesOnlyOwnedSelectedId()throws Exception{
 var p=new ProfileAppearance(new ObjectMapper(),dir.toString());var out=new ByteArrayOutputStream();ImageIO.write(new BufferedImage(32,32,BufferedImage.TYPE_INT_ARGB),"png",out);var file=new MockMultipartFile("file","frame.png","image/png",out.toByteArray());
 var first=p.upload("owner","frame",file);var second=p.upload("owner","frame",file);var stranger=p.upload("stranger","frame",file);assertThat(second.frames()).hasSize(2);
 var selected=p.update("owner",new ProfileAppearance.Settings("custom",true,1.2,.1,-.1,List.of(),first.customFrame(),"",List.of(),1.3,.2,-.2),false,List.of());assertThat(selected.customFrame()).isEqualTo(first.customFrame());assertThat(selected.frames().get(0).scale()).isEqualTo(1.2);assertThat(p.publicView("owner",false)).containsEntry("avatarScale",1.3).containsEntry("avatarX",.2);
 assertThatThrownBy(()->p.removeFrame("owner",stranger.frames().get(0).id())).hasMessageContaining("404");assertThat(p.get("stranger").frames()).hasSize(1);
 var removed=p.removeFrame("owner",second.frames().get(1).id());assertThat(removed.frames()).hasSize(1);assertThat(removed.frame()).isEqualTo("custom");assertThat(removed.customFrame()).isEqualTo(first.customFrame());assertThat(removed.avatarScale()).isEqualTo(1.3);
 var reloaded=new ProfileAppearance(new ObjectMapper(),dir.toString());assertThat(reloaded.get("owner").frames()).hasSize(1);assertThatThrownBy(()->reloaded.update("owner",new ProfileAppearance.Settings("custom",true,1,0,0,List.of(),stranger.customFrame(),""),false,List.of())).hasMessageContaining("400");
 var empty=reloaded.removeFrame("owner",first.frames().get(0).id());assertThat(empty.frame()).isEqualTo("none");assertThat(empty.frames()).isEmpty();assertThat(reloaded.get("stranger").frames()).hasSize(1);
 }
 @Test void legacyAppearanceMigratesOneOwnedFrameAndKeepsAvatarDefaults()throws Exception{
 var folder=dir.resolve("appearance");java.nio.file.Files.createDirectories(folder);java.nio.file.Files.writeString(folder.resolve("settings.json"),"{\"legacy\":{\"frame\":\"custom\",\"holidayBadge\":true,\"scale\":1.2,\"x\":0,\"y\":0,\"tags\":[],\"customFrame\":\"/api/campus-social/appearance/files/11111111-1111-1111-1111-111111111111.png\",\"banner\":\"\"}}");var p=new ProfileAppearance(new ObjectMapper(),dir.toString());assertThat(p.get("legacy").frames()).hasSize(1);assertThat(p.get("legacy").avatarScale()).isEqualTo(1);assertThat(p.get("legacy").customFrame()).endsWith("11111111-1111-1111-1111-111111111111.png");
 }
}
