const {chromium}=require('playwright-core'),fs=require('fs'),assert=require('assert/strict');
(async()=>{fs.mkdirSync('tests/e2e/artifacts',{recursive:true});const b=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const c=await b.newContext({viewport:{width:1360,height:900}}),p=await c.newPage();p.setDefaultTimeout(7000);let me,post;const errors=[];p.on('pageerror',e=>errors.push(e.message));const api=async(path,method='GET',data)=>{const r=await c.request.fetch('http://localhost:8088/api/campus-social'+path,{method,data,headers:me?{'X-Workspace-Token':me.token}:{}});assert(r.ok(),path);return r.json()};try{
 const u=JSON.parse(fs.readFileSync(process.env.E2E_USER_FILE||'tests/e2e/accounts.local.json')).bob;assert.equal((await(await c.request.post('http://localhost:8088/api/user/login',{data:u})).json()).code,200);me=await api('/me');post=await api('/posts','POST',{text:'自动收起动画验证',anonymous:false,category:'general'});await api('/posts/'+post.id+'/replies','POST',{text:'回复目标'});const comment=(await api('/posts/'+post.id+'/replies'))[0];
 for(const width of [1360,390]){await p.setViewportSize({width,height:900});await p.goto('http://localhost:8088/page/wall?post='+post.id);const card=p.locator('#post-'+post.id),row=card.locator('[data-reply-id="'+comment.id+'"]'),button=row.locator('.reply-thread-button'),form=row.locator('.inline-reply');
 const open=async()=>{await button.click();await form.waitFor();await p.waitForTimeout(800);assert.equal(await button.getAttribute('aria-expanded'),'true');};
 await open();await form.locator('textarea').fill('保存的草稿');await form.locator('textarea').click();assert.equal(await form.count(),1);
 // Outside pointer starts a visible height/opacity exit; exiting controls become inert.
 const animation=await row.evaluate(el=>{const wrap=el.querySelector('.reply-composer-transition');const before=wrap.getBoundingClientRect().height;document.querySelector('.social-replies h2').dispatchEvent(new PointerEvent('pointerdown',{bubbles:true}));return new Promise(resolve=>setTimeout(()=>resolve({before,height:wrap.getBoundingClientRect().height,opacity:+getComputedStyle(wrap).opacity,inert:wrap.hasAttribute('inert')}),80))});assert(animation.height>0&&animation.height<animation.before,JSON.stringify(animation));assert(animation.opacity<1);assert(animation.inert);await form.waitFor({state:'detached'});
 await open();assert.equal(await form.locator('textarea').inputValue(),'保存的草稿');await p.mouse.move(width-12,450);await p.mouse.wheel(0,180);await form.waitFor({state:'detached'});
 await open();assert.equal(await form.locator('textarea').inputValue(),'保存的草稿');await form.locator('textarea').fill(Array.from({length:18},(_,i)=>'长回复 '+i).join('\n'));await form.locator('textarea').evaluate(el=>el.scrollTop=0);await form.locator('textarea').hover();await p.mouse.wheel(0,25);await p.waitForTimeout(300);assert.equal(await button.getAttribute('aria-expanded'),'true');await form.locator('textarea').press('Escape');await form.waitFor({state:'detached'});
 await open();await p.evaluate(()=>{document.body.style.minHeight='3000px';window.scrollBy(0,80)});await form.waitFor({state:'detached'});
 await open();await form.locator('textarea').fill('发送后收起');await form.locator('.inline-reply-send').click();await form.waitFor({state:'detached'});
 assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),width);
 }
 for(const where of ['wall','profile']){await p.setViewportSize({width:1360,height:900});await p.goto('http://localhost:8088'+(where==='wall'?'/page/wall':'/page/user/home?account='+me.account.id));const card=p.locator('#post-'+post.id);await card.locator('.post-featured-comment>.reply-thread-button').click();await card.locator('textarea').fill('列表草稿');await p.waitForTimeout(300);await p.mouse.move(10,400);await p.mouse.wheel(0,100);await card.locator('.inline-reply').waitFor({state:'detached'});await card.locator('.post-featured-comment>.reply-thread-button').click();assert.equal(await card.locator('textarea').inputValue(),'列表草稿');}
 assert.deepEqual(errors,[]);console.log(JSON.stringify({outsideClick:true,pageWheel:true,pageScroll:true,internalTextareaScrollPreserved:true,escape:true,draftsPreserved:true,sendCollapse:true,animatedHeightAndOpacity:true,inertDuringExit:true,desktopMobile:true,wallProfile:true,pageErrors:errors}));
 }finally{if(post)await api('/posts/'+post.id,'DELETE');await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
