const {chromium}=require('playwright-core'),fs=require('fs'),assert=require('assert/strict');
(async()=>{fs.mkdirSync('tests/e2e/artifacts',{recursive:true});const b=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const c=await b.newContext({viewport:{width:1360,height:1000},reducedMotion:'reduce'}),p=await c.newPage();p.setDefaultTimeout(6000);let me,post;const api=async(path,method='GET',data)=>{const r=await c.request.fetch('http://localhost:8088/api/campus-social'+path,{method,data,headers:me?{'X-Workspace-Token':me.token}:{}});assert(r.ok(),path);return r.json()};try{
 const u=JSON.parse(fs.readFileSync(process.env.E2E_USER_FILE||'tests/e2e/accounts.local.json')).bob;assert.equal((await(await c.request.post('http://localhost:8088/api/user/login',{data:u})).json()).code,200);me=await api('/me');post=await api('/posts','POST',{text:'回复交互验证',anonymous:false,category:'general'});await api('/posts/'+post.id+'/replies','POST',{text:'第一条评论'});await api('/posts/'+post.id+'/replies','POST',{text:'第二条评论'});const comments=await api('/posts/'+post.id+'/replies'),one=comments[0].id,two=comments[1].id;
 for(const where of ['wall','profile']){await p.goto('http://localhost:8088'+(where==='wall'?'/page/wall':'/page/user/home?account='+me.account.id));const card=p.locator('#post-'+post.id);await card.waitFor();const icon=card.locator('.post-featured-comment>.reply-thread-button');assert.equal(await icon.evaluate(e=>getComputedStyle(e).backgroundColor),'rgba(0, 0, 0, 0)');assert.equal(await icon.evaluate(e=>getComputedStyle(e).borderRadius),'999px');await card.locator('.post-featured-comment').screenshot({path:'tests/e2e/artifacts/reply-v22-icon-'+where+'.png'});await card.getByRole('button',{name:'回复帖子',exact:true}).click();await card.locator('textarea').fill('列表回复 '+where);await card.locator('.inline-reply-send').click();await card.locator('.inline-reply').waitFor({state:'detached'});await icon.click();await card.locator('textarea').fill('回复精选评论 '+where);await card.locator('.inline-reply-send').click();await card.locator('.inline-reply').waitFor({state:'detached'});}
 for(const width of [1360,390]){await p.setViewportSize({width,height:1000});await p.goto('http://localhost:8088/page/wall?post='+post.id);const card=p.locator('#post-'+post.id),root=card.locator('.social-post-body>.reply-composer-transition>.inline-reply'),r1=card.locator('[data-reply-id="'+one+'"]'),r2=card.locator('[data-reply-id="'+two+'"]');await root.locator('textarea').fill('母帖草稿 '+width);await r1.locator('.reply-thread-button').click();await root.waitFor({state:'detached'});assert.equal(await card.locator('.inline-reply').count(),1);await r1.locator('textarea').fill('评论一草稿 '+width);await r2.locator('.reply-thread-button').click();await r2.locator('textarea').fill('评论二草稿');await r1.locator('.reply-thread-button').click();assert.equal(await r1.locator('textarea').inputValue(),'评论一草稿 '+width);
 const actions=await r1.locator('.reply-actions').boundingBox(),form=await r1.locator('.inline-reply').boundingBox();assert(form.y>=actions.y+actions.height);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),width);await r1.screenshot({path:'tests/e2e/artifacts/reply-v22-detail-'+width+'.png'});
 const route='**/api/campus-social/posts/'+post.id+'/replies';const fail=async route=>{if(route.request().method()==='POST')await route.fulfill({status:503,json:{message:'暂时无法发送'}});else await route.continue()};await p.route(route,fail);await r1.locator('.inline-reply-send').click();await r1.locator('.social-error').waitFor();assert.equal(await r1.locator('textarea').inputValue(),'评论一草稿 '+width);await p.unroute(route,fail);await r1.locator('.inline-reply-send').click();await card.locator('.inline-reply').waitFor({state:'detached'});assert((await api('/posts/'+post.id+'/replies')).some(r=>r.text==='评论一草稿 '+width&&r.parentReply===one));
 await card.getByRole('button',{name:'回复帖子',exact:true}).click();assert.equal(await root.locator('textarea').inputValue(),'母帖草稿 '+width);await root.locator('.inline-reply-send').click();await card.locator('.inline-reply').waitFor({state:'detached'});
 }
 console.log(JSON.stringify({collapseAfterSend:true,wallAndProfileIcons:true,detailComposerBelowSelectedComment:true,oneComposerAtATime:true,independentDrafts:true,failedSendPreservesDraft:true,parentReplyCorrect:true,desktopMobile:true}));
 }catch(e){await p.screenshot({path:'tests/e2e/artifacts/reply-v22-failure.png',fullPage:true});console.log(await p.locator('textarea').evaluateAll(es=>es.map(e=>{let x=e,a=[];for(let i=0;x&&i<7;i++,x=x.parentElement){let r=x.getBoundingClientRect(),c=getComputedStyle(x);a.push({class:x.className,width:r.width,height:r.height,display:c.display,grid:c.gridTemplateColumns})}return a})));throw e;}finally{if(post)await api('/posts/'+post.id,'DELETE');await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
