package com.qpwflshclub.formal_club.workspace;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import java.io.IOException;import java.nio.file.*;import java.time.*;import java.util.*;
/** Term reports, attendance and recruitment remain private to the managed club. */
@Service public class ClubOperationsStore {
 public record Term(String id,String name,String start,String end){}
 public record Report(String id,String term,String kind,String activity,String title,String content,String feedback,String improvements,String document,String status,String updatedAt,String submittedAt,String author){}
 public record Mark(String member,String name,String nameEn,String status){}
 public record Attendance(String activity,List<Mark> marks,String updatedAt,String author){}
 public record Candidate(String id,String term,long student,String name,String nameEn,String note,String status,String createdAt,String confirmedAt){}
 public record Data(List<Term> terms,List<Report> reports,List<Attendance> attendance,List<Candidate> candidates){}
 private final Path root;private final ObjectMapper mapper;
 public ClubOperationsStore(ObjectMapper m,@Value("${club.workspace-dir:./data/club-workspace}")String directory){mapper=m;root=Path.of(directory).toAbsolutePath().normalize();}
 private Path dir(int club){if(club<=0)throw WorkspaceStore.bad("社团无效");return root.resolve(String.valueOf(club));}
 public synchronized Data read(int club)throws IOException{Path p=dir(club).resolve("operations.json");return Files.exists(p)?mapper.readValue(p.toFile(),Data.class):new Data(new ArrayList<>(),new ArrayList<>(),new ArrayList<>(),new ArrayList<>());}
 private void write(int club,Data d)throws IOException{Files.createDirectories(dir(club));Path p=Files.createTempFile(dir(club),"operations-",".tmp");try{mapper.writeValue(p.toFile(),d);Files.move(p,dir(club).resolve("operations.json"),StandardCopyOption.ATOMIC_MOVE,StandardCopyOption.REPLACE_EXISTING);}finally{Files.deleteIfExists(p);}}
 public static String now(){return LocalDateTime.now(ZoneId.of("Asia/Shanghai")).toString();}
 public synchronized Term term(int club,String name,String start,String end)throws IOException{Data d=read(club);LocalDate a,b;try{a=LocalDate.parse(start);b=LocalDate.parse(end);}catch(RuntimeException e){throw WorkspaceStore.bad("请选择学期起止日期");}if(!b.isAfter(a)||b.isAfter(a.plusYears(1)))throw WorkspaceStore.bad("学期结束应晚于开始，且不能超过一年");name=text(name,80,true);for(var t:d.terms())if(!a.isAfter(LocalDate.parse(t.end()))&&!b.isBefore(LocalDate.parse(t.start())))throw WorkspaceStore.bad("此日期范围已存在学期，请选择已有学期");Term t=new Term(UUID.randomUUID().toString(),name,a.toString(),b.toString());d.terms().add(0,t);write(club,d);return t;}
 public Term term(Data d,String id){return d.terms().stream().filter(t->t.id().equals(id)).findFirst().orElseThrow(()->WorkspaceStore.bad("请先选择学期"));}
 public synchronized Report report(int club,Report input)throws IOException{Data d=read(club);term(d,input.term());Report old=d.reports().stream().filter(r->r.term().equals(input.term())&&r.kind().equals(input.kind())&&r.activity().equals(input.activity())).findFirst().orElse(null);if(old!=null&&old.status().equals("submitted")&&input.status().equals("draft"))throw WorkspaceStore.bad("已提交的记录请修改后重新提交");Report r=new Report(old==null?UUID.randomUUID().toString():old.id(),input.term(),input.kind(),input.activity(),input.title(),input.content(),input.feedback(),input.improvements(),input.document(),input.status(),now(),input.status().equals("submitted")?now():"",input.author());if(old!=null)d.reports().remove(old);d.reports().add(0,r);write(club,d);return r;}
 public synchronized Attendance attendance(int club,String activity,List<Mark> marks,String author)throws IOException{Data d=read(club);Attendance a=new Attendance(activity,List.copyOf(marks),now(),author);d.attendance().removeIf(v->v.activity().equals(activity));d.attendance().add(a);write(club,d);return a;}
 public synchronized Candidate candidate(int club,String term,long student,String name,String nameEn,String note)throws IOException{Data d=read(club);term(d,term);if(d.candidates().stream().anyMatch(c->c.term().equals(term)&&c.student()==student))throw WorkspaceStore.bad("该同学已在本学期招新名单中");Candidate c=new Candidate(UUID.randomUUID().toString(),term,student,name,nameEn,text(note,500,false),"pending",now(),"");d.candidates().add(0,c);write(club,d);return c;}
 public Candidate candidate(Data d,String id){return d.candidates().stream().filter(c->c.id().equals(id)).findFirst().orElseThrow(()->WorkspaceStore.bad("招新记录不存在"));}
 public synchronized Candidate decide(int club,String id,String status)throws IOException{if(!Set.of("confirmed","declined").contains(status))throw WorkspaceStore.bad("招新决定无效");Data d=read(club);Candidate c=candidate(d,id);if(c.status().equals(status))return c;if(!c.status().equals("pending"))throw WorkspaceStore.bad("该招新记录已处理");Candidate next=new Candidate(c.id(),c.term(),c.student(),c.name(),c.nameEn(),c.note(),status,c.createdAt(),status.equals("confirmed")?now():"");d.candidates().set(d.candidates().indexOf(c),next);write(club,d);return next;}
 public static String text(String s,int max,boolean required){s=Objects.toString(s,"").trim();if(s.length()>max||(required&&s.isBlank()))throw WorkspaceStore.bad("请完整填写内容，单项最多 "+max+" 字");return s;}
 public synchronized void removeAccount(int club,String email,String account,Set<Long> students,Set<String> memberIds)throws IOException{Data d=read(club);d.reports().removeIf(v->email.equalsIgnoreCase(v.author())||account.equals(v.author()));d.candidates().removeIf(v->students.contains(v.student()));d.attendance().replaceAll(v->new Attendance(v.activity(),v.marks().stream().filter(m->!account.equals(m.member())&&!email.equalsIgnoreCase(m.member())&&!memberIds.contains(m.member())).toList(),v.updatedAt(),email.equalsIgnoreCase(v.author())||account.equals(v.author())?"":v.author()));write(club,d);}
}
