<?php
declare(strict_types=1);namespace MRBS;
function school_trial_slot(int $start,int $end): bool {
  $zone=new \DateTimeZone('Asia/Shanghai');
  $a=(new \DateTimeImmutable('@'.$start))->setTimezone($zone);
  $b=(new \DateTimeImmutable('@'.$end))->setTimezone($zone);
  if($end-$start!==1200 || $a->format('Y-m-d')!==$b->format('Y-m-d') || (int)$a->format('N')>5 || $a->format('s')!=='00')return false;
  $minute=(int)$a->format('H')*60+(int)$a->format('i');
  foreach([[690,770],[990,1110]] as [$from,$to])if($minute>=$from && $minute+20<=$to && ($minute-$from)%20===0)return true;
  return false;
}
function school_trial_message(): string {return ($_COOKIE['club_language']??'')==='en' ? 'Trial operation: court slots are limited to 11:30–12:50 and 16:30–18:30, 20 minutes each.' : '试运行阶段仅开放午休和晚间休息时段：11:30–12:50 / 16:30–18:30，每段20分钟。';}
function school_student_window(?\DateTimeImmutable $now=null): bool { $now=$now??new \DateTimeImmutable('now',new \DateTimeZone('Asia/Shanghai'));$day=(int)$now->format('N');$minutes=(int)$now->format('H')*60+(int)$now->format('i');return $day>=6&&$minutes>=780&&$minutes<1140; }
function school_queue_deadline(int $start): int {$date=(new \DateTimeImmutable('@'.$start))->setTimezone(new \DateTimeZone('Asia/Shanghai'));return $date->modify('monday this week')->modify('-1 day')->setTime(19,0)->getTimestamp();}
function school_booking_lock(): void {static $locked=false;if($locked)return;if((int)db()->query1("SELECT GET_LOCK('school_court_booking',10)")!==1)throw new \RuntimeException('Booking busy. Please retry.');$locked=true;register_shutdown_function(function(){try{db()->query1("SELECT RELEASE_LOCK('school_court_booking')");}catch(\Throwable $e){}});}
function school_queue_install(): void {db()->command("CREATE TABLE IF NOT EXISTS school_teacher_queue (id BIGINT PRIMARY KEY AUTO_INCREMENT, email VARCHAR(254) NOT NULL, display_name VARCHAR(100) NOT NULL, room_id INT NOT NULL, start_time INT NOT NULL, end_time INT NOT NULL, confirm_after INT NOT NULL, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), status VARCHAR(16) NOT NULL DEFAULT 'pending', entry_id INT NULL, UNIQUE KEY teacher_slot(email,room_id,start_time), KEY pending_deadline(status,confirm_after)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");}
function school_teacher_submit(array $account,int $room,int $start,int $end): array {if(!school_trial_slot($start,$end))throw new \RuntimeException(school_trial_message());school_booking_lock();school_queue_install();$email=$account['email'];$existing=db()->query("SELECT status FROM school_teacher_queue WHERE email=? AND room_id=? AND start_time=?",[$email,$room,$start])->all_rows_keyed();if($existing)return ['status'=>$existing[0]['status'],'pending'=>$existing[0]['status']==='pending'];$date=(new \DateTimeImmutable('@'.$start))->setTimezone(new \DateTimeZone('Asia/Shanghai'));$week=$date->modify('monday this week')->setTime(0,0)->getTimestamp();$day=$date->setTime(0,0)->getTimestamp();foreach([[$week,$week+5*86400,3],[$day,$day+86400,1]] as [$from,$to,$limit]){$used=(int)db()->query1('SELECT COUNT(*) FROM '._tbl('entry').' WHERE LOWER(create_by)=LOWER(?) AND start_time>=? AND start_time<?',[$email,$from,$to]);$queued=(int)db()->query1("SELECT COUNT(*) FROM school_teacher_queue WHERE email=? AND status='pending' AND start_time>=? AND start_time<?",[$email,$from,$to]);if($used+$queued>=$limit)throw new \RuntimeException('每周最多三次，每天一次 / Up to 3 bookings a week, 1 per day');}db()->command("INSERT INTO school_teacher_queue(email,display_name,room_id,start_time,end_time,confirm_after) VALUES(?,?,?,?,?,?)",[$email,$account['display_name'],$room,$start,$end,school_queue_deadline($start)]);school_resolve_teachers();$status=db()->query('SELECT status FROM school_teacher_queue WHERE email=? AND room_id=? AND start_time=?',[$email,$room,$start])->all_rows_keyed()[0]['status'];return ['status'=>$status,'pending'=>$status==='pending'];}
function school_resolve_teachers(?int $now=null): void {school_booking_lock();$now=$now??time();$pending=db()->query("SELECT * FROM school_teacher_queue WHERE status='pending' AND confirm_after<=? ORDER BY created_at,id",[$now])->all_rows_keyed();foreach($pending as $p){db()->begin();try{$conflict=(int)db()->query1('SELECT COUNT(*) FROM '._tbl('entry').' WHERE room_id=? AND start_time<? AND end_time>?',[$p['room_id'],$p['end_time'],$p['start_time']]);if($conflict||$p['start_time']<=$now||!school_trial_slot((int)$p['start_time'],(int)$p['end_time'])){db()->command("UPDATE school_teacher_queue SET status='unavailable' WHERE id=?",[$p['id']]);}else{db()->command('INSERT INTO '._tbl('entry')." (start_time,end_time,room_id,create_by,modified_by,name,description,type,ical_uid) VALUES(?,?,?,?,?,?,?,'E',?)",[$p['start_time'],$p['end_time'],$p['room_id'],$p['email'],$p['email'],mb_substr($p['display_name'],0,80),'Teacher booking confirmed after student priority window',bin2hex(random_bytes(16)).'@qpwflhsclub.com']);$id=db()->query1('SELECT LAST_INSERT_ID()');db()->command("UPDATE school_teacher_queue SET status='confirmed',entry_id=? WHERE id=?",[$id,$p['id']]);}db()->commit();}catch(\Throwable $e){db()->rollback();throw $e;}}}
