package com.qpwflshclub.formal_club.workspace;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.qpwflshclub.formal_club.pojo.User.*;
import com.qpwflshclub.formal_club.pojo.Club.Club;
import com.qpwflshclub.formal_club.repository.Club.ClubRepository;
import com.qpwflshclub.formal_club.repository.User.*;
import com.qpwflshclub.formal_club.service.User.IUserService;
import org.junit.jupiter.api.*;import org.junit.jupiter.api.io.TempDir;import org.springframework.mock.web.MockHttpServletRequest;
import java.nio.file.Path;import java.time.*;import java.util.*;
import static org.assertj.core.api.Assertions.*;import static org.mockito.Mockito.*;
class ClubOperationsTest {
 @TempDir Path dir;ClubOperationsStore store;WorkspaceStore workspace;WorkspaceAccess access;WorkspaceController members;ClubOperationsController controller;MockHttpServletRequest request;UserRepository students;ClubPresidentRepository presidents;IUserService users;Club club;ClubPresident leader;User student;String term,event,future;
 @BeforeEach void setup()throws Exception{users=mock(IUserService.class);students=mock(UserRepository.class);presidents=mock(ClubPresidentRepository.class);var clubs=mock(ClubRepository.class);club=new Club();club.setId(1);club.setClubName("Club");leader=new ClubPresident();leader.setId(9);leader.setEmail("leader@example.com");leader.setUsername("Leader");leader.setMainClub(club);student=new User();student.setId(1);student.setEmail("student@example.com");student.setUsername("Student");student.setUsernameEn("Student");student.setClubs(new ArrayList<>());when(users.findByEmail(leader.getEmail())).thenReturn(leader);when(students.findAll()).thenReturn(List.of(student));when(students.findById(1L)).thenReturn(Optional.of(student));when(presidents.findAll()).thenReturn(List.of(leader));access=new WorkspaceAccess(users,clubs);workspace=new WorkspaceStore(new ObjectMapper(),dir.toString());store=new ClubOperationsStore(new ObjectMapper(),dir.toString());members=new WorkspaceController(access,workspace,students,presidents);org.springframework.test.util.ReflectionTestUtils.setField(members,"operations",store);controller=new ClubOperationsController(access,workspace,store,members,students);request=new MockHttpServletRequest();request.getSession().setAttribute("authenticatedEmail",leader.getEmail());request.addHeader("X-Workspace-Token",access.token(request));LocalDate day=LocalDate.now(ZoneId.of("Asia/Shanghai"));term=store.term(1,"Semester",day.minusMonths(1).toString(),day.plusMonths(4).toString()).id();event=add("past",day.minusDays(2).toString());future=add("future",day.plusDays(5).toString());}
 String add(String id,String day)throws Exception{workspace.add(1,new WorkspaceStore.Activity(id,id,day+"T15:00",day+"T16:00","Room","Session",10,"event","scheduled","author",day,"",""));return id;}
 ClubOperationsController.ReportInput report(String kind,String activity,String content,String feedback,String improvements,String status){return new ClubOperationsController.ReportInput(term,kind,activity,"Title",content,feedback,improvements,"",status);}
 @Test void accessRequiresOwnClubAndMutationToken()throws Exception{assertThatThrownBy(()->controller.data(2,request)).hasMessageContaining("403");var anon=new MockHttpServletRequest();assertThatThrownBy(()->controller.data(1,anon)).hasMessageContaining("401");when(users.findByEmail(leader.getEmail())).thenReturn(student);assertThatThrownBy(()->controller.data(1,request)).hasMessageContaining("403");when(users.findByEmail(leader.getEmail())).thenReturn(leader);request.removeHeader("X-Workspace-Token");assertThatThrownBy(()->controller.report(1,report("proposal","","Plan","","","draft"),request)).hasMessageContaining("403");assertThat(store.read(1).reports()).isEmpty();}
 @Test void semesterReportsPersistAsDraftAndSubmittedRevisions()throws Exception{controller.report(1,report("proposal","","","","","draft"),request);assertThatThrownBy(()->controller.report(1,report("proposal","","","","","submitted"),request)).hasMessageContaining("400");controller.report(1,report("proposal","","Goals and schedule","","","submitted"),request);controller.report(1,report("proposal","","Updated plan","","","submitted"),request);var data=new ClubOperationsStore(new ObjectMapper(),dir.toString()).read(1);assertThat(data.reports()).hasSize(1);assertThat(data.reports().getFirst().content()).isEqualTo("Updated plan");assertThat(data.reports().getFirst().submittedAt()).isNotBlank();assertThatThrownBy(()->controller.report(1,report("proposal","","Draft again","","","draft"),request)).hasMessageContaining("已提交");assertThatThrownBy(()->controller.report(1,report("review","","Summary","","","submitted"),request)).hasMessageContaining("400");controller.report(1,report("review","","Summary","Members liked it","Improve next term","submitted"),request);assertThat(store.read(1).reports()).hasSize(2);}
 @Test void feedbackMustBelongToThisTermAndAnEndedActivity()throws Exception{assertThatThrownBy(()->controller.report(1,report("feedback",future,"Session","Response","Next","submitted"),request)).hasMessageContaining("活动结束");controller.report(1,report("feedback",future,"Draft","","","draft"),request);assertThatThrownBy(()->controller.report(1,report("feedback",event,"Session","","Next","submitted"),request)).hasMessageContaining("400");controller.report(1,report("feedback",event,"Session","Response","Next","submitted"),request);assertThatThrownBy(()->controller.report(1,report("feedback","foreign","Session","Response","Next","submitted"),request)).hasMessageContaining("请选择");String outside=add("outside",LocalDate.now().minusYears(2).toString());assertThatThrownBy(()->controller.report(1,report("feedback",outside,"Session","Response","Next","submitted"),request)).hasMessageContaining("不在所选学期");assertThatThrownBy(()->members.removeEvent(1,event,request)).hasMessageContaining("已有签到或反馈");}
 @Test void attachmentsMustBeStoredInsideTheAuthorizedClub()throws Exception{var doc=workspace.upload(2,new org.springframework.mock.web.MockMultipartFile("file","proposal.pdf","application/pdf","test".getBytes()),"","author");var input=new ClubOperationsController.ReportInput(term,"proposal","","Plan","Content","","",doc.id(),"submitted");assertThatThrownBy(()->controller.report(1,input,request)).hasMessageContaining("文件不存在");}
 @Test void attendanceAllowsOnlyActualMembersAndThreeExplicitStates()throws Exception{assertThat(store.read(1).attendance()).isEmpty();var foreign=new ClubOperationsController.AttendanceInput(List.of(new ClubOperationsController.MarkInput("student:1","present")));assertThatThrownBy(()->controller.attendance(1,event,foreign,request)).hasMessageContaining("本社团成员");student.getClubs().add(club);assertThatThrownBy(()->controller.attendance(1,future,foreign,request)).hasMessageContaining("开始后");for(String status:List.of("present","leave","absent")){controller.attendance(1,event,new ClubOperationsController.AttendanceInput(List.of(new ClubOperationsController.MarkInput("student:1",status))),request);assertThat(new ClubOperationsStore(new ObjectMapper(),dir.toString()).read(1).attendance().getFirst().marks().getFirst().status()).isEqualTo(status);}assertThatThrownBy(()->controller.attendance(1,event,new ClubOperationsController.AttendanceInput(List.of(new ClubOperationsController.MarkInput("student:1","fake"))),request)).hasMessageContaining("签到状态");student.getClubs().clear();controller.attendance(1,event,new ClubOperationsController.AttendanceInput(List.of(new ClubOperationsController.MarkInput("president:9","present"))),request);assertThat(store.read(1).attendance().getFirst().marks()).hasSize(2);assertThatThrownBy(()->members.removeEvent(1,event,request)).hasMessageContaining("不能删除");}
 @Test void recruitmentWaitsForConfirmationAndIsIdempotent()throws Exception{var c=(ClubOperationsStore.Candidate)controller.candidate(1,new ClubOperationsController.CandidateInput(term,1,"Interviewed"),request);assertThat(student.getClubs()).isEmpty();verify(students,never()).save(any());assertThatThrownBy(()->controller.candidate(1,new ClubOperationsController.CandidateInput(term,1,""),request)).hasMessageContaining("已在");controller.confirm(1,c.id(),request);controller.confirm(1,c.id(),request);assertThat(student.getClubs()).containsExactly(club);verify(students,times(1)).save(student);assertThat(new ClubOperationsStore(new ObjectMapper(),dir.toString()).read(1).candidates().getFirst().status()).isEqualTo("confirmed");assertThatThrownBy(()->controller.decline(1,c.id(),request)).hasMessageContaining("已处理");}
 @Test void decliningOrWrongClubNeverAddsMembership()throws Exception{var c=(ClubOperationsStore.Candidate)controller.candidate(1,new ClubOperationsController.CandidateInput(term,1,""),request);assertThatThrownBy(()->controller.confirm(2,c.id(),request)).hasMessageContaining("403");controller.decline(1,c.id(),request);assertThatThrownBy(()->controller.confirm(1,c.id(),request)).hasMessageContaining("已处理");assertThat(student.getClubs()).isEmpty();verify(students,never()).save(any());}
 @Test void overlappingSemestersAreRejected()throws Exception{var t=store.read(1).terms().getFirst();assertThatThrownBy(()->controller.term(1,new ClubOperationsController.TermInput("Duplicate",t.start(),t.end()),request)).hasMessageContaining("已存在学期");assertThatThrownBy(()->controller.term(1,new ClubOperationsController.TermInput("Invalid",t.end(),t.start()),request)).hasMessageContaining("结束应晚于");}
}
