import {readFile} from 'node:fs/promises';
import {test} from 'node:test';
import assert from 'node:assert/strict';
const source=await readFile(new URL('../message-crypto.js',import.meta.url),'utf8');
const c=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
test('only the sender and recipient decrypt; tampering and wrong participant fail',async()=>{const a=await c.makeIdentity(),b=await c.makeIdentity(),other=await c.makeIdentity();const message={sender:'alice',recipient:'bob',text:await c.encryptMessage(a,b,'alice','bob','私人消息：一起组队')};assert(!message.text.includes('私人消息'));assert.equal(await c.decryptMessage(b,a,'bob',message),'私人消息：一起组队');assert.equal(await c.decryptMessage(a,b,'alice',message),'私人消息：一起组队');await assert.rejects(()=>c.decryptMessage(other,a,'bob',message));await assert.rejects(()=>c.decryptMessage(b,a,'bob',{...message,sender:'mallory'}));const e=JSON.parse(message.text.slice(8));const bytes=c.unb64(e.ciphertext);bytes[0]^=1;e.ciphertext=c.b64(bytes);await assert.rejects(()=>c.decryptMessage(b,a,'bob',{...message,text:'e2ee:v1:'+JSON.stringify(e)}));assert.equal(await c.safetyCode(a,b),await c.safetyCode(b,a));});
test('same plaintext produces unique IVs and distinct ciphertext',async()=>{const a=await c.makeIdentity(),b=await c.makeIdentity();assert.notEqual(await c.encryptMessage(a,b,'a','b','hello'),await c.encryptMessage(a,b,'a','b','hello'));});
test('encrypted backup restores original key; wrong password and different account fail; changed peer keys stop sending',async()=>{
 const memory=new Map();globalThis.indexedDB={open(){const request={};setTimeout(()=>{request.result={close(){},transaction(){const tx={objectStore(){return {get(id){const r={};setTimeout(()=>{r.result=memory.get(id);r.onsuccess();tx.oncomplete();},0);return r;},put(value,id){const r={};setTimeout(()=>{memory.set(id,value);r.result=id;r.onsuccess();tx.oncomplete();},0);return r;}};}};return tx;}};request.onsuccess();},0);return request;}};
 let remote={ready:false},saved=null;const api=async path=>path==='/keys/recovery'?(saved?{ready:true,...saved}:{ready:false}):remote;const write=async(path,_m,data)=>{if(path==='/keys/provision'){const own=await c.makeIdentity();saved={publicKey:own.publicKey,privateKey:c.b64(await crypto.subtle.exportKey('pkcs8',own.privateKey))};remote={ready:true,publicKey:own.publicKey,fingerprint:own.fingerprint};return remote;}if(path==='/keys/recovery'){saved=data;return {ok:true}}const fingerprint=Buffer.from(await crypto.subtle.digest('SHA-256',c.unb64(data.publicKey))).toString('hex');remote={ready:true,...data,fingerprint};};
 const original=await c.ensureIdentity('backup-account',api,write);const encoded=await c.exportIdentity('backup-account','long backup password');assert(!encoded.includes('privateJwk'));const file=new File([encoded],'key.json');memory.delete('backup-account');await assert.rejects(()=>c.importIdentity('backup-account','wrong password',file,api,write));await assert.rejects(()=>c.importIdentity('other-account','long backup password',file,api,write));const restored=await c.importIdentity('backup-account','long backup password',file,api,write);assert.equal(restored.fingerprint,original.fingerprint);const peer=await c.makeIdentity(),message={sender:'backup-account',recipient:'peer',text:await c.encryptMessage(original,peer,'backup-account','peer','backed up')};assert.equal(await c.decryptMessage(restored,peer,'backup-account',message),'backed up');await c.verifyPeer('me','peer',peer);const changed=await c.makeIdentity();await assert.rejects(()=>c.verifyPeer('me','peer',changed));
});
