package com.qpwflshclub.formal_club.social;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.core.type.TypeReference;
import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Value;
import java.nio.file.*;import java.util.*;import java.util.function.Supplier;import java.io.IOException;
/** Single-instance private profile registry. Student numbers are unique and immutable. */
@Service public class AccountProfiles {
 public record Profile(String studentNumber,String nickname,String grade,String classroom,List<String> tags,String bio){public Profile{tags=tags==null?List.of():List.copyOf(tags);}}
 private final Path file;private final ObjectMapper json=new ObjectMapper();private final Map<String,Profile> profiles;
 public AccountProfiles(@Value("${club.profiles-file:./data/accounts/profiles.json}")String path)throws IOException{file=Path.of(path);profiles=Files.exists(file)?json.readValue(Files.readAllBytes(file),new TypeReference<LinkedHashMap<String,Profile>>(){}):new LinkedHashMap<>();}
 public synchronized Profile get(String email){return profiles.getOrDefault(SchoolAccounts.key(email),new Profile("","","","",List.of(),""));}
 private String clean(String value,int limit){value=Objects.toString(value,"").strip();if(value.length()>limit||value.codePoints().anyMatch(c->Character.isISOControl(c)&&c!='\n'))throw SchoolAccounts.error(400,"资料超出长度限制 / Profile text is too long");return value;}
 private String number(String email,String input){String n=java.text.Normalizer.normalize(clean(input,32),java.text.Normalizer.Form.NFKC).toUpperCase(Locale.ROOT);String current=get(email).studentNumber();if(!current.isEmpty()&&!current.equals(n))throw SchoolAccounts.error(409,"学生号绑定后不能修改 / Student number cannot be changed");if(!n.isEmpty()&&!n.matches("[A-Z0-9-]{1,32}"))throw SchoolAccounts.error(400,"请填写有效学生号 / Enter a valid student number");String me=SchoolAccounts.key(email);if(!n.isEmpty()&&profiles.entrySet().stream().anyMatch(e->!e.getKey().equals(me)&&n.equals(e.getValue().studentNumber())))throw SchoolAccounts.error(409,"这个学生号已绑定账户 / This student number is already registered");return n;}
 private void persist(){try{Files.createDirectories(file.toAbsolutePath().getParent());Path tmp=Files.createTempFile(file.toAbsolutePath().getParent(),"profiles-",".tmp");try{Files.setPosixFilePermissions(tmp,java.nio.file.attribute.PosixFilePermissions.fromString("rw-------"));Files.write(tmp,json.writeValueAsBytes(profiles));Files.move(tmp,file.toAbsolutePath(),StandardCopyOption.ATOMIC_MOVE,StandardCopyOption.REPLACE_EXISTING);}finally{Files.deleteIfExists(tmp);}}catch(IOException e){throw new IllegalStateException("Profile storage unavailable",e);}}
 public synchronized <T>T register(String email,String studentNumber,String nickname,boolean student,Supplier<T> create){String key=SchoolAccounts.key(email);if(profiles.containsKey(key))throw SchoolAccounts.error(409,"此邮箱已注册 / Email already registered");String n=number(email,studentNumber);if(student&&n.isEmpty())throw SchoolAccounts.error(400,"请填写学生号 / Student number is required");profiles.put(key,new Profile(n,clean(nickname,60),"","",List.of(),""));try{persist();return create.get();}catch(RuntimeException e){profiles.remove(key);persist();throw e;}}
 public synchronized Profile update(String email,Profile input,boolean student){var old=get(email);String n=student?number(email,input.studentNumber()==null?old.studentNumber():input.studentNumber()):old.studentNumber();var tags=input.tags().stream().map(v->clean(v,24)).filter(v->!v.isBlank()).distinct().toList();if(tags.size()>8)throw SchoolAccounts.error(400,"最多 8 个标签 / Up to 8 tags");var p=new Profile(n,clean(input.nickname(),60),student?clean(input.grade(),30):"",student?clean(input.classroom(),30):"",tags,clean(input.bio(),600));String key=SchoolAccounts.key(email);Profile previous=profiles.put(key,p);try{persist();}catch(RuntimeException e){if(previous==null)profiles.remove(key);else profiles.put(key,previous);throw e;}return p;}
 public synchronized void removeAccount(String id){profiles.remove(id);persist();}
}
