package com.qpwflshclub.formal_club.social;
import com.qpwflshclub.formal_club.config.*;import com.qpwflshclub.formal_club.pojo.User.*;import com.qpwflshclub.formal_club.repository.User.*;import com.qpwflshclub.formal_club.repository.Club.ClubRepository;import com.qpwflshclub.formal_club.repository.Suggestion.SuggestionRepository;import com.qpwflshclub.formal_club.workspace.*;
import org.springframework.web.bind.annotation.*;import org.springframework.beans.factory.annotation.*;import org.springframework.http.ResponseEntity;import org.springframework.transaction.support.TransactionTemplate;import jakarta.servlet.http.*;import java.util.*;import java.io.IOException;import java.net.*;import java.net.http.*;import java.time.Duration;
@RestController public class AccountDeletionController {
 @Autowired SchoolAccounts accounts;@Autowired WorkspaceAccess access;@Autowired UserRepository students;@Autowired TeacherRepository teachers;@Autowired ClubPresidentRepository presidents;@Autowired AdminRepository admins;@Autowired ClubRepository clubs;@Autowired SuggestionRepository suggestions;@Autowired CommunityController community;@Autowired SocialStore social;@Autowired AvatarStore avatars;@Autowired ProfileAppearance appearance;@Autowired AccountProfiles profiles;@Autowired PersonalCalendarStore calendar;@Autowired MessageKeys keys;@Autowired MessageRecovery recovery;@Autowired MessageKeyBackupRepository backups;@Autowired ChatPreferences preferences;@Autowired PostPins pins;@Autowired PostViews views;@Autowired SocialNotifications notifications;@Autowired OfficerAssignments officers;@Autowired TeacherDayGifts gifts;@Autowired ContentAudit audit;@Autowired WallFiles files;@Autowired JoinRequests joins;@Autowired WorkspaceStore workspace;@Autowired ClubOperationsStore operations;@Autowired LoginEmails logins;@Autowired SessionRevocations sessions;@Autowired TransactionTemplate transaction;
 @Value("${club.booking.url:http://localhost:8765/}") String bookingUrl;
 public record Input(String password,String confirmation){}
 @GetMapping("/booking/deletion-authorization") public ResponseEntity<?> authorize(HttpServletRequest r){var session=r.getSession(false);String proof=r.getHeader("X-Account-Deletion-Proof");if(session==null||proof==null||!(session.getAttribute("accountDeletionProof") instanceof String expected)||!java.security.MessageDigest.isEqual(proof.getBytes(java.nio.charset.StandardCharsets.UTF_8),expected.getBytes(java.nio.charset.StandardCharsets.UTF_8)))throw SchoolAccounts.error(403,"Deletion authorization required");var u=accounts.current(r);return ResponseEntity.ok().header("Cache-Control","no-store").body(Map.of("email",u.getEmail()));}
 private void bookings(HttpServletRequest r)throws IOException{String proof=UUID.randomUUID().toString();var session=r.getSession();session.setAttribute("accountDeletionProof",proof);try{URI target=URI.create(bookingUrl.endsWith("/")?bookingUrl:bookingUrl+"/").resolve("delete_account.php");var call=HttpRequest.newBuilder(target).timeout(Duration.ofSeconds(20)).header("Cookie","JSESSIONID="+session.getId()).header("X-Account-Deletion-Proof",proof).POST(HttpRequest.BodyPublishers.noBody()).build();var result=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(5)).build().send(call,HttpResponse.BodyHandlers.ofString());if(result.statusCode()!=200||!result.body().contains("\"deleted\":true"))throw new IOException("Booking cleanup unavailable");}catch(InterruptedException e){Thread.currentThread().interrupt();throw new IOException(e);}finally{session.removeAttribute("accountDeletionProof");}}
 @DeleteMapping("/api/campus-social/me/account") public synchronized Object delete(@RequestBody Input input,HttpServletRequest r)throws IOException{var me=accounts.current(r);access.mutation(r);if(!"DELETE".equals(input.confirmation())||!PasswordCodec.matches(me.getPassword(),input.password()))throw SchoolAccounts.error(403,"请确认注销并填写正确的当前密码 / Confirm deletion and enter your current password");String email=me.getEmail(),id=SchoolAccounts.key(email);bookings(r);
  var identities=new ArrayList<UserBase>();var student=students.findByEmail(email);if(student!=null)identities.add(student);var teacher=teachers.findByEmail(email);if(teacher!=null)identities.add(teacher);var president=presidents.findByEmail(email);if(president!=null)identities.add(president);var admin=admins.findByAdminEmail(email);if(admin!=null)identities.add(admin);Set<Integer> teacherClubs=new HashSet<>();if(teacher!=null&&teacher.getClubs()!=null)teacher.getClubs().forEach(c->teacherClubs.add(c.getId()));Set<Integer> affected=new HashSet<>();for(var office:officers.forAccount(id))affected.add(office.club());if(president!=null&&president.getMainClub()!=null)affected.add(president.getMainClub().getId());Set<Long> studentIds=student==null?Set.of():Set.of(student.getId());Set<String> memberIds=new HashSet<>();for(var u:identities)memberIds.add((u instanceof Teacher?"teacher":u instanceof ClubPresident?"president":u instanceof Admin?"admin":"student")+":"+u.getId());
  var snapshot=social.snapshot();Set<String> postIds=new HashSet<>();for(var post:snapshot.posts())if(post.author().equals(id)){postIds.add(post.id());for(var attachment:post.attachments())files.remove(attachment.id());}social.removeAccount(id);for(String post:postIds)pins.remove(post);views.removeAccount(id,postIds);notifications.removeAccount(id,postIds);preferences.removeAccount(id);calendar.removeAccount(id);avatars.remove(id);appearance.removeAccount(id);profiles.removeAccount(id);gifts.removeAccount(id);
  Set<Long> suggestionIds=new HashSet<>();for(String value:audit.owned(id,"suggestion"))try{suggestionIds.add(Long.parseLong(value));}catch(NumberFormatException ignored){}
  var allClubs=clubs.findAll();for(var club:allClubs){joins.removeAccount(club.getId(),id);workspace.removeAccount(club.getId(),email);operations.removeAccount(club.getId(),email,id,studentIds,memberIds);}officers.removeAccount(id);audit.removeAccount(id);recovery.remove(id);keys.removeAccount(id);logins.removeAccount(email);
  transaction.executeWithoutResult(status->{for(Long suggestion:suggestionIds)suggestions.deleteById(suggestion);backups.deleteById(id);for(var u:identities){u.setClubs(new ArrayList<>());if(u instanceof ClubPresident v){v.setMainClub(null);presidents.save(v);presidents.delete(v);}else if(u instanceof Teacher v){teachers.save(v);teachers.delete(v);}else if(u instanceof Admin v){admins.save(v);admins.delete(v);}else if(u instanceof User v){students.save(v);students.delete(v);}}});accounts.invalidateDirectory();for(var club:allClubs){if(affected.contains(club.getId()))community.syncLeaderLabels(club.getId());if(teacherClubs.contains(club.getId())){var advisers=java.util.stream.StreamSupport.stream(teachers.findAll().spliterator(),false).filter(t->t.getClubs()!=null&&t.getClubs().stream().anyMatch(c->c.getId()==club.getId())).toList();club.setTeacher(advisers.stream().map(Teacher::getUsername).collect(java.util.stream.Collectors.joining("、")));club.setTeacherEn(advisers.stream().map(t->Objects.toString(t.getUsernameEn(),"")).collect(java.util.stream.Collectors.joining(", ")));clubs.save(club);}}
  sessions.revoke(email);r.getSession().invalidate();return Map.of("deleted",true);
 }
}
