package com.qpwflshclub.formal_club.social;
import com.qpwflshclub.formal_club.pojo.User.*;
import com.qpwflshclub.formal_club.pojo.Club.Club;
import com.qpwflshclub.formal_club.repository.User.*;
import com.qpwflshclub.formal_club.repository.Club.ClubRepository;
import com.qpwflshclub.formal_club.workspace.*;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.server.ResponseStatusException;
import org.springframework.transaction.annotation.Transactional;
import jakarta.servlet.http.HttpServletRequest;
import java.util.*;
import java.io.IOException;

@RestController @RequestMapping("/api/campus-social")
public class CommunityController {
 @org.springframework.beans.factory.annotation.Autowired private ProfileAppearance appearance;
 private final SchoolAccounts accounts;private final WorkspaceAccess access;private final MessageKeys keys;private final WorkspaceStore workspace;private final ClubRepository clubs;private final UserRepository students;private final TeacherRepository teachers;private final ClubPresidentRepository presidents;private final AdminRepository admins;
 public CommunityController(SchoolAccounts a,WorkspaceAccess w,MessageKeys k,WorkspaceStore s,ClubRepository c,UserRepository u,TeacherRepository t,ClubPresidentRepository p,AdminRepository d){accounts=a;access=w;keys=k;workspace=s;clubs=c;students=u;teachers=t;presidents=p;admins=d;}
 @org.springframework.beans.factory.annotation.Autowired private AccountProfiles profiles;
 @org.springframework.beans.factory.annotation.Autowired private MessageKeyVault vault;
 @org.springframework.beans.factory.annotation.Autowired private com.qpwflshclub.formal_club.config.LoginEmails loginEmails;
 @org.springframework.beans.factory.annotation.Autowired private OfficerAssignments officers;
 private UserBase current(HttpServletRequest r,boolean write){var u=accounts.current(r);if(write)access.mutation(r);return u;}
 @org.springframework.beans.factory.annotation.Autowired private MessageRecovery recovery;
 @GetMapping("/keys/recovery") public Object recovery(HttpServletRequest r,jakarta.servlet.http.HttpServletResponse response)throws IOException{response.setHeader("Cache-Control","no-store");var identity=recovery.get(SchoolAccounts.key(current(r,false).getEmail()));return identity==null?Map.of("ready",false):Map.of("ready",true,"publicKey",identity.publicKey(),"privateKey",identity.privateKey());}
 @PutMapping("/keys/recovery") public Object recovery(@RequestBody MessageRecovery.Identity input,HttpServletRequest r)throws IOException{recovery.save(SchoolAccounts.key(current(r,true).getEmail()),input);return Map.of("ok",true);}
 public record ProvisionInput(String account){}
 @PostMapping("/keys/provision") public Object provision(@RequestBody ProvisionInput input,HttpServletRequest r)throws IOException{current(r,true);accounts.find(input.account());var key=recovery.provision(input.account());return Map.of("ready",true,"publicKey",key.publicKey(),"fingerprint",key.fingerprint());}
 public record BackupInput(String envelope){}
 @GetMapping("/keys/backup") public Object backup(HttpServletRequest r){return Map.of("envelope",vault.get(SchoolAccounts.key(current(r,false).getEmail())));}
 @PutMapping("/keys/backup") public Object backup(@RequestBody BackupInput input,HttpServletRequest r){vault.create(SchoolAccounts.key(current(r,true).getEmail()),input.envelope());return Map.of("ok",true);}
 @GetMapping("/keys/{id}") public Object key(@PathVariable String id,HttpServletRequest r)throws IOException{current(r,false);accounts.find(id);var key=keys.get(id);return key==null?Map.of("ready",false):Map.of("ready",true,"publicKey",key.publicKey(),"fingerprint",key.fingerprint());}
 public record KeyInput(String publicKey){}
 @PutMapping("/keys") public Object key(@RequestBody KeyInput input,HttpServletRequest r)throws IOException{return keys.register(SchoolAccounts.key(current(r,true).getEmail()),input.publicKey());}
 @GetMapping("/me") public Object me(HttpServletRequest r){var u=current(r,false);return Map.of("account",accounts.view(u),"email",loginEmails==null?u.getEmail():loginEmails.display(u.getEmail()),"token",access.token(r),"details",profiles.get(u.getEmail()),"offices",offices(u));}
 public record ProfileInput(String name,String nameEn){} public record PasswordInput(String currentPassword,String newPassword,String keyEnvelope){public PasswordInput(String currentPassword,String newPassword){this(currentPassword,newPassword,null);}}
 private List<UserBase> identities(String email){List<UserBase> list=new ArrayList<>();var student=students.findByEmail(email);if(student!=null)list.add(student);var teacher=teachers.findByEmail(email);if(teacher!=null)list.add(teacher);var president=presidents.findByEmail(email);if(president!=null)list.add(president);var admin=admins.findByAdminEmail(email);if(admin!=null)list.add(admin);return list;}
 private void save(UserBase u){if(u instanceof User x)students.save(x);else if(u instanceof Teacher x)teachers.save(x);else if(u instanceof ClubPresident x)presidents.save(x);else if(u instanceof Admin x)admins.save(x);}
 @PutMapping("/me") @Transactional public Object profile(@RequestBody ProfileInput input,HttpServletRequest r){var u=current(r,true);com.qpwflshclub.formal_club.config.RegistrationNames.validate(input.name(),input.nameEn());String name=input.name()==null?"":input.name().strip(),en=input.nameEn()==null?"":input.nameEn().strip();for(var identity:identities(u.getEmail())){identity.setUsername(name);identity.setUsernameEn(en);save(identity);if(identity instanceof ClubPresident p&&p.getMainClub()!=null){var c=p.getMainClub();if(p.isVicePresident()){c.setVicePresident(name);c.setVicePresidentEn(en);}else{c.setPresident(name);c.setPresidentEn(en);}clubs.save(c);}if(identity instanceof Teacher t&&t.getClubs()!=null){for(var c:t.getClubs()){var advisers=java.util.stream.StreamSupport.stream(teachers.findAll().spliterator(),false).filter(v->v.getClubs()!=null&&v.getClubs().stream().anyMatch(vv->Objects.equals(vv.getId(),c.getId()))).toList();c.setTeacher(advisers.stream().map(Teacher::getUsername).collect(java.util.stream.Collectors.joining("、")));c.setTeacherEn(advisers.stream().map(Teacher::getUsernameEn).collect(java.util.stream.Collectors.joining(", ")));clubs.save(c);}}}if(u instanceof ClubPresident||u instanceof User)for(var c:access.clubs(u))syncLeaderLabels(c.getId());accounts.invalidateDirectory();return Map.of("ok",true);}
 @PutMapping("/me/password") @Transactional public Object password(@RequestBody PasswordInput input,HttpServletRequest r){var u=current(r,true);if(!com.qpwflshclub.formal_club.config.PasswordCodec.matches(u.getPassword(),input.currentPassword()))throw SchoolAccounts.error(403,"当前密码不正确");String password=input.newPassword();com.qpwflshclub.formal_club.config.PasswordPolicy.require(password);String id=SchoolAccounts.key(u.getEmail());if(vault!=null){if(input.keyEnvelope()!=null&&!input.keyEnvelope().isBlank())vault.replace(id,input.keyEnvelope());else if(!vault.get(id).isBlank())throw SchoolAccounts.error(400,"请在个人资料页面更新密码以同步加密私信 / Change your password in Profile to keep messages in sync");}for(var identity:identities(u.getEmail())){identity.setPassword(com.qpwflshclub.formal_club.config.PasswordCodec.encode(password));save(identity);}return Map.of("ok",true);}
 @GetMapping("/me/clubs") public Object mine(HttpServletRequest r){var u=current(r,false);Map<Integer,Map<String,Object>> result=new LinkedHashMap<>();for(var identity:identities(u.getEmail())){if(identity.getClubs()!=null)for(var c:identity.getClubs())result.put(c.getId(),club(c,identity instanceof Teacher?"指导教师":"社员"));if(identity instanceof ClubPresident cp&&cp.getMainClub()!=null)result.put(cp.getMainClub().getId(),club(cp.getMainClub(),cp.isVicePresident()?"副社长":"社长"));}if(officers!=null)for(var o:officers.forAccount(SchoolAccounts.key(u.getEmail())))clubs.findById(o.club()).ifPresent(c->result.put(c.getId(),club(c,o.position().equals("vice_president")?"副社长":"社长")));return result.values();}
 public List<Club> memberClubs(UserBase user){Map<Integer,Club> result=new LinkedHashMap<>();for(var identity:identities(user.getEmail())){if(identity.getClubs()!=null)for(var club:identity.getClubs())result.put(club.getId(),club);if(identity instanceof ClubPresident p&&p.getMainClub()!=null)result.put(p.getMainClub().getId(),p.getMainClub());}if(officers!=null)for(var o:officers.forAccount(SchoolAccounts.key(user.getEmail())))clubs.findById(o.club()).ifPresent(c->result.put(c.getId(),c));return List.copyOf(result.values());}
 @GetMapping("/clubs/{id}/leaders") public Map<String,List<SchoolAccounts.Account>> leaders(@PathVariable int id){if(!clubs.existsById(id))throw SchoolAccounts.error(404,"社团不存在");List<SchoolAccounts.Account> president=new ArrayList<>(),vice=new ArrayList<>(),advisers=new ArrayList<>();for(var p:presidents.findAll())if(p.getMainClub()!=null&&p.getMainClub().getId()==id&&OfficerAssignments.named(p))(p.isVicePresident()?vice:president).add(accounts.view(p));for(var t:teachers.findAll())if(t.getClubs()!=null&&t.getClubs().stream().anyMatch(c->c.getId()==id))advisers.add(accounts.view(t));if(officers!=null)for(var office:officers.all())if(office.club()==id){var u=accounts.find(office.account());if(OfficerAssignments.named(u)){var a=accounts.view(u);var c=clubs.findById(id).orElseThrow();var scoped=new SchoolAccounts.Account(a.id(),a.name(),a.nameEn(),"president",a.avatarUrl(),a.nickname(),office.position(),c.getClubName(),c.getClubNameEn(),a.grade(),a.avatarFrame(),a.badges(),a.appearance());var list=office.position().equals("vice_president")?vice:president;if(list.stream().noneMatch(v->v.id().equals(a.id())))list.add(scoped);}}return Map.of("president",president,"vice_president",vice,"teacher",advisers);}
 private Map<String,Object> club(Club c,String role){return Map.of("id",c.getId(),"name",Objects.toString(c.getClubName(),""),"slug",Objects.toString(c.getClubNameEn(),""),"nameEn",Objects.toString(c.getClubNameEn(),""),"sloganEn",Objects.toString(c.getSortDescriptionEn(),""),"descriptionEn",Objects.toString(c.getClubDescriptionEn(),""),"slogan",Objects.toString(c.getSortDescription(),""),"description",Objects.toString(c.getClubDescription(),""),"role",role);}
 @GetMapping("/clubs/{id}/contact") public Object contact(@PathVariable int id,HttpServletRequest r){current(r,false);var team=leaders(id).get("president");if(!team.isEmpty())return team.getFirst();throw SchoolAccounts.error(404,"该社团尚未绑定社长账号 / No president account is linked yet");}
 @DeleteMapping("/me/clubs/{id}") @Transactional public Object leave(@PathVariable int id,HttpServletRequest r)throws IOException{var me=current(r,true);if(!(me instanceof User||me instanceof Teacher||me instanceof ClubPresident||me instanceof Admin))throw SchoolAccounts.error(403,"此账号不能退社");var club=clubs.findById(id).orElseThrow(()->SchoolAccounts.error(404,"社团不存在"));boolean changed=officers!=null&&officers.remove(SchoolAccounts.key(me.getEmail()),id);
  for(var u:identities(me.getEmail())){var owned=u.getClubs()==null?new ArrayList<Club>():new ArrayList<>(u.getClubs());boolean member=owned.removeIf(c->c.getId()==id);if(member){u.setClubs(owned);changed=true;}
   if(u instanceof ClubPresident p&&p.getMainClub()!=null&&p.getMainClub().getId()==id){if(p.isVicePresident()){club.setVicePresident("");club.setVicePresidentEn("");}else{club.setPresident("");club.setPresidentEn("");}p.setMainClub(null);changed=true;member=true;}
   if(member)save(u);
  }
  if(!changed)throw SchoolAccounts.error(409,"你不在这个社团 / You are not a member of this club");
  if(me instanceof Teacher){StringJoiner names=new StringJoiner("、"),english=new StringJoiner(", ");for(var t:teachers.findAll())if(t.getClubs()!=null&&t.getClubs().stream().anyMatch(c->c.getId()==id)){names.add(t.getUsername());english.add(t.getUsernameEn());}club.setTeacher(names.toString());club.setTeacherEn(english.toString());}
  clubs.save(club);if(officers!=null)syncLeaderLabels(id);return Map.of("ok",true);
 }
 @PutMapping("/me/details") public Object details(@RequestBody AccountProfiles.Profile input,HttpServletRequest request){var user=current(request,true);var updated=profiles.update(user.getEmail(),input,user instanceof User||user instanceof ClubPresident||user instanceof Admin);accounts.invalidateDirectory();return updated;}
 @GetMapping("/users/{id}/profile") public Object publicProfile(@PathVariable String id,HttpServletRequest request){current(request,false);var user=accounts.find(id);var info=profiles.get(user.getEmail());return Map.of("account",accounts.view(user),"tags",appearance==null||appearance.get(id).tags()==null?info.tags():info.tags().stream().filter(appearance.get(id).tags()::contains).toList(),"bio",info.bio(),"offices",offices(user));}
 private List<Map<String,Object>> offices(UserBase user){List<Map<String,Object>> result=new ArrayList<>();if(user instanceof ClubPresident p&&p.getMainClub()!=null)result.add(club(p.getMainClub(),p.isVicePresident()?"副社长":"社长"));if(officers!=null)for(var o:officers.forAccount(SchoolAccounts.key(user.getEmail())))clubs.findById(o.club()).ifPresent(c->result.add(club(c,o.position().equals("vice_president")?"副社长":"社长")));return result;}
 public void syncLeaderLabels(int id){var c=clubs.findById(id).orElseThrow();var team=leaders(id);c.setPresident(team.get("president").stream().map(SchoolAccounts.Account::name).collect(java.util.stream.Collectors.joining("、")));c.setPresidentEn(team.get("president").stream().map(SchoolAccounts.Account::nameEn).collect(java.util.stream.Collectors.joining(", ")));c.setVicePresident(team.get("vice_president").stream().map(SchoolAccounts.Account::name).collect(java.util.stream.Collectors.joining("、")));c.setVicePresidentEn(team.get("vice_president").stream().map(SchoolAccounts.Account::nameEn).collect(java.util.stream.Collectors.joining(", ")));clubs.save(c);}
 public record OfficeInput(String position){}
 @PutMapping("/clubs/{id}/officers/{account}") public Object assignOffice(@PathVariable int id,@PathVariable String account,@RequestBody OfficeInput input,HttpServletRequest request)throws IOException{var actor=current(request,true);if(!(actor instanceof Admin))throw SchoolAccounts.error(403,"仅管理员可直接任命负责人");clubs.findById(id).orElseThrow(()->SchoolAccounts.error(404,"社团不存在"));var user=accounts.find(account);if(!(user instanceof User||user instanceof ClubPresident))throw SchoolAccounts.error(400,"请选择学生账号");if(user instanceof ClubPresident p&&p.getMainClub()!=null&&p.getMainClub().getId()==id)throw SchoolAccounts.error(409,"该账号已在此社团任职，请调整原职务");officers.assign(account,id,input.position());syncLeaderLabels(id);accounts.invalidateDirectory();return Map.of("ok",true,"offices",offices(user));}
 @DeleteMapping("/clubs/{id}/officers/{account}") @Transactional public Object removeVice(@PathVariable int id,@PathVariable String account,HttpServletRequest request)throws IOException{
  var actor=current(request,true);String me=SchoolAccounts.key(actor.getEmail());boolean president=offices(actor).stream().anyMatch(o->Objects.equals(o.get("id"),id)&&Objects.equals(o.get("role"),"社长"));if(!(actor instanceof Admin)&&!president)throw SchoolAccounts.error(403,"仅本社团社长可以移除副社长 / Only this club's president may remove a vice president");
  if(me.equals(account))throw SchoolAccounts.error(400,"请使用卸任功能 / Use Resign for your own role");var target=accounts.find(account);if(offices(target).stream().noneMatch(o->Objects.equals(o.get("id"),id)&&Objects.equals(o.get("role"),"副社长")))throw SchoolAccounts.error(403,"只能移除本社团副社长 / Only this club's vice president can be removed");
  var club=clubs.findById(id).orElseThrow();if(officers!=null)officers.remove(account,id);
  if(target instanceof ClubPresident p&&p.getMainClub()!=null&&p.getMainClub().getId()==id){if(!p.isVicePresident())throw SchoolAccounts.error(403,"不能移除社长 / Cannot remove a president");p.setMainClub(null);}
  var membership=new ArrayList<>(target.getClubs()==null?List.<Club>of():target.getClubs());if(membership.stream().noneMatch(c->c.getId()==id))membership.add(club);target.setClubs(membership);save(target);syncLeaderLabels(id);accounts.invalidateDirectory();return Map.of("ok",true);
 }
 public record ResignInput(String confirmation,Integer club){public ResignInput(String confirmation){this(confirmation,null);}}
 @PostMapping("/me/resign") @Transactional public Object resign(@RequestBody ResignInput input,HttpServletRequest request)throws IOException{var current=current(request,true);
 if(!"RESIGN".equals(input.confirmation()))throw SchoolAccounts.error(400,"请再次确认卸任 / Confirm resignation");
 if(input.club()!=null&&officers!=null&&officers.forAccount(SchoolAccounts.key(current.getEmail())).stream().anyMatch(o->o.club()==input.club())){
  var club=clubs.findById(input.club()).orElseThrow(()->SchoolAccounts.error(404,"社团不存在"));var membership=new ArrayList<>(current.getClubs()==null?List.<Club>of():current.getClubs());if(membership.stream().noneMatch(c->c.getId()==club.getId()))membership.add(club);current.setClubs(membership);save(current);officers.remove(SchoolAccounts.key(current.getEmail()),input.club());syncLeaderLabels(input.club());accounts.invalidateDirectory();return Map.of("ok",true,"offices",offices(current));
 }
 if(input.club()!=null&&(!(current instanceof ClubPresident cp)||cp.getMainClub()==null||!Objects.equals(cp.getMainClub().getId(),input.club())))throw SchoolAccounts.error(403,"你没有该社团职务");if(!(current instanceof ClubPresident p))throw SchoolAccounts.error(403,"此账户没有社长职务");if(!"RESIGN".equals(input.confirmation()))throw SchoolAccounts.error(400,"请再次确认卸任 / Confirm resignation");var student=students.findByEmail(p.getEmail());if(student==null){student=new User();student.setEmail(p.getEmail());student.setUsername(p.getUsername());student.setUsernameEn(p.getUsernameEn());student.setPassword(p.getPassword());}Map<Integer,Club> membership=new LinkedHashMap<>();if(student.getClubs()!=null)for(var c:student.getClubs())membership.put(c.getId(),c);if(p.getClubs()!=null)for(var c:p.getClubs())membership.put(c.getId(),c);var main=p.getMainClub();if(main!=null)membership.put(main.getId(),main);student.setClubs(new ArrayList<>(membership.values()));students.save(student);p.setClubs(new ArrayList<>());p.setMainClub(null);presidents.save(p);presidents.delete(p);if(main!=null){var team=java.util.stream.StreamSupport.stream(presidents.findAll().spliterator(),false).filter(v->v.getMainClub()!=null&&Objects.equals(v.getMainClub().getId(),main.getId())&&!v.getEmail().equals(p.getEmail())).toList();main.setPresident(team.stream().filter(v->!v.isVicePresident()).map(ClubPresident::getUsername).collect(java.util.stream.Collectors.joining("、")));main.setPresidentEn(team.stream().filter(v->!v.isVicePresident()).map(ClubPresident::getUsernameEn).collect(java.util.stream.Collectors.joining(", ")));main.setVicePresident(team.stream().filter(ClubPresident::isVicePresident).map(ClubPresident::getUsername).collect(java.util.stream.Collectors.joining("、")));main.setVicePresidentEn(team.stream().filter(ClubPresident::isVicePresident).map(ClubPresident::getUsernameEn).collect(java.util.stream.Collectors.joining(", ")));clubs.save(main);}if(main!=null&&officers!=null)syncLeaderLabels(main.getId());accounts.invalidateDirectory();return Map.of("ok",true,"offices",offices(student));}
 @GetMapping("/events") public Object events(HttpServletRequest r)throws IOException{current(r,false);List<Map<String,Object>> result=new ArrayList<>();for(var c:clubs.findAll())for(var a:workspace.read(c.getId()).activities())if("application".equals(a.kind())&&"approved".equals(a.status()))result.add(Map.of("id",c.getId()+":"+a.id(),"club",c.getClubName(),"clubId",c.getId(),"title",a.title(),"start",a.start(),"end",a.end(),"location",a.location(),"description",a.description()));result.sort(Comparator.comparing(e->e.get("start").toString()));return result;}
 @ExceptionHandler(ResponseStatusException.class) public ResponseEntity<?> error(ResponseStatusException e){return ResponseEntity.status(e.getStatusCode()).body(Map.of("message",Objects.toString(e.getReason(),"请求未成功")));}
 @ExceptionHandler(IOException.class) public ResponseEntity<?> io(IOException e){return ResponseEntity.internalServerError().body(Map.of("message","存储暂时不可用，请稍后重试"));}
}
