package com.qpwflshclub.formal_club.social;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Value;
import javax.crypto.*;import javax.crypto.spec.*;import java.security.*;import java.security.spec.*;import java.nio.file.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.io.IOException;
/** Recovery keys are encrypted at rest with a host secret, independently of login passwords. */
@Service public class MessageRecovery {
 public record Identity(String publicKey,String privateKey){}
 private final Path root;private final ObjectMapper json;private final MessageKeys keys;
 public MessageRecovery(ObjectMapper json,MessageKeys keys,@Value("${club.social-dir:./data/campus-social}")String dir){this.json=json;this.keys=keys;root=Path.of(dir).toAbsolutePath().resolve("recovery");}
 private Path file(String id){if(!id.matches("[a-f0-9]{64}"))throw SchoolAccounts.error(400,"Invalid account");return root.resolve(id+".enc");}
 private byte[] master()throws IOException{Files.createDirectories(root);Files.setPosixFilePermissions(root,java.nio.file.attribute.PosixFilePermissions.fromString("rwx------"));Path f=root.resolve("master.key");if(!Files.exists(f)){byte[] secret=new byte[32];new SecureRandom().nextBytes(secret);try{Files.write(f,secret,StandardOpenOption.CREATE_NEW);Files.setPosixFilePermissions(f,java.nio.file.attribute.PosixFilePermissions.fromString("rw-------"));}catch(FileAlreadyExistsException ignored){}}byte[] value=Files.readAllBytes(f);if(value.length!=32)throw new IOException("Invalid recovery master key");return value;}
 private byte[] crypt(int mode,String id,byte[] iv,byte[] bytes)throws Exception{Cipher cipher=Cipher.getInstance("AES/GCM/NoPadding");cipher.init(mode,new SecretKeySpec(master(),"AES"),new GCMParameterSpec(128,iv));cipher.updateAAD(id.getBytes(StandardCharsets.UTF_8));return cipher.doFinal(bytes);}
 public synchronized Identity get(String id)throws IOException{Path f=file(id);if(!Files.exists(f))return null;try{byte[] raw=Files.readAllBytes(f);return json.readValue(crypt(Cipher.DECRYPT_MODE,id,Arrays.copyOf(raw,12),Arrays.copyOfRange(raw,12,raw.length)),Identity.class);}catch(Exception e){throw new IOException("Recovery key unavailable",e);}}
 private void validate(Identity own){try{if(own==null||own.privateKey()==null||own.privateKey().length()>1000||own.publicKey()==null||own.publicKey().length()>300)throw new IllegalArgumentException();KeyFactory factory=KeyFactory.getInstance("EC");var pub=factory.generatePublic(new X509EncodedKeySpec(Base64.getDecoder().decode(own.publicKey())));var priv=factory.generatePrivate(new PKCS8EncodedKeySpec(Base64.getDecoder().decode(own.privateKey())));var gen=KeyPairGenerator.getInstance("EC");gen.initialize(new ECGenParameterSpec("secp256r1"));var probe=gen.generateKeyPair();var a=KeyAgreement.getInstance("ECDH");a.init(priv);a.doPhase(probe.getPublic(),true);var b=KeyAgreement.getInstance("ECDH");b.init(probe.getPrivate());b.doPhase(pub,true);if(!MessageDigest.isEqual(a.generateSecret(),b.generateSecret()))throw new IllegalArgumentException();}catch(Exception e){throw SchoolAccounts.error(400,"恢复密钥不匹配 / Invalid recovery key pair");}}
 public synchronized void save(String id,Identity own)throws IOException{validate(own);var old=keys.get(id);if(old!=null&&!old.publicKey().equals(own.publicKey()))throw SchoolAccounts.error(409,"请保留原聊天密钥 / Keep the original message key");if(get(id)!=null)return;try{byte[] iv=new byte[12];new SecureRandom().nextBytes(iv);byte[] sealed=crypt(Cipher.ENCRYPT_MODE,id,iv,json.writeValueAsBytes(own));Path tmp=Files.createTempFile(root,"recovery-",".tmp");try{Files.setPosixFilePermissions(tmp,java.nio.file.attribute.PosixFilePermissions.fromString("rw-------"));byte[] all=new byte[12+sealed.length];System.arraycopy(iv,0,all,0,12);System.arraycopy(sealed,0,all,12,sealed.length);Files.write(tmp,all);keys.register(id,own.publicKey());Files.move(tmp,file(id),StandardCopyOption.ATOMIC_MOVE,StandardCopyOption.REPLACE_EXISTING);}finally{Files.deleteIfExists(tmp);}}catch(IOException e){throw e;}catch(Exception e){throw new IOException("Recovery key storage unavailable",e);}}
 public synchronized MessageKeys.PublicKeyInfo provision(String id)throws IOException{var existing=keys.get(id);if(existing!=null)return existing;try{var generator=KeyPairGenerator.getInstance("EC");generator.initialize(new ECGenParameterSpec("secp256r1"));var pair=generator.generateKeyPair();save(id,new Identity(Base64.getEncoder().encodeToString(pair.getPublic().getEncoded()),Base64.getEncoder().encodeToString(pair.getPrivate().getEncoded())));return keys.get(id);}catch(IOException e){throw e;}catch(Exception e){throw new IOException("Unable to initialize messaging",e);}}
 public synchronized void remove(String id)throws IOException{Files.deleteIfExists(file(id));}
}
