package com.qpwflshclub.formal_club.social;
import com.qpwflshclub.formal_club.config.*;
import com.qpwflshclub.formal_club.repository.User.*;
import com.qpwflshclub.formal_club.service.User.IUserService;
import com.qpwflshclub.formal_club.service.Suggestion.MailService;
import jakarta.servlet.http.*;import jakarta.validation.Valid;import jakarta.validation.constraints.*;
import org.springframework.beans.factory.annotation.Value;import org.springframework.web.bind.annotation.*;import org.springframework.transaction.annotation.Transactional;
import java.util.*;import java.util.concurrent.*;import java.security.*;import java.nio.charset.StandardCharsets;

@RestController @RequestMapping("/api/user/password-reset")
public class PasswordRecoveryController {
 private final LoginEmails emails;private final IUserService users;private final UserRepository students;private final TeacherRepository teachers;private final ClubPresidentRepository presidents;private final AdminRepository admins;private final MailService mail;private final SessionRevocations sessions;private final MessageKeyVault vault;
 @Value("${spring.mail.host:}") private String host;@Value("${spring.mail.port:465}") private int port;@Value("${spring.mail.username:}") private String username;@Value("${spring.mail.password:}") private String password;
 private static final String KEY="passwordRecovery";private final SecureRandom random=new SecureRandom();
 private final Map<String,Deque<Long>> rates=new HashMap<>();
 private final ExecutorService delivery=new ThreadPoolExecutor(2,2,0L,TimeUnit.MILLISECONDS,new ArrayBlockingQueue<>(100),r->{Thread t=new Thread(r,"password-recovery-mail");t.setDaemon(true);return t;});
 record Challenge(String login,String canonical,String version,String digest,long expires,int attempts,boolean verified){}
 public record EmailInput(@NotBlank @Email @Size(max=254)String email){}
 public record CodeInput(@NotBlank @Email @Size(max=254)String email,@NotBlank @Pattern(regexp="[0-9]{6}")String code){}
 public record PasswordInput(@NotBlank @Size(max=128)String password,String keyEnvelope){}
 public PasswordRecoveryController(LoginEmails e,IUserService u,UserRepository s,TeacherRepository t,ClubPresidentRepository p,AdminRepository a,MailService m,SessionRevocations r,MessageKeyVault v){emails=e;users=u;students=s;teachers=t;presidents=p;admins=a;mail=m;sessions=r;vault=v;}
 private static String hash(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
 private void origin(HttpServletRequest r){String origin=r.getHeader("Origin");if("cross-site".equals(r.getHeader("Sec-Fetch-Site"))||(origin!=null&&!origin.equals(r.getScheme()+"://"+r.getServerName()+((r.getServerPort()==443&&r.isSecure()||r.getServerPort()==80&&!r.isSecure())?"":":"+r.getServerPort()))))throw SchoolAccounts.error(403,"请求来源无效 / Invalid request origin");}
 private synchronized void limit(String email,String ip){long now=System.currentTimeMillis();rates.values().forEach(q->q.removeIf(v->v<now-3600000));rates.values().removeIf(Deque::isEmpty);if(rates.size()>20000)throw SchoolAccounts.error(429,"请稍后再试 / Please try again later");for(String k:List.of("e:"+email,"i:"+ip)){var q=rates.getOrDefault(k,new ArrayDeque<>());if(q.size()>=(k.startsWith("e:")?5:20)||(k.startsWith("e:")&&!q.isEmpty()&&q.getLast()>now-60000))throw SchoolAccounts.error(429,"发送过于频繁，请稍后再试 / Too many requests. Please try again later");}for(String k:List.of("e:"+email,"i:"+ip))rates.computeIfAbsent(k,v->new ArrayDeque<>()).add(now);}
 @PostMapping("/code") public Object code(@Valid @RequestBody EmailInput body,HttpServletRequest r){origin(r);String login=LoginEmails.normalize(body.email());limit(login,r.getRemoteAddr());String canonical=emails.resolve(login);var user=canonical==null?null:users.findByEmail(canonical);String code=String.format(Locale.ROOT,"%06d",random.nextInt(1000000));var session=r.getSession();synchronized(session){session.setAttribute(KEY,new Challenge(login,user==null?null:canonical,user==null?"":user.getPassword(),hash(code),System.currentTimeMillis()+300000,0,false));}boolean english=Arrays.stream(Optional.ofNullable(r.getCookies()).orElse(new Cookie[0])).anyMatch(c->c.getName().equals("club_language")&&c.getValue().equals("en"));try{delivery.execute(()->{if(user==null)return;try{mail.sendRecoveryCode(host,port,username,password,login,code,english);}catch(Exception e){org.slf4j.LoggerFactory.getLogger(getClass()).warn("Password recovery mail delivery failed: {}",e.getClass().getSimpleName());}});}catch(RejectedExecutionException e){session.removeAttribute(KEY);throw SchoolAccounts.error(503,"请稍后再试 / Please try again later");}return Map.of("code",200,"retryAfter",60,"message","OK");}
 private Challenge challenge(HttpSession s){Object value=s==null?null:s.getAttribute(KEY);if(!(value instanceof Challenge c))throw SchoolAccounts.error(400,"请重新获取验证码 / Request a new code");var user=c.canonical()==null?null:users.findByEmail(c.canonical());if(c.expires()<System.currentTimeMillis()||c.attempts()>=5||(c.canonical()!=null&&(user==null||!Objects.equals(user.getPassword(),c.version())||!emails.display(c.canonical()).equals(c.login())))){s.removeAttribute(KEY);throw SchoolAccounts.error(400,"验证码已失效，请重新获取 / Code expired. Request a new code");}return c;}
 @PostMapping("/verify") public Object verify(@Valid @RequestBody CodeInput body,HttpServletRequest r){origin(r);var s=r.getSession();synchronized(s){var c=challenge(s);s.setAttribute(KEY,new Challenge(c.login(),c.canonical(),c.version(),c.digest(),c.expires(),c.attempts()+1,false));if(c.canonical()==null||!c.login().equals(LoginEmails.normalize(body.email()))||!MessageDigest.isEqual(c.digest().getBytes(StandardCharsets.UTF_8),hash(body.code()).getBytes(StandardCharsets.UTF_8)))throw SchoolAccounts.error(400,"验证码不正确 / Incorrect verification code");s.setAttribute(KEY,new Challenge(c.login(),c.canonical(),c.version(),c.digest(),c.expires(),c.attempts(),true));return Map.of("code",200,"account",SchoolAccounts.key(c.canonical()));}}
 @PostMapping("/complete") @Transactional public synchronized Object complete(@Valid @RequestBody PasswordInput body,HttpServletRequest r){origin(r);var s=r.getSession();synchronized(s){var c=challenge(s);if(!c.verified())throw SchoolAccounts.error(403,"请先验证邮箱 / Verify your email first");PasswordPolicy.require(body.password());String id=SchoolAccounts.key(c.canonical());if(body.keyEnvelope()!=null&&!body.keyEnvelope().isBlank())vault.replace(id,body.keyEnvelope());String encoded=PasswordCodec.encode(body.password());var u=students.findByEmail(c.canonical());if(u!=null){u.setPassword(encoded);students.save(u);}var t=teachers.findByEmail(c.canonical());if(t!=null){t.setPassword(encoded);teachers.save(t);}var p=presidents.findByEmail(c.canonical());if(p!=null){p.setPassword(encoded);presidents.save(p);}var a=admins.findByAdminEmail(c.canonical());if(a!=null){a.setPassword(encoded);admins.save(a);}sessions.revoke(c.canonical());s.removeAttribute(KEY);s.invalidate();return Map.of("code",200,"message","OK");}}
}
