package com.qpwflshclub.formal_club.social;
import com.qpwflshclub.formal_club.pojo.User.*;
import com.qpwflshclub.formal_club.workspace.WorkspaceAccess;
import jakarta.servlet.http.HttpServletRequest;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.server.ResponseStatusException;
import java.io.IOException;
import java.util.*;
import java.util.stream.Collectors;

@RestController
@RequestMapping("/api/campus-social")
public class SocialController {
 @org.springframework.beans.factory.annotation.Autowired private MessageKeys messageKeys;
 @org.springframework.beans.factory.annotation.Autowired private WallFiles files;
 @org.springframework.beans.factory.annotation.Autowired private PostViews views;
 @org.springframework.beans.factory.annotation.Autowired private ChatPreferences preferences;
 @org.springframework.beans.factory.annotation.Autowired private PostPins pins;
 @org.springframework.beans.factory.annotation.Autowired private SocialNotifications notifications;
 private final SchoolAccounts accounts;private final WorkspaceAccess access;private final SocialStore store;private final ClubAppointments appointments;
 public SocialController(SchoolAccounts accounts,WorkspaceAccess access,SocialStore store,ClubAppointments appointments){this.accounts=accounts;this.access=access;this.store=store;this.appointments=appointments;}
 private UserBase current(HttpServletRequest request,boolean write){UserBase u=accounts.current(request);if(write)access.mutation(request);return u;}
 private boolean mayPost(UserBase u){return u instanceof User||u instanceof ClubPresident||u instanceof Teacher||u instanceof Admin;}
 private void canPost(UserBase u){if(!mayPost(u))throw SchoolAccounts.error(403,"当前账号无法发布校园动态 / This account cannot post");}
 private String key(UserBase u){return SchoolAccounts.key(u.getEmail());}
 @GetMapping public Map<String,Object> bootstrap(HttpServletRequest request){UserBase u=current(request,false);return Map.of("account",accounts.view(u),"token",access.token(request),"canPost",mayPost(u),"admin",u instanceof Admin,"clubs",access.clubs(u).stream().map(c->Map.of("id",c.getId(),"name",Objects.toString(c.getClubName(),"社团"))).toList());}
 @GetMapping("/users") public List<SchoolAccounts.Account> search(@RequestParam String keyword,@RequestParam(defaultValue="false")boolean includeSelf,HttpServletRequest request){return accounts.search(keyword,key(current(request,false)),includeSelf);}
 private Map<String,SchoolAccounts.Account> directory(){return accounts.directory();}
 private SchoolAccounts.Account author(Map<String,SchoolAccounts.Account> people,String id){return people.getOrDefault(id,new SchoolAccounts.Account(id,"已注销用户","","student"));}
 @GetMapping("/posts") public Map<String,Object> posts(@RequestParam(defaultValue="")String before,@RequestParam(defaultValue="")String category,@RequestParam(defaultValue="0")int club,@RequestParam(defaultValue="")String keyword,@RequestParam(defaultValue="1")int page,HttpServletRequest request)throws IOException{
  String me=key(current(request,false));var data=store.snapshot();var people=directory();String query=SchoolAccounts.searchQuery(keyword.substring(0,Math.min(keyword.length(),100)));List<SocialStore.Post> posts=data.posts().stream().filter(p->(query.isBlank()||ContentModeration.normalize(p.text()).contains(query)||!p.anonymous()&&SchoolAccounts.matches(people.get(p.author()),query))&&(category.isBlank()||category.equals(p.category()))&&(club==0||p.club()==club&&!p.anonymous())).toList();posts=pins==null?posts:pins.ordered(posts,false);int total=posts.size(),pages=Math.max(1,(total+19)/20);page=Math.min(Math.max(page,1),pages);int start=(page-1)*20;if(!before.isEmpty()){for(int i=0;i<posts.size();i++)if(posts.get(i).id().equals(before)){start=i+1;break;}}
  var grouped=data.replies().stream().collect(java.util.stream.Collectors.groupingBy(SocialStore.Reply::post));
  var slice=posts.subList(Math.min(start,posts.size()),Math.min(start+20,posts.size()));List<Map<String,Object>> result=new ArrayList<>();for(var p:slice)result.add(postView(p,grouped.getOrDefault(p.id(),List.of()),people,me));
  return Map.of("items",result,"next",start+20<posts.size()?slice.getLast().id():"","page",page,"pages",pages,"total",total);
 }
 @GetMapping("/users/{id}/posts") public Object userPosts(@PathVariable String id,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="false")boolean media,HttpServletRequest request)throws IOException{
  String me=key(current(request,false));accounts.find(id);var data=store.snapshot();var people=directory();var own=data.posts().stream().filter(p->p.author().equals(id)&&!p.anonymous()&&(!media||p.attachments().stream().map(a->files==null?a:files.resolved(a)).anyMatch(a->a.type().startsWith("image/")||a.type().startsWith("video/")))).toList();own=pins==null?own:pins.ordered(own,true);int pages=Math.max(1,(own.size()+19)/20);page=Math.min(Math.max(1,page),pages);var grouped=data.replies().stream().collect(Collectors.groupingBy(SocialStore.Reply::post));List<Map<String,Object>> result=new ArrayList<>();for(var p:own.subList(Math.min((page-1)*20,own.size()),Math.min(page*20,own.size())))result.add(postView(p,grouped.getOrDefault(p.id(),List.of()),people,me));return Map.of("items",result,"total",own.size(),"page",page,"pages",pages);
 }
 private Map<String,Object> replyView(SocialStore.Reply r,SocialStore.Post parent,Map<String,SchoolAccounts.Account> people,String me){Map<String,Object> row=new LinkedHashMap<>();row.put("id",r.id());row.put("author",parent.anonymous()&&parent.author().equals(r.author())?new SchoolAccounts.Account("","匿名楼主","","anonymous"):author(people,r.author()));row.put("text",r.text());row.put("createdAt",r.createdAt());row.put("likes",r.likes().size());row.put("liked",r.likes().contains(me));row.put("own",r.author().equals(me));row.put("parentReply",r.parentReply());try{var replies=store.snapshot().replies();row.put("replyCount",replies.stream().filter(v->v.parentReply().equals(r.id())).count());replies.stream().filter(v->v.id().equals(r.parentReply())&&v.post().equals(r.post())).findFirst().ifPresent(v->row.put("replyingTo",parent.anonymous()&&parent.author().equals(v.author())?new SchoolAccounts.Account("","匿名楼主","","anonymous"):author(people,v.author())));}catch(IOException e){throw new java.io.UncheckedIOException(e);}return row;}

 private Map<String,Object> postView(SocialStore.Post p,List<SocialStore.Reply> replies,Map<String,SchoolAccounts.Account> people,String me)throws IOException{Map<String,Object> row=new LinkedHashMap<>();row.put("id",p.id());row.put("profilePinned",pins!=null&&pins.profile(p));row.put("wallPinned",pins!=null&&pins.wall(p));row.put("views",views==null?0:views.count(p.id()));row.put("club",p.club());row.put("clubName",Objects.toString(p.clubName(),""));row.put("author",p.anonymous()?new SchoolAccounts.Account("","匿名同学","","anonymous"):author(people,p.author()));row.put("text",p.text());row.put("mentions",notifications==null?List.of():notifications.mentions(p.id()));row.put("attachments",p.attachments().stream().map(a->files==null?a:files.resolved(a)).toList());row.put("createdAt",p.createdAt());row.put("likes",p.likes().size());row.put("liked",p.likes().contains(me));row.put("replies",replies.size());row.put("own",p.author().equals(me));row.put("anonymous",p.anonymous());row.put("category",Objects.toString(p.category(),"general"));if(!replies.isEmpty()){int max=replies.stream().mapToInt(r->r.likes().size()).max().orElse(0);var candidates=replies.stream().filter(r->r.likes().size()==max).toList();var chosen=candidates.get(java.util.concurrent.ThreadLocalRandom.current().nextInt(candidates.size()));row.put("previewReply",replyView(chosen,p,people,me));}return row;}
 @GetMapping("/posts/{id}") public Map<String,Object> detail(@PathVariable String id,HttpServletRequest request)throws IOException{String me=key(current(request,false));var d=store.snapshot();var p=d.posts().stream().filter(v->v.id().equals(id)).findFirst().orElseThrow(()->SchoolAccounts.error(404,"帖子不存在"));return postView(p,d.replies().stream().filter(v->v.post().equals(id)).toList(),directory(),me);}
 public record ViewInput(List<String> ids){}
 @PostMapping("/posts/views") public Object viewed(@RequestBody ViewInput body,HttpServletRequest request)throws IOException{String me=key(current(request,true));if(body.ids()==null||body.ids().isEmpty()||body.ids().size()>20)throw SchoolAccounts.error(400,"一次最多记录 20 条帖子");var existing=store.snapshot().posts().stream().map(SocialStore.Post::id).collect(Collectors.toSet());if(body.ids().stream().anyMatch(id->!existing.contains(id)))throw SchoolAccounts.error(404,"帖子不存在");return Map.of("views",views.record(body.ids(),me));}
 @DeleteMapping("/posts/{id}/replies/{reply}") public Object deleteReply(@PathVariable String id,@PathVariable String reply,HttpServletRequest request)throws IOException{var u=current(request,true);store.deleteReply(id,reply,key(u),u instanceof Admin);return Map.of("ok",true);}
 @PutMapping("/posts/{id}/replies/{reply}/like") public Object likeReply(@PathVariable String id,@PathVariable String reply,@RequestBody LikeInput body,HttpServletRequest request)throws IOException{var u=current(request,true);store.likeReply(id,reply,key(u),body.liked());return Map.of("ok",true);}
 public Map<String,Object> posts(String before,String category,int club,String keyword,HttpServletRequest request)throws IOException{return posts(before,category,club,keyword,1,request);}
 public Map<String,Object> posts(String before,String category,int club,HttpServletRequest request)throws IOException{return posts(before,category,club,"",request);}
 public Map<String,Object> posts(String before,HttpServletRequest request)throws IOException{return posts(before,"",0,request);}
 public Map<String,Object> posts(String before,String category,HttpServletRequest request)throws IOException{return posts(before,category,0,request);}
 public record PostInput(String text,String category,boolean anonymous,int club,List<SocialNotifications.Mention> mentions){public PostInput(String text,String category,boolean anonymous,int club){this(text,category,anonymous,club,List.of());}public PostInput(String text,String category,boolean anonymous){this(text,category,anonymous,0);}}
 public record TextInput(String text){} public record LikeInput(boolean liked){} public record InviteInput(int club,String recipient,String role){} public record AcceptInput(boolean accept){}
 @PostMapping(value="/posts",consumes="application/json") public Object post(@RequestBody PostInput body,HttpServletRequest request)throws IOException{UserBase u=current(request,true);canPost(u);String clubName="";if(body.club()!=0){var club=access.require(u,body.club());if(body.anonymous())throw SchoolAccounts.error(400,"社团发布不能匿名");clubName=Objects.toString(club.getClubName(),"社团");}var mentions=notifications==null?List.<SocialNotifications.Mention>of():notifications.validate(body.text(),body.mentions(),accounts);var p=store.post(key(u),body.text(),Objects.toString(body.category(),"general"),body.anonymous(),body.club(),clubName);if(notifications!=null)notifications.attach(p.id(),mentions);audit(p.id(),key(u),body.anonymous());return Map.of("id",p.id());}
 private void audit(String post,String actor,boolean anonymous){org.slf4j.LoggerFactory.getLogger(getClass()).info("campus_post id={} account={} anonymous={}",post,actor,anonymous);}
 @PostMapping(value="/posts",consumes="multipart/form-data") public Object uploadPost(@RequestParam String text,@RequestParam(defaultValue="general")String category,@RequestParam(defaultValue="false")boolean anonymous,@RequestParam(defaultValue="0")int club,@RequestParam("files")List<org.springframework.web.multipart.MultipartFile> uploads,@RequestParam(defaultValue="[]")String mentions,HttpServletRequest request)throws IOException{
  var u=current(request,true);canPost(u);ContentModeration.check(text);SocialStore.text(text,1000);
  String name="";if(club!=0){name=access.require(u,club).getClubName();if(anonymous)throw SchoolAccounts.error(400,"社团发布不能匿名");}
  if(uploads.size()>4||uploads.stream().mapToLong(org.springframework.web.multipart.MultipartFile::getSize).sum()>40*1024*1024)throw SchoolAccounts.error(400,"最多 4 个附件，总计 40 MB / Up to 4 files, 40 MB total");
  List<SocialNotifications.Mention> tagged;try{tagged=notifications==null?List.of():notifications.validate(text,new com.fasterxml.jackson.databind.ObjectMapper().readValue(mentions,new com.fasterxml.jackson.core.type.TypeReference<List<SocialNotifications.Mention>>(){}),accounts);}catch(com.fasterxml.jackson.core.JsonProcessingException e){throw SchoolAccounts.error(400,"提及内容无效 / Invalid mention");}List<SocialStore.Attachment> attachments=new ArrayList<>();boolean saved=false;try{for(var upload:uploads)attachments.add(files.save(upload,anonymous));var post=store.post(key(u),text,category,anonymous,club,name,attachments);saved=true;if(notifications!=null)notifications.attach(post.id(),tagged);audit(post.id(),key(u),anonymous);return Map.of("id",post.id());}finally{if(!saved)for(var attachment:attachments)files.remove(attachment.id());}
 }
 public Object uploadPost(String text,String category,boolean anonymous,int club,List<org.springframework.web.multipart.MultipartFile> uploads,HttpServletRequest request)throws IOException{return uploadPost(text,category,anonymous,club,uploads,"[]",request);}
 @GetMapping("/posts/{post}/files/{id}") public ResponseEntity<org.springframework.core.io.Resource> download(@PathVariable String post,@PathVariable String id,HttpServletRequest request)throws IOException{
  current(request,false);var attachment=store.snapshot().posts().stream().filter(p->p.id().equals(post)).flatMap(p->p.attachments().stream()).filter(a->a.id().equals(id)).findFirst().orElseThrow(()->SchoolAccounts.error(404,"File not found"));
  attachment=files.resolved(attachment);
  var disposition=org.springframework.http.ContentDisposition.builder((attachment.type().startsWith("image/")||attachment.type().startsWith("video/"))?"inline":"attachment").filename(attachment.name(),java.nio.charset.StandardCharsets.UTF_8).build();
  return ResponseEntity.ok().header("Content-Type",attachment.type()).header("Content-Disposition",disposition.toString()).header("X-Content-Type-Options","nosniff").header("Content-Security-Policy","sandbox").header("Cache-Control","private, max-age=86400").body(new org.springframework.core.io.FileSystemResource(files.file(id)));
 }
 @DeleteMapping("/posts/{id}") public Map<String,Boolean> delete(@PathVariable String id,HttpServletRequest request)throws IOException{UserBase u=current(request,true);store.delete(id,key(u),u instanceof Admin);if(pins!=null)pins.remove(id);return Map.of("ok",true);}
 public record PinInput(String scope,boolean pinned){}
 @PutMapping("/posts/{id}/pin") public Object pin(@PathVariable String id,@RequestBody PinInput input,HttpServletRequest request)throws IOException{var u=current(request,true);var post=store.snapshot().posts().stream().filter(p->p.id().equals(id)).findFirst().orElseThrow(()->SchoolAccounts.error(404,"帖子不存在 / Post not found"));pins.update(post,key(u),u instanceof Admin,input.scope(),input.pinned());return Map.of("profilePinned",pins.profile(post),"wallPinned",pins.wall(post));}
 @PutMapping("/posts/{id}/like") public Map<String,Boolean> like(@PathVariable String id,@RequestBody LikeInput body,HttpServletRequest request)throws IOException{UserBase u=current(request,true);store.like(id,key(u),body.liked());return Map.of("ok",true);}
 @GetMapping("/posts/{id}/replies") public List<Map<String,Object>> replies(@PathVariable String id,HttpServletRequest request)throws IOException{String me=key(current(request,false));var people=directory();var snapshot=store.snapshot();var parent=snapshot.posts().stream().filter(p->p.id().equals(id)).findFirst().orElseThrow(()->SchoolAccounts.error(404,"帖子不存在"));return snapshot.replies().stream().filter(r->r.post().equals(id)).map(r->replyView(r,parent,people,me)).toList();}
 public Object reply(String id,TextInput body,HttpServletRequest request)throws IOException{return reply(id,new ReplyInput(body.text(),""),request);}
 public record ReplyInput(String text,String parentReply){}
 @PostMapping("/posts/{id}/replies") public Object reply(@PathVariable String id,@RequestBody ReplyInput body,HttpServletRequest request)throws IOException{UserBase u=current(request,true);canPost(u);var r=store.reply(id,key(u),body.text(),body.parentReply());return Map.of("id",r.id());}
 @GetMapping("/inbox") public List<Map<String,Object>> inbox(HttpServletRequest request)throws IOException{
  String me=key(current(request,false));var data=store.snapshot();var people=directory();Map<String,String> last=new HashMap<>(),preview=new HashMap<>();Map<String,Long> unread=new HashMap<>();Map<String,SocialStore.Message> latest=new HashMap<>();
  for(var m:data.messages()){if(!m.sender().equals(me)&&!m.recipient().equals(me))continue;String peer=m.sender().equals(me)?m.recipient():m.sender();latest.put(peer,m);last.put(peer,m.createdAt());preview.put(peer,m.recalled()?"消息已撤回":m.text().startsWith("e2ee:v1:")?"端到端加密消息":"历史消息（未加密）");if(m.recipient().equals(me)&&!m.read())unread.merge(peer,1L,Long::sum);}
  for(var i:data.invitations()){if(!i.sender().equals(me)&&!i.recipient().equals(me))continue;String peer=i.sender().equals(me)?i.recipient():i.sender();if(i.createdAt().compareTo(last.getOrDefault(peer,""))>0){last.put(peer,i.createdAt());preview.put(peer,"任职邀请 · "+i.clubName());}if(i.recipient().equals(me)&&i.status().equals("pending"))unread.merge(peer,1L,Long::sum);}
  if(preferences!=null)for(String peer:preferences.peers(me)){last.putIfAbsent(peer,"");preview.putIfAbsent(peer,"");}
  return last.keySet().stream().sorted((a,b)->{boolean ap=preferences!=null&&preferences.get(me,a).pinned(),bp=preferences!=null&&preferences.get(me,b).pinned();return ap!=bp?(ap?-1:1):last.get(b).compareTo(last.get(a));}).map(peer->Map.<String,Object>of("account",author(people,peer),"latestMessage",latest.containsKey(peer)?latest.get(peer):Map.of(),"preview",preview.get(peer),"updatedAt",last.get(peer),"unread",unread.getOrDefault(peer,0L),"pinned",preferences!=null&&preferences.get(me,peer).pinned(),"blocked",preferences!=null&&preferences.get(me,peer).blocked())).toList();
 }
 @PutMapping("/conversations/{peer}/preferences") public Object chatPreference(@PathVariable String peer,@RequestBody ChatPreferences.Preference input,HttpServletRequest request)throws IOException{String me=key(current(request,true));accounts.find(peer);return preferences.update(me,peer,input);}
 private boolean pair(String a,String b,String me,String peer){return a.equals(me)&&b.equals(peer)||a.equals(peer)&&b.equals(me);}
 @GetMapping("/conversations/{peer}") public Map<String,Object> conversation(@PathVariable String peer,@RequestParam(defaultValue="")String before,HttpServletRequest request)throws IOException{
  String me=key(current(request,false));UserBase target=accounts.find(peer);var d=store.snapshot();var all=d.messages().stream().filter(m->pair(m.sender(),m.recipient(),me,peer)).toList();int end=all.size();if(!before.isEmpty())for(int n=0;n<all.size();n++)if(all.get(n).id().equals(before)){end=n;break;}
  var batch=all.subList(Math.max(0,end-100),end);return Map.of("account",accounts.view(target),"messages",batch,"recalledIds",all.stream().filter(SocialStore.Message::recalled).map(SocialStore.Message::id).toList(),"readIds",all.stream().filter(SocialStore.Message::read).map(SocialStore.Message::id).toList(),"older",end>100?batch.getFirst().id():"","invitations",d.invitations().stream().filter(i->pair(i.sender(),i.recipient(),me,peer)).toList(),"preferences",preferences==null?new ChatPreferences.Preference(false,false):preferences.get(me,peer),"messagingAllowed",preferences==null||preferences.allowed(me,peer));
 }
 @PostMapping("/conversations/{peer}") public Object message(@PathVariable String peer,@RequestBody TextInput body,HttpServletRequest request)throws IOException{UserBase me=current(request,true);accounts.find(peer);if(preferences!=null)preferences.requireAllowed(key(me),peer);messageKeys.validateMessage(key(me),peer,body.text());return store.message(key(me),peer,body.text());}
 @PostMapping(value="/conversations/{peer}/attachments",consumes="multipart/form-data") public Object messageFiles(@PathVariable String peer,@RequestParam String text,@RequestParam("files")List<org.springframework.web.multipart.MultipartFile> uploads,HttpServletRequest request)throws IOException{
  String me=key(current(request,true));accounts.find(peer);if(preferences!=null)preferences.requireAllowed(me,peer);messageKeys.validateMessage(me,peer,text);
  if(uploads.isEmpty()||uploads.size()>4||uploads.stream().mapToLong(org.springframework.web.multipart.MultipartFile::getSize).sum()>40L*1024*1024+64)throw SchoolAccounts.error(400,"最多 4 个附件，合计 40 MB");
  Map<String,byte[]> encrypted=new LinkedHashMap<>();for(var upload:uploads){String id=upload.getOriginalFilename();if(id==null||!id.matches("[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}")||upload.getSize()<16||upload.getSize()>20L*1024*1024+16||encrypted.containsKey(id))throw SchoolAccounts.error(400,"附件格式无效或超过 20 MB");encrypted.put(id,upload.getBytes());}
  return store.message(me,peer,text,encrypted);
 }
 @GetMapping("/conversations/{peer}/messages/{id}/files/{file}") public ResponseEntity<byte[]> messageFile(@PathVariable String peer,@PathVariable String id,@PathVariable String file,HttpServletRequest request)throws IOException{
  byte[] encrypted=store.messageFile(key(current(request,false)),peer,id,file);return ResponseEntity.ok().header("Cache-Control","private, no-store").header("X-Content-Type-Options","nosniff").header("Content-Disposition","attachment; filename=encrypted.bin").contentType(org.springframework.http.MediaType.APPLICATION_OCTET_STREAM).body(encrypted);
 }
 @DeleteMapping("/conversations/{peer}/messages/{id}") public Object recall(@PathVariable String peer,@PathVariable String id,HttpServletRequest request)throws IOException{store.recall(id,key(current(request,true)),peer);return Map.of("ok",true);}
 @PutMapping("/conversations/{peer}/history/{id}") public Object encryptHistory(@PathVariable String peer,@PathVariable String id,@RequestBody TextInput body,HttpServletRequest request)throws IOException{String me=key(current(request,true));accounts.find(peer);messageKeys.validateMessage(me,peer,body.text());store.encryptHistory(id,me,peer,body.text());return Map.of("ok",true);}
 @PostMapping("/conversations/{peer}/read") public Map<String,Boolean> read(@PathVariable String peer,HttpServletRequest request)throws IOException{String me=key(current(request,true));store.markRead(me,peer);return Map.of("ok",true);}
 @PostMapping("/invitations") public Object invite(@RequestBody InviteInput body,HttpServletRequest request)throws IOException{UserBase sender=current(request,true),recipient=accounts.find(body.recipient());if(preferences!=null)preferences.requireAllowed(key(sender),key(recipient));var club=appointments.authorize(sender,body.club());appointments.eligible(recipient,body.club());return store.invite(key(sender),key(recipient),body.club(),club.getClubName(),body.role());}
 @PostMapping("/invitations/{id}/respond") public Object respond(@PathVariable String id,@RequestBody AcceptInput body,HttpServletRequest request)throws IOException{return store.respond(id,key(current(request,true)),body.accept(),appointments::accept);}
 @ExceptionHandler(ResponseStatusException.class) public ResponseEntity<?> error(ResponseStatusException e){return ResponseEntity.status(e.getStatusCode()).body(Map.of("message",Objects.toString(e.getReason(),"请求未成功")));}
 @ExceptionHandler(IOException.class) public ResponseEntity<?> diskError(IOException e){return ResponseEntity.internalServerError().body(Map.of("message","保存或读取失败，请稍后重试"));}
}
