package com.qpwflshclub.formal_club.social;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import java.nio.file.*;
import java.io.IOException;
import java.time.*;
import java.util.*;

@Service
public class SocialStore {
 public record Attachment(String id,String name,String type,long size){}
 public record Post(String id,String author,String text,String createdAt,Set<String> likes,String category,boolean anonymous,int club,String clubName,List<Attachment> attachments){public Post{attachments=attachments==null?List.of():List.copyOf(attachments);}public Post(String id,String author,String text,String createdAt,Set<String> likes,String category,boolean anonymous,int club,String clubName){this(id,author,text,createdAt,likes,category,anonymous,club,clubName,List.of());}public Post(String id,String author,String text,String createdAt,Set<String> likes,String category,boolean anonymous){this(id,author,text,createdAt,likes,category,anonymous,0,"");}public Post(String id,String author,String text,String createdAt,Set<String> likes){this(id,author,text,createdAt,likes,"general",false);}}
 public record Reply(String id,String post,String author,String text,String createdAt,Set<String> likes,String parentReply){public Reply{likes=likes==null?Set.of():Set.copyOf(likes);parentReply=Objects.toString(parentReply,"");}public Reply(String id,String post,String author,String text,String createdAt,Set<String> likes){this(id,post,author,text,createdAt,likes,"");}public Reply(String id,String post,String author,String text,String createdAt){this(id,post,author,text,createdAt,Set.of(),"");}}
 public record Message(String id,String sender,String recipient,String text,String createdAt,boolean read,boolean recalled){public Message(String id,String sender,String recipient,String text,String createdAt,boolean read){this(id,sender,recipient,text,createdAt,read,false);}}
 public record Invitation(String id,String sender,String recipient,int club,String clubName,String role,String status,String createdAt){}
 public record Data(List<Post> posts,List<Reply> replies,List<Message> messages,List<Invitation> invitations){}
 private final ObjectMapper mapper;private final Path root;
 public SocialStore(ObjectMapper mapper,@Value("${club.social-dir:./data/campus-social}")String path){this.mapper=mapper;root=Path.of(path).toAbsolutePath().normalize();}
 public static String now(){return LocalDateTime.now(ZoneId.of("Asia/Shanghai")).toString();}
 private Data cached;
 private Data freeze(Data d){return new Data(d.posts().stream().map(p->new Post(p.id(),p.author(),p.text(),p.createdAt(),Set.copyOf(p.likes()),p.category(),p.anonymous(),p.club(),p.clubName(),p.attachments())).toList(),List.copyOf(d.replies()),List.copyOf(d.messages()),List.copyOf(d.invitations()));}
 private Data loaded()throws IOException{if(cached==null){Path f=root.resolve("social.json");cached=freeze(Files.exists(f)?mapper.readValue(f.toFile(),Data.class):new Data(List.of(),List.of(),List.of(),List.of()));}return cached;}
 private Data read()throws IOException{Data d=loaded();return new Data(new ArrayList<>(d.posts().stream().map(p->new Post(p.id(),p.author(),p.text(),p.createdAt(),new HashSet<>(p.likes()),p.category(),p.anonymous(),p.club(),p.clubName(),p.attachments())).toList()),new ArrayList<>(d.replies()),new ArrayList<>(d.messages()),new ArrayList<>(d.invitations()));}
 private void save(Data data)throws IOException{Files.createDirectories(root);Path tmp=Files.createTempFile(root,"social-",".tmp");try{mapper.writeValue(tmp.toFile(),data);Files.move(tmp,root.resolve("social.json"),StandardCopyOption.ATOMIC_MOVE,StandardCopyOption.REPLACE_EXISTING);cached=freeze(data);}finally{Files.deleteIfExists(tmp);}}
 public synchronized Data snapshot()throws IOException{return loaded();}
 public static String text(String value,int max){if(value==null||value.isBlank()||value.length()>max)throw SchoolAccounts.error(400,"内容不能为空，最多 "+max+" 字");return value.trim();}
 public synchronized Post post(String author,String text)throws IOException{return post(author,text,"general",false);}
 public synchronized Post post(String author,String text,String category,boolean anonymous)throws IOException{return post(author,text,category,anonymous,0,"");}
 public synchronized Post post(String author,String text,String category,boolean anonymous,int club,String clubName)throws IOException{return post(author,text,category,anonymous,club,clubName,List.of());}
 public synchronized Post post(String author,String text,String category,boolean anonymous,int club,String clubName,List<Attachment> attachments)throws IOException{ContentModeration.check(text);if(!Set.of("recruit","help","team","general","other").contains(category))throw SchoolAccounts.error(400,"请选择有效的发布类型");Data d=read();Post p=new Post(UUID.randomUUID().toString(),author,text(text,1000),now(),new HashSet<>(),category,anonymous,club,clubName,attachments);d.posts().add(0,p);save(d);return p;}
 private Post post(Data d,String id){return d.posts().stream().filter(p->p.id().equals(id)).findFirst().orElseThrow(()->SchoolAccounts.error(404,"帖子已不存在"));}
 public synchronized void delete(String id,String actor,boolean admin)throws IOException{Data d=read();Post p=post(d,id);if(!p.author().equals(actor)&&!admin)throw SchoolAccounts.error(403,"只能删除自己的帖子");d.posts().remove(p);d.replies().removeIf(r->r.post().equals(id));save(d);}
 public synchronized void like(String id,String actor,boolean liked)throws IOException{Data d=read();Post p=post(d,id);if(liked)p.likes().add(actor);else p.likes().remove(actor);save(d);}
 public synchronized void deleteReply(String postId,String replyId,String actor,boolean admin)throws IOException{Data d=read();post(d,postId);Reply reply=d.replies().stream().filter(r->r.id().equals(replyId)&&r.post().equals(postId)).findFirst().orElseThrow(()->SchoolAccounts.error(404,"回复不存在"));if(!reply.author().equals(actor)&&!admin)throw SchoolAccounts.error(403,"只能删除自己的评论");d.replies().remove(reply);save(d);}
 public synchronized void likeReply(String postId,String replyId,String actor,boolean liked)throws IOException{Data d=read();post(d,postId);for(int i=0;i<d.replies().size();i++){Reply r=d.replies().get(i);if(r.id().equals(replyId)&&r.post().equals(postId)){Set<String> likes=new HashSet<>(r.likes());if(liked)likes.add(actor);else likes.remove(actor);d.replies().set(i,new Reply(r.id(),r.post(),r.author(),r.text(),r.createdAt(),likes,r.parentReply()));save(d);return;}}throw SchoolAccounts.error(404,"回复不存在");}
 public synchronized Reply reply(String id,String actor,String text)throws IOException{return reply(id,actor,text,"");}
 public synchronized Reply reply(String id,String actor,String text,String parentReply)throws IOException{ContentModeration.check(text);Data d=read();post(d,id);String target=Objects.toString(parentReply,"");if(!target.isEmpty()&&d.replies().stream().noneMatch(v->v.id().equals(target)&&v.post().equals(id)))throw SchoolAccounts.error(404,"被回复的评论不存在 / Comment not found");Reply r=new Reply(UUID.randomUUID().toString(),id,actor,text(text,500),now(),Set.of(),target);d.replies().add(r);save(d);return r;}

 public synchronized Message message(String sender,String recipient,String text)throws IOException{return message(sender,recipient,text,Map.of());}
 public synchronized Message message(String sender,String recipient,String text,Map<String,byte[]> attachments)throws IOException{
  if(sender.equals(recipient))throw SchoolAccounts.error(400,"不能给自己发送私信");
  if(attachments.size()>4||attachments.values().stream().mapToLong(v->v.length).sum()>40L*1024*1024+64)throw SchoolAccounts.error(400,"最多 4 个附件，合计 40 MB");
  for(var entry:attachments.entrySet())if(!validFileId(entry.getKey())||entry.getValue().length<16||entry.getValue().length>20L*1024*1024+16)throw SchoolAccounts.error(400,"附件格式无效或超过 20 MB");
  Data d=read();if(text!=null&&text.startsWith("e2ee:v1:")&&d.messages().stream().anyMatch(m->m.sender().equals(sender)&&m.text().equals(text)))throw SchoolAccounts.error(409,"请勿重复发送同一条消息");
  Message m=new Message(UUID.randomUUID().toString(),sender,recipient,text(text,16000),now(),false);
  try{
   if(!attachments.isEmpty()){Path directory=messageDirectory(m.id());Files.createDirectories(directory);privatePermissions(directory,true);for(var entry:attachments.entrySet()){Path file=directory.resolve(entry.getKey()+".bin");Files.write(file,entry.getValue(),StandardOpenOption.CREATE_NEW);privatePermissions(file,false);}}
   d.messages().add(m);save(d);return m;
  }catch(IOException|RuntimeException failure){try{removeMessageFiles(m.id());}catch(IOException cleanup){failure.addSuppressed(cleanup);}throw failure;}
 }
 private static boolean validFileId(String id){return id!=null&&id.matches("[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}");}
 private Path messageDirectory(String id){if(!validFileId(id))throw SchoolAccounts.error(404,"附件不存在");return root.resolve("message-files").resolve(id);}
 private static void privatePermissions(Path path,boolean directory)throws IOException{try{Files.setPosixFilePermissions(path,java.nio.file.attribute.PosixFilePermissions.fromString(directory?"rwx------":"rw-------"));}catch(UnsupportedOperationException ignored){}}
 private void removeMessageFiles(String id)throws IOException{Path directory=messageDirectory(id);if(Files.exists(directory)){try(var children=Files.list(directory)){for(Path file:children.toList())Files.deleteIfExists(file);}Files.deleteIfExists(directory);}}
 public synchronized byte[] messageFile(String account,String peer,String message,String attachment)throws IOException{
  var m=loaded().messages().stream().filter(v->v.id().equals(message)&&!v.recalled()&&((v.sender().equals(account)&&v.recipient().equals(peer))||(v.sender().equals(peer)&&v.recipient().equals(account)))).findFirst().orElseThrow(()->SchoolAccounts.error(404,"附件不存在"));
  if(!validFileId(attachment))throw SchoolAccounts.error(404,"附件不存在");Path file=messageDirectory(m.id()).resolve(attachment+".bin");if(!Files.isRegularFile(file))throw SchoolAccounts.error(404,"附件不存在");return Files.readAllBytes(file);
 }
 public synchronized void encryptHistory(String id,String sender,String recipient,String encrypted)throws IOException{Data d=read();for(int n=0;n<d.messages().size();n++){Message m=d.messages().get(n);if(!m.id().equals(id))continue;if(!m.sender().equals(sender)||!m.recipient().equals(recipient))throw SchoolAccounts.error(403,"只能加密自己发送的历史消息");if(m.recalled())throw SchoolAccounts.error(409,"消息已撤回 / Message recalled");if(m.text().startsWith("e2ee:v1:"))return;d.messages().set(n,new Message(m.id(),m.sender(),m.recipient(),encrypted,m.createdAt(),m.read()));save(d);return;}throw SchoolAccounts.error(404,"消息不存在");}
 public synchronized void markRead(String recipient,String sender)throws IOException{Data d=read();boolean changed=false;for(int i=0;i<d.messages().size();i++){Message m=d.messages().get(i);if(m.recipient().equals(recipient)&&m.sender().equals(sender)&&!m.read()){d.messages().set(i,new Message(m.id(),m.sender(),m.recipient(),m.text(),m.createdAt(),true,m.recalled()));changed=true;}}if(changed)save(d);}
 public synchronized void recall(String id,String sender,String peer)throws IOException{Data d=read();for(int i=0;i<d.messages().size();i++){Message m=d.messages().get(i);if(!m.id().equals(id))continue;if(!m.sender().equals(sender)||!m.recipient().equals(peer))throw SchoolAccounts.error(403,"只能撤回自己发送的消息 / You can only recall your own messages");d.messages().set(i,new Message(m.id(),m.sender(),m.recipient(),"",m.createdAt(),true,true));save(d);removeMessageFiles(m.id());return;}throw SchoolAccounts.error(404,"消息不存在 / Message not found");}
 public synchronized void readMessages(Set<String> ids,String recipient)throws IOException{Data d=read();boolean changed=false;for(int i=0;i<d.messages().size();i++){var m=d.messages().get(i);if(ids.contains(m.id())&&m.recipient().equals(recipient)&&!m.read()){d.messages().set(i,new Message(m.id(),m.sender(),m.recipient(),m.text(),m.createdAt(),true,m.recalled()));changed=true;}}if(changed)save(d);}
 public synchronized Invitation invite(String sender,String recipient,int club,String name,String role)throws IOException{
  if(!Set.of("president","vice_president").contains(role))throw SchoolAccounts.error(400,"任职类型无效");if(sender.equals(recipient))throw SchoolAccounts.error(400,"请邀请其他账号");Data d=read();if(d.invitations().stream().anyMatch(i->i.club()==club&&i.recipient().equals(recipient)&&i.status().equals("pending")))throw SchoolAccounts.error(409,"对方已有本社团待处理的邀请");Invitation i=new Invitation(UUID.randomUUID().toString(),sender,recipient,club,name,role,"pending",now());d.invitations().add(i);save(d);return i;
 }
 public synchronized Invitation respond(String id,String actor,boolean accept,java.util.function.Consumer<Invitation> appointment)throws IOException{
  Data d=read();for(int n=0;n<d.invitations().size();n++){Invitation i=d.invitations().get(n);if(!i.id().equals(id))continue;if(!i.recipient().equals(actor))throw SchoolAccounts.error(403,"只有被邀请的账号可以处理此邀请");if(!i.status().equals("pending"))throw SchoolAccounts.error(409,"邀请已处理");if(accept)appointment.accept(i);Invitation next=new Invitation(i.id(),i.sender(),i.recipient(),i.club(),i.clubName(),i.role(),accept?"accepted":"declined",i.createdAt());d.invitations().set(n,next);save(d);return next;}throw SchoolAccounts.error(404,"邀请不存在");
 }
 public synchronized Set<String> removeAccount(String id)throws IOException{Data d=read();Set<String> posts=new HashSet<>();d.posts().removeIf(p->{if(p.author().equals(id)){posts.add(p.id());return true;}p.likes().remove(id);return false;});d.replies().removeIf(v->v.author().equals(id)||posts.contains(v.post()));d.replies().replaceAll(v->{var likes=new HashSet<>(v.likes());likes.remove(id);return new Reply(v.id(),v.post(),v.author(),v.text(),v.createdAt(),likes,v.parentReply());});var removedMessages=d.messages().stream().filter(v->v.sender().equals(id)||v.recipient().equals(id)).map(Message::id).toList();d.messages().removeIf(v->v.sender().equals(id)||v.recipient().equals(id));d.invitations().removeIf(v->v.sender().equals(id)||v.recipient().equals(id));save(d);for(String message:removedMessages)removeMessageFiles(message);return posts;}
}
