package com.qpwflshclub.formal_club.config;
import org.junit.jupiter.api.Test;import java.time.*;import static org.assertj.core.api.Assertions.*;
class AccountSecurityTest {
 @Test void namesAcceptEitherScriptAndAtLeastOne(){RegistrationNames.validate("Jason Li","");RegistrationNames.validate("","张三");RegistrationNames.validate("张三",null);RegistrationNames.validate(null,"李四");assertThatThrownBy(()->RegistrationNames.validate(" ",null)).hasMessageContaining("400");assertThatThrownBy(()->RegistrationNames.validate("x".repeat(101),"")).hasMessageContaining("400");}
 @Test void passwordRequirementsAreServerEnforced(){for(String p:new String[]{"weak","lowercaseonly123!","UPPERCASEONLY123!","NoNumberPassword!","NoSymbolPassword123","Aa1!short","Aa1 "+"a".repeat(20)})assertThat(PasswordPolicy.valid(p)).as(p).isFalse();assertThat(PasswordPolicy.valid("StrongPassword7!")).isTrue();assertThat(PasswordPolicy.valid("Strong密码Password7。" )).isTrue();}
 static class Time extends Clock{long now=0;public ZoneId getZone(){return ZoneOffset.UTC;}public Clock withZone(ZoneId zone){return this;}public Instant instant(){return Instant.ofEpochMilli(now);}}
 @Test void accountLockCannotBeBypassedByDifferentIpAndExpires(){var clock=new Time();var protection=new LoginProtection(clock);for(int i=0;i<5;i++){protection.check("USER@example.com","ip1");protection.failed("user@example.com","ip1");}assertThatThrownBy(()->protection.check(" USER@example.com ","ip2")).hasMessageContaining("429");clock.now=900001;assertThatCode(()->protection.check("user@example.com","ip1")).doesNotThrowAnyException();}
 @Test void ipLimitBlocksPasswordSprayingAndSuccessfulLoginResetsAccountOnly(){var p=new LoginProtection();for(int i=0;i<30;i++)p.failed("user"+i,"ip");assertThatThrownBy(()->p.check("another","ip")).hasMessageContaining("429");var clean=new LoginProtection();for(int i=0;i<4;i++)clean.failed("user","ip");clean.success("user");assertThatCode(()->clean.check("user","ip")).doesNotThrowAnyException();}
}
